// <auto-generated>
//     This code was generated by the DeepEquals source generator {{Version}}.
//     https://github.com/jeremy-morren/DeepEquals.SourceGenerator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. To change what is generated, edit the attributes
//     on the context class instead.
// </auto-generated>

/*
Context
    {{ContextName}} ({{ContextAccessibility}})

    Deep, by-value IEqualityComparer<T> implementations for the registered
    roots below and every type they reach. Comparison walks instance storage
        (fields and property backing fields), never a getter you wrote; strings
    compare ordinally, floating point bitwise, sets and dictionaries as
    unordered multisets under this context's own equality; reference cycles
    terminate and equal graphs always hash alike.

    Usage:
        {{ContextShortName}}.<TypeName>.Equals(left, right)
        {{ContextShortName}}.<TypeName>.GetHashCode(value)
        {{ContextShortName}}.GetEqualityComparer<T>()

Registered roots
{{Roots}}

{{ClosureHeading}}
{{Closure}}

Custom comparers
{{CustomComparers}}

Types compared through delegate field accessors (RequiresUnreferencedCode, RequiresDynamicCode)
{{UnsafeTypes}}

Options in effect
    MaxSwitchCases               = {{MaxSwitchCases}}
    MaxUnorderedCollisionRun     = {{MaxUnorderedCollisionRun}}
    MaxComparisonPairs           = {{MaxComparisonPairs}}
    MaxBinaryExpressionArity     = {{MaxBinaryExpressionArity}}
    StructPassByValueMaxByteSize = {{StructPassByValueMaxByteSize}}
    ExcludeInterfacesByPrefix    = {{ExcludeInterfacesByPrefix}}
    CycleHandling                = {{CycleHandling}}
    MaxDepth                     = {{MaxDepth}}
    MatchingHashDepth            = {{MatchingHashDepth}}
    Hashing                      = {{Hashing}}

Target
    Language version:    C# {{LanguageVersion}}
    Available:           {{CapabilitiesPresent}}
    Not available:       {{CapabilitiesAbsent}}

Reference
    What is generated:   https://github.com/jeremy-morren/DeepEquals.SourceGenerator/blob/main/docs/Implementation.md
    Diagnostics:         https://github.com/jeremy-morren/DeepEquals.SourceGenerator/blob/main/docs/Diagnostics.md
    
Diagnostics reported while generating this context
{{Diagnostics}}
*/

{{NullableDirective}}
// Suppress obsolete, experimental and preview members the consuming project already chose to use,
// and compiler hints that carry no meaning for emitted source.
#pragma warning disable {{SuppressedDiagnostics}}
