// <auto-generated/>
// Generated by eng/Generate-HashCodeCombine.ps1 -Width 64 -MaxArity 32. Do not edit.
using System.Runtime.CompilerServices;

namespace DeepEquals.SourceGeneration.Framework;

public static partial class DeepEqualsHashCode64
{
    /// <summary>Combines 1 already computed hash codes with the seeded xxHash64 stream.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong Combine(ulong h1)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            hash = seed + Prime5;
            hash += 8U;
            hash = QueueRound(hash, h1);
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 2 already computed hash codes with the seeded xxHash64 stream.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong Combine(ulong h1, ulong h2)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            hash = seed + Prime5;
            hash += 16U;
            hash = QueueRound(hash, h1);
            hash = QueueRound(hash, h2);
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 3 already computed hash codes with the seeded xxHash64 stream.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong Combine(ulong h1, ulong h2, ulong h3)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            hash = seed + Prime5;
            hash += 24U;
            hash = QueueRound(hash, h1);
            hash = QueueRound(hash, h2);
            hash = QueueRound(hash, h3);
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 4 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            hash = MixState(v1, v2, v3, v4);
            hash += 32U;
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 5 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            hash = MixState(v1, v2, v3, v4);
            hash += 40U;
            hash = QueueRound(hash, h5);
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 6 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            hash = MixState(v1, v2, v3, v4);
            hash += 48U;
            hash = QueueRound(hash, h5);
            hash = QueueRound(hash, h6);
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 7 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6, ulong h7)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            hash = MixState(v1, v2, v3, v4);
            hash += 56U;
            hash = QueueRound(hash, h5);
            hash = QueueRound(hash, h6);
            hash = QueueRound(hash, h7);
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 8 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6, ulong h7, ulong h8)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            v1 = Round(v1, h5);
            v2 = Round(v2, h6);
            v3 = Round(v3, h7);
            v4 = Round(v4, h8);
            hash = MixState(v1, v2, v3, v4);
            hash += 64U;
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 9 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6, ulong h7, ulong h8, ulong h9)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            v1 = Round(v1, h5);
            v2 = Round(v2, h6);
            v3 = Round(v3, h7);
            v4 = Round(v4, h8);
            hash = MixState(v1, v2, v3, v4);
            hash += 72U;
            hash = QueueRound(hash, h9);
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 10 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6, ulong h7, ulong h8, ulong h9, ulong h10)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            v1 = Round(v1, h5);
            v2 = Round(v2, h6);
            v3 = Round(v3, h7);
            v4 = Round(v4, h8);
            hash = MixState(v1, v2, v3, v4);
            hash += 80U;
            hash = QueueRound(hash, h9);
            hash = QueueRound(hash, h10);
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 11 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6, ulong h7, ulong h8, ulong h9, ulong h10, ulong h11)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            v1 = Round(v1, h5);
            v2 = Round(v2, h6);
            v3 = Round(v3, h7);
            v4 = Round(v4, h8);
            hash = MixState(v1, v2, v3, v4);
            hash += 88U;
            hash = QueueRound(hash, h9);
            hash = QueueRound(hash, h10);
            hash = QueueRound(hash, h11);
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 12 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6, ulong h7, ulong h8, ulong h9, ulong h10, ulong h11, ulong h12)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            v1 = Round(v1, h5);
            v2 = Round(v2, h6);
            v3 = Round(v3, h7);
            v4 = Round(v4, h8);
            v1 = Round(v1, h9);
            v2 = Round(v2, h10);
            v3 = Round(v3, h11);
            v4 = Round(v4, h12);
            hash = MixState(v1, v2, v3, v4);
            hash += 96U;
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 13 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6, ulong h7, ulong h8, ulong h9, ulong h10, ulong h11, ulong h12, ulong h13)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            v1 = Round(v1, h5);
            v2 = Round(v2, h6);
            v3 = Round(v3, h7);
            v4 = Round(v4, h8);
            v1 = Round(v1, h9);
            v2 = Round(v2, h10);
            v3 = Round(v3, h11);
            v4 = Round(v4, h12);
            hash = MixState(v1, v2, v3, v4);
            hash += 104U;
            hash = QueueRound(hash, h13);
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 14 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6, ulong h7, ulong h8, ulong h9, ulong h10, ulong h11, ulong h12, ulong h13, ulong h14)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            v1 = Round(v1, h5);
            v2 = Round(v2, h6);
            v3 = Round(v3, h7);
            v4 = Round(v4, h8);
            v1 = Round(v1, h9);
            v2 = Round(v2, h10);
            v3 = Round(v3, h11);
            v4 = Round(v4, h12);
            hash = MixState(v1, v2, v3, v4);
            hash += 112U;
            hash = QueueRound(hash, h13);
            hash = QueueRound(hash, h14);
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 15 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6, ulong h7, ulong h8, ulong h9, ulong h10, ulong h11, ulong h12, ulong h13, ulong h14, ulong h15)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            v1 = Round(v1, h5);
            v2 = Round(v2, h6);
            v3 = Round(v3, h7);
            v4 = Round(v4, h8);
            v1 = Round(v1, h9);
            v2 = Round(v2, h10);
            v3 = Round(v3, h11);
            v4 = Round(v4, h12);
            hash = MixState(v1, v2, v3, v4);
            hash += 120U;
            hash = QueueRound(hash, h13);
            hash = QueueRound(hash, h14);
            hash = QueueRound(hash, h15);
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 16 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6, ulong h7, ulong h8, ulong h9, ulong h10, ulong h11, ulong h12, ulong h13, ulong h14, ulong h15, ulong h16)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            v1 = Round(v1, h5);
            v2 = Round(v2, h6);
            v3 = Round(v3, h7);
            v4 = Round(v4, h8);
            v1 = Round(v1, h9);
            v2 = Round(v2, h10);
            v3 = Round(v3, h11);
            v4 = Round(v4, h12);
            v1 = Round(v1, h13);
            v2 = Round(v2, h14);
            v3 = Round(v3, h15);
            v4 = Round(v4, h16);
            hash = MixState(v1, v2, v3, v4);
            hash += 128U;
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 17 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6, ulong h7, ulong h8, ulong h9, ulong h10, ulong h11, ulong h12, ulong h13, ulong h14, ulong h15, ulong h16, ulong h17)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            v1 = Round(v1, h5);
            v2 = Round(v2, h6);
            v3 = Round(v3, h7);
            v4 = Round(v4, h8);
            v1 = Round(v1, h9);
            v2 = Round(v2, h10);
            v3 = Round(v3, h11);
            v4 = Round(v4, h12);
            v1 = Round(v1, h13);
            v2 = Round(v2, h14);
            v3 = Round(v3, h15);
            v4 = Round(v4, h16);
            hash = MixState(v1, v2, v3, v4);
            hash += 136U;
            hash = QueueRound(hash, h17);
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 18 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6, ulong h7, ulong h8, ulong h9, ulong h10, ulong h11, ulong h12, ulong h13, ulong h14, ulong h15, ulong h16, ulong h17, ulong h18)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            v1 = Round(v1, h5);
            v2 = Round(v2, h6);
            v3 = Round(v3, h7);
            v4 = Round(v4, h8);
            v1 = Round(v1, h9);
            v2 = Round(v2, h10);
            v3 = Round(v3, h11);
            v4 = Round(v4, h12);
            v1 = Round(v1, h13);
            v2 = Round(v2, h14);
            v3 = Round(v3, h15);
            v4 = Round(v4, h16);
            hash = MixState(v1, v2, v3, v4);
            hash += 144U;
            hash = QueueRound(hash, h17);
            hash = QueueRound(hash, h18);
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 19 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6, ulong h7, ulong h8, ulong h9, ulong h10, ulong h11, ulong h12, ulong h13, ulong h14, ulong h15, ulong h16, ulong h17, ulong h18, ulong h19)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            v1 = Round(v1, h5);
            v2 = Round(v2, h6);
            v3 = Round(v3, h7);
            v4 = Round(v4, h8);
            v1 = Round(v1, h9);
            v2 = Round(v2, h10);
            v3 = Round(v3, h11);
            v4 = Round(v4, h12);
            v1 = Round(v1, h13);
            v2 = Round(v2, h14);
            v3 = Round(v3, h15);
            v4 = Round(v4, h16);
            hash = MixState(v1, v2, v3, v4);
            hash += 152U;
            hash = QueueRound(hash, h17);
            hash = QueueRound(hash, h18);
            hash = QueueRound(hash, h19);
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 20 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6, ulong h7, ulong h8, ulong h9, ulong h10, ulong h11, ulong h12, ulong h13, ulong h14, ulong h15, ulong h16, ulong h17, ulong h18, ulong h19, ulong h20)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            v1 = Round(v1, h5);
            v2 = Round(v2, h6);
            v3 = Round(v3, h7);
            v4 = Round(v4, h8);
            v1 = Round(v1, h9);
            v2 = Round(v2, h10);
            v3 = Round(v3, h11);
            v4 = Round(v4, h12);
            v1 = Round(v1, h13);
            v2 = Round(v2, h14);
            v3 = Round(v3, h15);
            v4 = Round(v4, h16);
            v1 = Round(v1, h17);
            v2 = Round(v2, h18);
            v3 = Round(v3, h19);
            v4 = Round(v4, h20);
            hash = MixState(v1, v2, v3, v4);
            hash += 160U;
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 21 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6, ulong h7, ulong h8, ulong h9, ulong h10, ulong h11, ulong h12, ulong h13, ulong h14, ulong h15, ulong h16, ulong h17, ulong h18, ulong h19, ulong h20, ulong h21)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            v1 = Round(v1, h5);
            v2 = Round(v2, h6);
            v3 = Round(v3, h7);
            v4 = Round(v4, h8);
            v1 = Round(v1, h9);
            v2 = Round(v2, h10);
            v3 = Round(v3, h11);
            v4 = Round(v4, h12);
            v1 = Round(v1, h13);
            v2 = Round(v2, h14);
            v3 = Round(v3, h15);
            v4 = Round(v4, h16);
            v1 = Round(v1, h17);
            v2 = Round(v2, h18);
            v3 = Round(v3, h19);
            v4 = Round(v4, h20);
            hash = MixState(v1, v2, v3, v4);
            hash += 168U;
            hash = QueueRound(hash, h21);
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 22 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6, ulong h7, ulong h8, ulong h9, ulong h10, ulong h11, ulong h12, ulong h13, ulong h14, ulong h15, ulong h16, ulong h17, ulong h18, ulong h19, ulong h20, ulong h21, ulong h22)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            v1 = Round(v1, h5);
            v2 = Round(v2, h6);
            v3 = Round(v3, h7);
            v4 = Round(v4, h8);
            v1 = Round(v1, h9);
            v2 = Round(v2, h10);
            v3 = Round(v3, h11);
            v4 = Round(v4, h12);
            v1 = Round(v1, h13);
            v2 = Round(v2, h14);
            v3 = Round(v3, h15);
            v4 = Round(v4, h16);
            v1 = Round(v1, h17);
            v2 = Round(v2, h18);
            v3 = Round(v3, h19);
            v4 = Round(v4, h20);
            hash = MixState(v1, v2, v3, v4);
            hash += 176U;
            hash = QueueRound(hash, h21);
            hash = QueueRound(hash, h22);
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 23 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6, ulong h7, ulong h8, ulong h9, ulong h10, ulong h11, ulong h12, ulong h13, ulong h14, ulong h15, ulong h16, ulong h17, ulong h18, ulong h19, ulong h20, ulong h21, ulong h22, ulong h23)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            v1 = Round(v1, h5);
            v2 = Round(v2, h6);
            v3 = Round(v3, h7);
            v4 = Round(v4, h8);
            v1 = Round(v1, h9);
            v2 = Round(v2, h10);
            v3 = Round(v3, h11);
            v4 = Round(v4, h12);
            v1 = Round(v1, h13);
            v2 = Round(v2, h14);
            v3 = Round(v3, h15);
            v4 = Round(v4, h16);
            v1 = Round(v1, h17);
            v2 = Round(v2, h18);
            v3 = Round(v3, h19);
            v4 = Round(v4, h20);
            hash = MixState(v1, v2, v3, v4);
            hash += 184U;
            hash = QueueRound(hash, h21);
            hash = QueueRound(hash, h22);
            hash = QueueRound(hash, h23);
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 24 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6, ulong h7, ulong h8, ulong h9, ulong h10, ulong h11, ulong h12, ulong h13, ulong h14, ulong h15, ulong h16, ulong h17, ulong h18, ulong h19, ulong h20, ulong h21, ulong h22, ulong h23, ulong h24)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            v1 = Round(v1, h5);
            v2 = Round(v2, h6);
            v3 = Round(v3, h7);
            v4 = Round(v4, h8);
            v1 = Round(v1, h9);
            v2 = Round(v2, h10);
            v3 = Round(v3, h11);
            v4 = Round(v4, h12);
            v1 = Round(v1, h13);
            v2 = Round(v2, h14);
            v3 = Round(v3, h15);
            v4 = Round(v4, h16);
            v1 = Round(v1, h17);
            v2 = Round(v2, h18);
            v3 = Round(v3, h19);
            v4 = Round(v4, h20);
            v1 = Round(v1, h21);
            v2 = Round(v2, h22);
            v3 = Round(v3, h23);
            v4 = Round(v4, h24);
            hash = MixState(v1, v2, v3, v4);
            hash += 192U;
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 25 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6, ulong h7, ulong h8, ulong h9, ulong h10, ulong h11, ulong h12, ulong h13, ulong h14, ulong h15, ulong h16, ulong h17, ulong h18, ulong h19, ulong h20, ulong h21, ulong h22, ulong h23, ulong h24, ulong h25)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            v1 = Round(v1, h5);
            v2 = Round(v2, h6);
            v3 = Round(v3, h7);
            v4 = Round(v4, h8);
            v1 = Round(v1, h9);
            v2 = Round(v2, h10);
            v3 = Round(v3, h11);
            v4 = Round(v4, h12);
            v1 = Round(v1, h13);
            v2 = Round(v2, h14);
            v3 = Round(v3, h15);
            v4 = Round(v4, h16);
            v1 = Round(v1, h17);
            v2 = Round(v2, h18);
            v3 = Round(v3, h19);
            v4 = Round(v4, h20);
            v1 = Round(v1, h21);
            v2 = Round(v2, h22);
            v3 = Round(v3, h23);
            v4 = Round(v4, h24);
            hash = MixState(v1, v2, v3, v4);
            hash += 200U;
            hash = QueueRound(hash, h25);
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 26 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6, ulong h7, ulong h8, ulong h9, ulong h10, ulong h11, ulong h12, ulong h13, ulong h14, ulong h15, ulong h16, ulong h17, ulong h18, ulong h19, ulong h20, ulong h21, ulong h22, ulong h23, ulong h24, ulong h25, ulong h26)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            v1 = Round(v1, h5);
            v2 = Round(v2, h6);
            v3 = Round(v3, h7);
            v4 = Round(v4, h8);
            v1 = Round(v1, h9);
            v2 = Round(v2, h10);
            v3 = Round(v3, h11);
            v4 = Round(v4, h12);
            v1 = Round(v1, h13);
            v2 = Round(v2, h14);
            v3 = Round(v3, h15);
            v4 = Round(v4, h16);
            v1 = Round(v1, h17);
            v2 = Round(v2, h18);
            v3 = Round(v3, h19);
            v4 = Round(v4, h20);
            v1 = Round(v1, h21);
            v2 = Round(v2, h22);
            v3 = Round(v3, h23);
            v4 = Round(v4, h24);
            hash = MixState(v1, v2, v3, v4);
            hash += 208U;
            hash = QueueRound(hash, h25);
            hash = QueueRound(hash, h26);
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 27 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6, ulong h7, ulong h8, ulong h9, ulong h10, ulong h11, ulong h12, ulong h13, ulong h14, ulong h15, ulong h16, ulong h17, ulong h18, ulong h19, ulong h20, ulong h21, ulong h22, ulong h23, ulong h24, ulong h25, ulong h26, ulong h27)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            v1 = Round(v1, h5);
            v2 = Round(v2, h6);
            v3 = Round(v3, h7);
            v4 = Round(v4, h8);
            v1 = Round(v1, h9);
            v2 = Round(v2, h10);
            v3 = Round(v3, h11);
            v4 = Round(v4, h12);
            v1 = Round(v1, h13);
            v2 = Round(v2, h14);
            v3 = Round(v3, h15);
            v4 = Round(v4, h16);
            v1 = Round(v1, h17);
            v2 = Round(v2, h18);
            v3 = Round(v3, h19);
            v4 = Round(v4, h20);
            v1 = Round(v1, h21);
            v2 = Round(v2, h22);
            v3 = Round(v3, h23);
            v4 = Round(v4, h24);
            hash = MixState(v1, v2, v3, v4);
            hash += 216U;
            hash = QueueRound(hash, h25);
            hash = QueueRound(hash, h26);
            hash = QueueRound(hash, h27);
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 28 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6, ulong h7, ulong h8, ulong h9, ulong h10, ulong h11, ulong h12, ulong h13, ulong h14, ulong h15, ulong h16, ulong h17, ulong h18, ulong h19, ulong h20, ulong h21, ulong h22, ulong h23, ulong h24, ulong h25, ulong h26, ulong h27, ulong h28)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            v1 = Round(v1, h5);
            v2 = Round(v2, h6);
            v3 = Round(v3, h7);
            v4 = Round(v4, h8);
            v1 = Round(v1, h9);
            v2 = Round(v2, h10);
            v3 = Round(v3, h11);
            v4 = Round(v4, h12);
            v1 = Round(v1, h13);
            v2 = Round(v2, h14);
            v3 = Round(v3, h15);
            v4 = Round(v4, h16);
            v1 = Round(v1, h17);
            v2 = Round(v2, h18);
            v3 = Round(v3, h19);
            v4 = Round(v4, h20);
            v1 = Round(v1, h21);
            v2 = Round(v2, h22);
            v3 = Round(v3, h23);
            v4 = Round(v4, h24);
            v1 = Round(v1, h25);
            v2 = Round(v2, h26);
            v3 = Round(v3, h27);
            v4 = Round(v4, h28);
            hash = MixState(v1, v2, v3, v4);
            hash += 224U;
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 29 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6, ulong h7, ulong h8, ulong h9, ulong h10, ulong h11, ulong h12, ulong h13, ulong h14, ulong h15, ulong h16, ulong h17, ulong h18, ulong h19, ulong h20, ulong h21, ulong h22, ulong h23, ulong h24, ulong h25, ulong h26, ulong h27, ulong h28, ulong h29)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            v1 = Round(v1, h5);
            v2 = Round(v2, h6);
            v3 = Round(v3, h7);
            v4 = Round(v4, h8);
            v1 = Round(v1, h9);
            v2 = Round(v2, h10);
            v3 = Round(v3, h11);
            v4 = Round(v4, h12);
            v1 = Round(v1, h13);
            v2 = Round(v2, h14);
            v3 = Round(v3, h15);
            v4 = Round(v4, h16);
            v1 = Round(v1, h17);
            v2 = Round(v2, h18);
            v3 = Round(v3, h19);
            v4 = Round(v4, h20);
            v1 = Round(v1, h21);
            v2 = Round(v2, h22);
            v3 = Round(v3, h23);
            v4 = Round(v4, h24);
            v1 = Round(v1, h25);
            v2 = Round(v2, h26);
            v3 = Round(v3, h27);
            v4 = Round(v4, h28);
            hash = MixState(v1, v2, v3, v4);
            hash += 232U;
            hash = QueueRound(hash, h29);
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 30 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6, ulong h7, ulong h8, ulong h9, ulong h10, ulong h11, ulong h12, ulong h13, ulong h14, ulong h15, ulong h16, ulong h17, ulong h18, ulong h19, ulong h20, ulong h21, ulong h22, ulong h23, ulong h24, ulong h25, ulong h26, ulong h27, ulong h28, ulong h29, ulong h30)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            v1 = Round(v1, h5);
            v2 = Round(v2, h6);
            v3 = Round(v3, h7);
            v4 = Round(v4, h8);
            v1 = Round(v1, h9);
            v2 = Round(v2, h10);
            v3 = Round(v3, h11);
            v4 = Round(v4, h12);
            v1 = Round(v1, h13);
            v2 = Round(v2, h14);
            v3 = Round(v3, h15);
            v4 = Round(v4, h16);
            v1 = Round(v1, h17);
            v2 = Round(v2, h18);
            v3 = Round(v3, h19);
            v4 = Round(v4, h20);
            v1 = Round(v1, h21);
            v2 = Round(v2, h22);
            v3 = Round(v3, h23);
            v4 = Round(v4, h24);
            v1 = Round(v1, h25);
            v2 = Round(v2, h26);
            v3 = Round(v3, h27);
            v4 = Round(v4, h28);
            hash = MixState(v1, v2, v3, v4);
            hash += 240U;
            hash = QueueRound(hash, h29);
            hash = QueueRound(hash, h30);
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 31 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6, ulong h7, ulong h8, ulong h9, ulong h10, ulong h11, ulong h12, ulong h13, ulong h14, ulong h15, ulong h16, ulong h17, ulong h18, ulong h19, ulong h20, ulong h21, ulong h22, ulong h23, ulong h24, ulong h25, ulong h26, ulong h27, ulong h28, ulong h29, ulong h30, ulong h31)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            v1 = Round(v1, h5);
            v2 = Round(v2, h6);
            v3 = Round(v3, h7);
            v4 = Round(v4, h8);
            v1 = Round(v1, h9);
            v2 = Round(v2, h10);
            v3 = Round(v3, h11);
            v4 = Round(v4, h12);
            v1 = Round(v1, h13);
            v2 = Round(v2, h14);
            v3 = Round(v3, h15);
            v4 = Round(v4, h16);
            v1 = Round(v1, h17);
            v2 = Round(v2, h18);
            v3 = Round(v3, h19);
            v4 = Round(v4, h20);
            v1 = Round(v1, h21);
            v2 = Round(v2, h22);
            v3 = Round(v3, h23);
            v4 = Round(v4, h24);
            v1 = Round(v1, h25);
            v2 = Round(v2, h26);
            v3 = Round(v3, h27);
            v4 = Round(v4, h28);
            hash = MixState(v1, v2, v3, v4);
            hash += 248U;
            hash = QueueRound(hash, h29);
            hash = QueueRound(hash, h30);
            hash = QueueRound(hash, h31);
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }

    /// <summary>Combines 32 already computed hash codes with the seeded xxHash64 stream.</summary>
    public static ulong Combine(ulong h1, ulong h2, ulong h3, ulong h4, ulong h5, ulong h6, ulong h7, ulong h8, ulong h9, ulong h10, ulong h11, ulong h12, ulong h13, ulong h14, ulong h15, ulong h16, ulong h17, ulong h18, ulong h19, ulong h20, ulong h21, ulong h22, ulong h23, ulong h24, ulong h25, ulong h26, ulong h27, ulong h28, ulong h29, ulong h30, ulong h31, ulong h32)
    {
        unchecked
        {
            ulong seed = s_seed;
            ulong hash;
            ulong v1 = seed + Prime1 + Prime2;
            ulong v2 = seed + Prime2;
            ulong v3 = seed;
            ulong v4 = seed - Prime1;
            v1 = Round(v1, h1);
            v2 = Round(v2, h2);
            v3 = Round(v3, h3);
            v4 = Round(v4, h4);
            v1 = Round(v1, h5);
            v2 = Round(v2, h6);
            v3 = Round(v3, h7);
            v4 = Round(v4, h8);
            v1 = Round(v1, h9);
            v2 = Round(v2, h10);
            v3 = Round(v3, h11);
            v4 = Round(v4, h12);
            v1 = Round(v1, h13);
            v2 = Round(v2, h14);
            v3 = Round(v3, h15);
            v4 = Round(v4, h16);
            v1 = Round(v1, h17);
            v2 = Round(v2, h18);
            v3 = Round(v3, h19);
            v4 = Round(v4, h20);
            v1 = Round(v1, h21);
            v2 = Round(v2, h22);
            v3 = Round(v3, h23);
            v4 = Round(v4, h24);
            v1 = Round(v1, h25);
            v2 = Round(v2, h26);
            v3 = Round(v3, h27);
            v4 = Round(v4, h28);
            v1 = Round(v1, h29);
            v2 = Round(v2, h30);
            v3 = Round(v3, h31);
            v4 = Round(v4, h32);
            hash = MixState(v1, v2, v3, v4);
            hash += 256U;
            hash = MixFinal(hash);
            return (ulong)hash;
        }
    }
}
