// <auto-generated/>
// Generated by eng/Generate-HashCodeCombine.ps1 -Width 32 -MaxArity 32. Do not edit.
using System.Runtime.CompilerServices;

namespace DeepEquals.SourceGeneration.Framework;

public static partial class DeepEqualsHashCode
{
    /// <summary>Combines 1 already computed hash codes with the seeded xxHash32 stream.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int Combine(int h1)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            hash = seed + Prime5;
            hash += 4U;
            hash = QueueRound(hash, (uint)h1);
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 2 already computed hash codes with the seeded xxHash32 stream.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int Combine(int h1, int h2)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            hash = seed + Prime5;
            hash += 8U;
            hash = QueueRound(hash, (uint)h1);
            hash = QueueRound(hash, (uint)h2);
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 3 already computed hash codes with the seeded xxHash32 stream.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int Combine(int h1, int h2, int h3)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            hash = seed + Prime5;
            hash += 12U;
            hash = QueueRound(hash, (uint)h1);
            hash = QueueRound(hash, (uint)h2);
            hash = QueueRound(hash, (uint)h3);
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 4 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            hash = MixState(v1, v2, v3, v4);
            hash += 16U;
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 5 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            hash = MixState(v1, v2, v3, v4);
            hash += 20U;
            hash = QueueRound(hash, (uint)h5);
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 6 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            hash = MixState(v1, v2, v3, v4);
            hash += 24U;
            hash = QueueRound(hash, (uint)h5);
            hash = QueueRound(hash, (uint)h6);
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 7 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6, int h7)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            hash = MixState(v1, v2, v3, v4);
            hash += 28U;
            hash = QueueRound(hash, (uint)h5);
            hash = QueueRound(hash, (uint)h6);
            hash = QueueRound(hash, (uint)h7);
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 8 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6, int h7, int h8)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            v1 = Round(v1, (uint)h5);
            v2 = Round(v2, (uint)h6);
            v3 = Round(v3, (uint)h7);
            v4 = Round(v4, (uint)h8);
            hash = MixState(v1, v2, v3, v4);
            hash += 32U;
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 9 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6, int h7, int h8, int h9)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            v1 = Round(v1, (uint)h5);
            v2 = Round(v2, (uint)h6);
            v3 = Round(v3, (uint)h7);
            v4 = Round(v4, (uint)h8);
            hash = MixState(v1, v2, v3, v4);
            hash += 36U;
            hash = QueueRound(hash, (uint)h9);
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 10 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6, int h7, int h8, int h9, int h10)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            v1 = Round(v1, (uint)h5);
            v2 = Round(v2, (uint)h6);
            v3 = Round(v3, (uint)h7);
            v4 = Round(v4, (uint)h8);
            hash = MixState(v1, v2, v3, v4);
            hash += 40U;
            hash = QueueRound(hash, (uint)h9);
            hash = QueueRound(hash, (uint)h10);
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 11 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6, int h7, int h8, int h9, int h10, int h11)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            v1 = Round(v1, (uint)h5);
            v2 = Round(v2, (uint)h6);
            v3 = Round(v3, (uint)h7);
            v4 = Round(v4, (uint)h8);
            hash = MixState(v1, v2, v3, v4);
            hash += 44U;
            hash = QueueRound(hash, (uint)h9);
            hash = QueueRound(hash, (uint)h10);
            hash = QueueRound(hash, (uint)h11);
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 12 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6, int h7, int h8, int h9, int h10, int h11, int h12)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            v1 = Round(v1, (uint)h5);
            v2 = Round(v2, (uint)h6);
            v3 = Round(v3, (uint)h7);
            v4 = Round(v4, (uint)h8);
            v1 = Round(v1, (uint)h9);
            v2 = Round(v2, (uint)h10);
            v3 = Round(v3, (uint)h11);
            v4 = Round(v4, (uint)h12);
            hash = MixState(v1, v2, v3, v4);
            hash += 48U;
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 13 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6, int h7, int h8, int h9, int h10, int h11, int h12, int h13)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            v1 = Round(v1, (uint)h5);
            v2 = Round(v2, (uint)h6);
            v3 = Round(v3, (uint)h7);
            v4 = Round(v4, (uint)h8);
            v1 = Round(v1, (uint)h9);
            v2 = Round(v2, (uint)h10);
            v3 = Round(v3, (uint)h11);
            v4 = Round(v4, (uint)h12);
            hash = MixState(v1, v2, v3, v4);
            hash += 52U;
            hash = QueueRound(hash, (uint)h13);
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 14 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6, int h7, int h8, int h9, int h10, int h11, int h12, int h13, int h14)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            v1 = Round(v1, (uint)h5);
            v2 = Round(v2, (uint)h6);
            v3 = Round(v3, (uint)h7);
            v4 = Round(v4, (uint)h8);
            v1 = Round(v1, (uint)h9);
            v2 = Round(v2, (uint)h10);
            v3 = Round(v3, (uint)h11);
            v4 = Round(v4, (uint)h12);
            hash = MixState(v1, v2, v3, v4);
            hash += 56U;
            hash = QueueRound(hash, (uint)h13);
            hash = QueueRound(hash, (uint)h14);
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 15 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6, int h7, int h8, int h9, int h10, int h11, int h12, int h13, int h14, int h15)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            v1 = Round(v1, (uint)h5);
            v2 = Round(v2, (uint)h6);
            v3 = Round(v3, (uint)h7);
            v4 = Round(v4, (uint)h8);
            v1 = Round(v1, (uint)h9);
            v2 = Round(v2, (uint)h10);
            v3 = Round(v3, (uint)h11);
            v4 = Round(v4, (uint)h12);
            hash = MixState(v1, v2, v3, v4);
            hash += 60U;
            hash = QueueRound(hash, (uint)h13);
            hash = QueueRound(hash, (uint)h14);
            hash = QueueRound(hash, (uint)h15);
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 16 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6, int h7, int h8, int h9, int h10, int h11, int h12, int h13, int h14, int h15, int h16)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            v1 = Round(v1, (uint)h5);
            v2 = Round(v2, (uint)h6);
            v3 = Round(v3, (uint)h7);
            v4 = Round(v4, (uint)h8);
            v1 = Round(v1, (uint)h9);
            v2 = Round(v2, (uint)h10);
            v3 = Round(v3, (uint)h11);
            v4 = Round(v4, (uint)h12);
            v1 = Round(v1, (uint)h13);
            v2 = Round(v2, (uint)h14);
            v3 = Round(v3, (uint)h15);
            v4 = Round(v4, (uint)h16);
            hash = MixState(v1, v2, v3, v4);
            hash += 64U;
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 17 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6, int h7, int h8, int h9, int h10, int h11, int h12, int h13, int h14, int h15, int h16, int h17)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            v1 = Round(v1, (uint)h5);
            v2 = Round(v2, (uint)h6);
            v3 = Round(v3, (uint)h7);
            v4 = Round(v4, (uint)h8);
            v1 = Round(v1, (uint)h9);
            v2 = Round(v2, (uint)h10);
            v3 = Round(v3, (uint)h11);
            v4 = Round(v4, (uint)h12);
            v1 = Round(v1, (uint)h13);
            v2 = Round(v2, (uint)h14);
            v3 = Round(v3, (uint)h15);
            v4 = Round(v4, (uint)h16);
            hash = MixState(v1, v2, v3, v4);
            hash += 68U;
            hash = QueueRound(hash, (uint)h17);
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 18 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6, int h7, int h8, int h9, int h10, int h11, int h12, int h13, int h14, int h15, int h16, int h17, int h18)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            v1 = Round(v1, (uint)h5);
            v2 = Round(v2, (uint)h6);
            v3 = Round(v3, (uint)h7);
            v4 = Round(v4, (uint)h8);
            v1 = Round(v1, (uint)h9);
            v2 = Round(v2, (uint)h10);
            v3 = Round(v3, (uint)h11);
            v4 = Round(v4, (uint)h12);
            v1 = Round(v1, (uint)h13);
            v2 = Round(v2, (uint)h14);
            v3 = Round(v3, (uint)h15);
            v4 = Round(v4, (uint)h16);
            hash = MixState(v1, v2, v3, v4);
            hash += 72U;
            hash = QueueRound(hash, (uint)h17);
            hash = QueueRound(hash, (uint)h18);
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 19 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6, int h7, int h8, int h9, int h10, int h11, int h12, int h13, int h14, int h15, int h16, int h17, int h18, int h19)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            v1 = Round(v1, (uint)h5);
            v2 = Round(v2, (uint)h6);
            v3 = Round(v3, (uint)h7);
            v4 = Round(v4, (uint)h8);
            v1 = Round(v1, (uint)h9);
            v2 = Round(v2, (uint)h10);
            v3 = Round(v3, (uint)h11);
            v4 = Round(v4, (uint)h12);
            v1 = Round(v1, (uint)h13);
            v2 = Round(v2, (uint)h14);
            v3 = Round(v3, (uint)h15);
            v4 = Round(v4, (uint)h16);
            hash = MixState(v1, v2, v3, v4);
            hash += 76U;
            hash = QueueRound(hash, (uint)h17);
            hash = QueueRound(hash, (uint)h18);
            hash = QueueRound(hash, (uint)h19);
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 20 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6, int h7, int h8, int h9, int h10, int h11, int h12, int h13, int h14, int h15, int h16, int h17, int h18, int h19, int h20)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            v1 = Round(v1, (uint)h5);
            v2 = Round(v2, (uint)h6);
            v3 = Round(v3, (uint)h7);
            v4 = Round(v4, (uint)h8);
            v1 = Round(v1, (uint)h9);
            v2 = Round(v2, (uint)h10);
            v3 = Round(v3, (uint)h11);
            v4 = Round(v4, (uint)h12);
            v1 = Round(v1, (uint)h13);
            v2 = Round(v2, (uint)h14);
            v3 = Round(v3, (uint)h15);
            v4 = Round(v4, (uint)h16);
            v1 = Round(v1, (uint)h17);
            v2 = Round(v2, (uint)h18);
            v3 = Round(v3, (uint)h19);
            v4 = Round(v4, (uint)h20);
            hash = MixState(v1, v2, v3, v4);
            hash += 80U;
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 21 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6, int h7, int h8, int h9, int h10, int h11, int h12, int h13, int h14, int h15, int h16, int h17, int h18, int h19, int h20, int h21)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            v1 = Round(v1, (uint)h5);
            v2 = Round(v2, (uint)h6);
            v3 = Round(v3, (uint)h7);
            v4 = Round(v4, (uint)h8);
            v1 = Round(v1, (uint)h9);
            v2 = Round(v2, (uint)h10);
            v3 = Round(v3, (uint)h11);
            v4 = Round(v4, (uint)h12);
            v1 = Round(v1, (uint)h13);
            v2 = Round(v2, (uint)h14);
            v3 = Round(v3, (uint)h15);
            v4 = Round(v4, (uint)h16);
            v1 = Round(v1, (uint)h17);
            v2 = Round(v2, (uint)h18);
            v3 = Round(v3, (uint)h19);
            v4 = Round(v4, (uint)h20);
            hash = MixState(v1, v2, v3, v4);
            hash += 84U;
            hash = QueueRound(hash, (uint)h21);
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 22 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6, int h7, int h8, int h9, int h10, int h11, int h12, int h13, int h14, int h15, int h16, int h17, int h18, int h19, int h20, int h21, int h22)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            v1 = Round(v1, (uint)h5);
            v2 = Round(v2, (uint)h6);
            v3 = Round(v3, (uint)h7);
            v4 = Round(v4, (uint)h8);
            v1 = Round(v1, (uint)h9);
            v2 = Round(v2, (uint)h10);
            v3 = Round(v3, (uint)h11);
            v4 = Round(v4, (uint)h12);
            v1 = Round(v1, (uint)h13);
            v2 = Round(v2, (uint)h14);
            v3 = Round(v3, (uint)h15);
            v4 = Round(v4, (uint)h16);
            v1 = Round(v1, (uint)h17);
            v2 = Round(v2, (uint)h18);
            v3 = Round(v3, (uint)h19);
            v4 = Round(v4, (uint)h20);
            hash = MixState(v1, v2, v3, v4);
            hash += 88U;
            hash = QueueRound(hash, (uint)h21);
            hash = QueueRound(hash, (uint)h22);
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 23 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6, int h7, int h8, int h9, int h10, int h11, int h12, int h13, int h14, int h15, int h16, int h17, int h18, int h19, int h20, int h21, int h22, int h23)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            v1 = Round(v1, (uint)h5);
            v2 = Round(v2, (uint)h6);
            v3 = Round(v3, (uint)h7);
            v4 = Round(v4, (uint)h8);
            v1 = Round(v1, (uint)h9);
            v2 = Round(v2, (uint)h10);
            v3 = Round(v3, (uint)h11);
            v4 = Round(v4, (uint)h12);
            v1 = Round(v1, (uint)h13);
            v2 = Round(v2, (uint)h14);
            v3 = Round(v3, (uint)h15);
            v4 = Round(v4, (uint)h16);
            v1 = Round(v1, (uint)h17);
            v2 = Round(v2, (uint)h18);
            v3 = Round(v3, (uint)h19);
            v4 = Round(v4, (uint)h20);
            hash = MixState(v1, v2, v3, v4);
            hash += 92U;
            hash = QueueRound(hash, (uint)h21);
            hash = QueueRound(hash, (uint)h22);
            hash = QueueRound(hash, (uint)h23);
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 24 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6, int h7, int h8, int h9, int h10, int h11, int h12, int h13, int h14, int h15, int h16, int h17, int h18, int h19, int h20, int h21, int h22, int h23, int h24)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            v1 = Round(v1, (uint)h5);
            v2 = Round(v2, (uint)h6);
            v3 = Round(v3, (uint)h7);
            v4 = Round(v4, (uint)h8);
            v1 = Round(v1, (uint)h9);
            v2 = Round(v2, (uint)h10);
            v3 = Round(v3, (uint)h11);
            v4 = Round(v4, (uint)h12);
            v1 = Round(v1, (uint)h13);
            v2 = Round(v2, (uint)h14);
            v3 = Round(v3, (uint)h15);
            v4 = Round(v4, (uint)h16);
            v1 = Round(v1, (uint)h17);
            v2 = Round(v2, (uint)h18);
            v3 = Round(v3, (uint)h19);
            v4 = Round(v4, (uint)h20);
            v1 = Round(v1, (uint)h21);
            v2 = Round(v2, (uint)h22);
            v3 = Round(v3, (uint)h23);
            v4 = Round(v4, (uint)h24);
            hash = MixState(v1, v2, v3, v4);
            hash += 96U;
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 25 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6, int h7, int h8, int h9, int h10, int h11, int h12, int h13, int h14, int h15, int h16, int h17, int h18, int h19, int h20, int h21, int h22, int h23, int h24, int h25)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            v1 = Round(v1, (uint)h5);
            v2 = Round(v2, (uint)h6);
            v3 = Round(v3, (uint)h7);
            v4 = Round(v4, (uint)h8);
            v1 = Round(v1, (uint)h9);
            v2 = Round(v2, (uint)h10);
            v3 = Round(v3, (uint)h11);
            v4 = Round(v4, (uint)h12);
            v1 = Round(v1, (uint)h13);
            v2 = Round(v2, (uint)h14);
            v3 = Round(v3, (uint)h15);
            v4 = Round(v4, (uint)h16);
            v1 = Round(v1, (uint)h17);
            v2 = Round(v2, (uint)h18);
            v3 = Round(v3, (uint)h19);
            v4 = Round(v4, (uint)h20);
            v1 = Round(v1, (uint)h21);
            v2 = Round(v2, (uint)h22);
            v3 = Round(v3, (uint)h23);
            v4 = Round(v4, (uint)h24);
            hash = MixState(v1, v2, v3, v4);
            hash += 100U;
            hash = QueueRound(hash, (uint)h25);
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 26 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6, int h7, int h8, int h9, int h10, int h11, int h12, int h13, int h14, int h15, int h16, int h17, int h18, int h19, int h20, int h21, int h22, int h23, int h24, int h25, int h26)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            v1 = Round(v1, (uint)h5);
            v2 = Round(v2, (uint)h6);
            v3 = Round(v3, (uint)h7);
            v4 = Round(v4, (uint)h8);
            v1 = Round(v1, (uint)h9);
            v2 = Round(v2, (uint)h10);
            v3 = Round(v3, (uint)h11);
            v4 = Round(v4, (uint)h12);
            v1 = Round(v1, (uint)h13);
            v2 = Round(v2, (uint)h14);
            v3 = Round(v3, (uint)h15);
            v4 = Round(v4, (uint)h16);
            v1 = Round(v1, (uint)h17);
            v2 = Round(v2, (uint)h18);
            v3 = Round(v3, (uint)h19);
            v4 = Round(v4, (uint)h20);
            v1 = Round(v1, (uint)h21);
            v2 = Round(v2, (uint)h22);
            v3 = Round(v3, (uint)h23);
            v4 = Round(v4, (uint)h24);
            hash = MixState(v1, v2, v3, v4);
            hash += 104U;
            hash = QueueRound(hash, (uint)h25);
            hash = QueueRound(hash, (uint)h26);
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 27 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6, int h7, int h8, int h9, int h10, int h11, int h12, int h13, int h14, int h15, int h16, int h17, int h18, int h19, int h20, int h21, int h22, int h23, int h24, int h25, int h26, int h27)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            v1 = Round(v1, (uint)h5);
            v2 = Round(v2, (uint)h6);
            v3 = Round(v3, (uint)h7);
            v4 = Round(v4, (uint)h8);
            v1 = Round(v1, (uint)h9);
            v2 = Round(v2, (uint)h10);
            v3 = Round(v3, (uint)h11);
            v4 = Round(v4, (uint)h12);
            v1 = Round(v1, (uint)h13);
            v2 = Round(v2, (uint)h14);
            v3 = Round(v3, (uint)h15);
            v4 = Round(v4, (uint)h16);
            v1 = Round(v1, (uint)h17);
            v2 = Round(v2, (uint)h18);
            v3 = Round(v3, (uint)h19);
            v4 = Round(v4, (uint)h20);
            v1 = Round(v1, (uint)h21);
            v2 = Round(v2, (uint)h22);
            v3 = Round(v3, (uint)h23);
            v4 = Round(v4, (uint)h24);
            hash = MixState(v1, v2, v3, v4);
            hash += 108U;
            hash = QueueRound(hash, (uint)h25);
            hash = QueueRound(hash, (uint)h26);
            hash = QueueRound(hash, (uint)h27);
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 28 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6, int h7, int h8, int h9, int h10, int h11, int h12, int h13, int h14, int h15, int h16, int h17, int h18, int h19, int h20, int h21, int h22, int h23, int h24, int h25, int h26, int h27, int h28)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            v1 = Round(v1, (uint)h5);
            v2 = Round(v2, (uint)h6);
            v3 = Round(v3, (uint)h7);
            v4 = Round(v4, (uint)h8);
            v1 = Round(v1, (uint)h9);
            v2 = Round(v2, (uint)h10);
            v3 = Round(v3, (uint)h11);
            v4 = Round(v4, (uint)h12);
            v1 = Round(v1, (uint)h13);
            v2 = Round(v2, (uint)h14);
            v3 = Round(v3, (uint)h15);
            v4 = Round(v4, (uint)h16);
            v1 = Round(v1, (uint)h17);
            v2 = Round(v2, (uint)h18);
            v3 = Round(v3, (uint)h19);
            v4 = Round(v4, (uint)h20);
            v1 = Round(v1, (uint)h21);
            v2 = Round(v2, (uint)h22);
            v3 = Round(v3, (uint)h23);
            v4 = Round(v4, (uint)h24);
            v1 = Round(v1, (uint)h25);
            v2 = Round(v2, (uint)h26);
            v3 = Round(v3, (uint)h27);
            v4 = Round(v4, (uint)h28);
            hash = MixState(v1, v2, v3, v4);
            hash += 112U;
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 29 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6, int h7, int h8, int h9, int h10, int h11, int h12, int h13, int h14, int h15, int h16, int h17, int h18, int h19, int h20, int h21, int h22, int h23, int h24, int h25, int h26, int h27, int h28, int h29)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            v1 = Round(v1, (uint)h5);
            v2 = Round(v2, (uint)h6);
            v3 = Round(v3, (uint)h7);
            v4 = Round(v4, (uint)h8);
            v1 = Round(v1, (uint)h9);
            v2 = Round(v2, (uint)h10);
            v3 = Round(v3, (uint)h11);
            v4 = Round(v4, (uint)h12);
            v1 = Round(v1, (uint)h13);
            v2 = Round(v2, (uint)h14);
            v3 = Round(v3, (uint)h15);
            v4 = Round(v4, (uint)h16);
            v1 = Round(v1, (uint)h17);
            v2 = Round(v2, (uint)h18);
            v3 = Round(v3, (uint)h19);
            v4 = Round(v4, (uint)h20);
            v1 = Round(v1, (uint)h21);
            v2 = Round(v2, (uint)h22);
            v3 = Round(v3, (uint)h23);
            v4 = Round(v4, (uint)h24);
            v1 = Round(v1, (uint)h25);
            v2 = Round(v2, (uint)h26);
            v3 = Round(v3, (uint)h27);
            v4 = Round(v4, (uint)h28);
            hash = MixState(v1, v2, v3, v4);
            hash += 116U;
            hash = QueueRound(hash, (uint)h29);
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 30 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6, int h7, int h8, int h9, int h10, int h11, int h12, int h13, int h14, int h15, int h16, int h17, int h18, int h19, int h20, int h21, int h22, int h23, int h24, int h25, int h26, int h27, int h28, int h29, int h30)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            v1 = Round(v1, (uint)h5);
            v2 = Round(v2, (uint)h6);
            v3 = Round(v3, (uint)h7);
            v4 = Round(v4, (uint)h8);
            v1 = Round(v1, (uint)h9);
            v2 = Round(v2, (uint)h10);
            v3 = Round(v3, (uint)h11);
            v4 = Round(v4, (uint)h12);
            v1 = Round(v1, (uint)h13);
            v2 = Round(v2, (uint)h14);
            v3 = Round(v3, (uint)h15);
            v4 = Round(v4, (uint)h16);
            v1 = Round(v1, (uint)h17);
            v2 = Round(v2, (uint)h18);
            v3 = Round(v3, (uint)h19);
            v4 = Round(v4, (uint)h20);
            v1 = Round(v1, (uint)h21);
            v2 = Round(v2, (uint)h22);
            v3 = Round(v3, (uint)h23);
            v4 = Round(v4, (uint)h24);
            v1 = Round(v1, (uint)h25);
            v2 = Round(v2, (uint)h26);
            v3 = Round(v3, (uint)h27);
            v4 = Round(v4, (uint)h28);
            hash = MixState(v1, v2, v3, v4);
            hash += 120U;
            hash = QueueRound(hash, (uint)h29);
            hash = QueueRound(hash, (uint)h30);
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 31 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6, int h7, int h8, int h9, int h10, int h11, int h12, int h13, int h14, int h15, int h16, int h17, int h18, int h19, int h20, int h21, int h22, int h23, int h24, int h25, int h26, int h27, int h28, int h29, int h30, int h31)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            v1 = Round(v1, (uint)h5);
            v2 = Round(v2, (uint)h6);
            v3 = Round(v3, (uint)h7);
            v4 = Round(v4, (uint)h8);
            v1 = Round(v1, (uint)h9);
            v2 = Round(v2, (uint)h10);
            v3 = Round(v3, (uint)h11);
            v4 = Round(v4, (uint)h12);
            v1 = Round(v1, (uint)h13);
            v2 = Round(v2, (uint)h14);
            v3 = Round(v3, (uint)h15);
            v4 = Round(v4, (uint)h16);
            v1 = Round(v1, (uint)h17);
            v2 = Round(v2, (uint)h18);
            v3 = Round(v3, (uint)h19);
            v4 = Round(v4, (uint)h20);
            v1 = Round(v1, (uint)h21);
            v2 = Round(v2, (uint)h22);
            v3 = Round(v3, (uint)h23);
            v4 = Round(v4, (uint)h24);
            v1 = Round(v1, (uint)h25);
            v2 = Round(v2, (uint)h26);
            v3 = Round(v3, (uint)h27);
            v4 = Round(v4, (uint)h28);
            hash = MixState(v1, v2, v3, v4);
            hash += 124U;
            hash = QueueRound(hash, (uint)h29);
            hash = QueueRound(hash, (uint)h30);
            hash = QueueRound(hash, (uint)h31);
            hash = MixFinal(hash);
            return (int)hash;
        }
    }

    /// <summary>Combines 32 already computed hash codes with the seeded xxHash32 stream.</summary>
    public static int Combine(int h1, int h2, int h3, int h4, int h5, int h6, int h7, int h8, int h9, int h10, int h11, int h12, int h13, int h14, int h15, int h16, int h17, int h18, int h19, int h20, int h21, int h22, int h23, int h24, int h25, int h26, int h27, int h28, int h29, int h30, int h31, int h32)
    {
        unchecked
        {
            uint seed = s_seed;
            uint hash;
            uint v1 = seed + Prime1 + Prime2;
            uint v2 = seed + Prime2;
            uint v3 = seed;
            uint v4 = seed - Prime1;
            v1 = Round(v1, (uint)h1);
            v2 = Round(v2, (uint)h2);
            v3 = Round(v3, (uint)h3);
            v4 = Round(v4, (uint)h4);
            v1 = Round(v1, (uint)h5);
            v2 = Round(v2, (uint)h6);
            v3 = Round(v3, (uint)h7);
            v4 = Round(v4, (uint)h8);
            v1 = Round(v1, (uint)h9);
            v2 = Round(v2, (uint)h10);
            v3 = Round(v3, (uint)h11);
            v4 = Round(v4, (uint)h12);
            v1 = Round(v1, (uint)h13);
            v2 = Round(v2, (uint)h14);
            v3 = Round(v3, (uint)h15);
            v4 = Round(v4, (uint)h16);
            v1 = Round(v1, (uint)h17);
            v2 = Round(v2, (uint)h18);
            v3 = Round(v3, (uint)h19);
            v4 = Round(v4, (uint)h20);
            v1 = Round(v1, (uint)h21);
            v2 = Round(v2, (uint)h22);
            v3 = Round(v3, (uint)h23);
            v4 = Round(v4, (uint)h24);
            v1 = Round(v1, (uint)h25);
            v2 = Round(v2, (uint)h26);
            v3 = Round(v3, (uint)h27);
            v4 = Round(v4, (uint)h28);
            v1 = Round(v1, (uint)h29);
            v2 = Round(v2, (uint)h30);
            v3 = Round(v3, (uint)h31);
            v4 = Round(v4, (uint)h32);
            hash = MixState(v1, v2, v3, v4);
            hash += 128U;
            hash = MixFinal(hash);
            return (int)hash;
        }
    }
}
