// Copyright 2026 Jeremy Morren <jeremy.morren@outlook.com>. All rights reserved.
// Source code is available at https://github.com/jeremy-morren/DeepEquals.SourceGenerator
// Use of this source code is governed by the MIT License as found in the LICENSE.txt file

using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading;
using DeepEquals.SourceGenerator.Model;
using Microsoft.CodeAnalysis.CSharp;
using static DeepEquals.SourceGenerator.Emit.CodeWriter;

// ReSharper disable IdentifierTypo
// ReSharper disable InvertIf
// ReSharper disable SwitchStatementMissingSomeEnumCasesNoDefault

namespace DeepEquals.SourceGenerator.Emit;

/// <summary>
/// A straight walk over the model.
/// No decisions are made here that the model does not already record.
/// </summary>
internal sealed class Emitter
{
    private const int MaxCombineArity = 32;

    private readonly ContextModel _model;
    private readonly CancellationToken _cancellationToken;
    private readonly CodeWriter _w;
    private readonly TypeModel[] _types;
    private readonly HashSet<int> _spanCores = [];
    private readonly List<(TypeModel Type, List<DispatchCase> Exact)> _pendingDispatchHolders = [];

    private Emitter(ContextModel model, CancellationToken cancellationToken)
    {
        _model = model;
        _cancellationToken = cancellationToken;
        // Estimate capacity: 2048 characters per type + 4096 characters for the usings and namespace
        _w = new CodeWriter(Math.Min(model.Types.Count * 2048 + 4096, 4 * 1024 * 1024));
        _types = model.Types.ToArray();
    }

    public static string Emit(ContextModel model, CancellationToken cancellationToken)
    {
        var emitter = new Emitter(model, cancellationToken);
        emitter.EmitFile();
        return emitter._w.ToString();
    }

    private TypeModel Type(int id) => _types[id];

    private bool Annotations => _model.Capabilities.NullableAnnotations;

    // ----- file ---------------------------------------------------------------------------------------------------------

    /// <summary>The package version of the generator, read once from the assembly's informational version without its build metadata.</summary>
    private static readonly string GeneratorVersion = ReadGeneratorVersion();

    private static string ReadGeneratorVersion()
    {
        var assembly = typeof(Emitter).Assembly;
        var informational = assembly
            .GetCustomAttributes<AssemblyInformationalVersionAttribute>()
            .Select(x => x.InformationalVersion)
            .FirstOrDefault();
        if (!string.IsNullOrEmpty(informational))
        {
            var plus = informational.IndexOf('+');
            return plus < 0 ? informational : informational[..plus];
        }

        return assembly.GetName().Version?.ToString(3) ?? "1.0.0";
    }

    /// <summary>The header template, an embedded resource with <c>{{placeholders}}</c>, read once and split into lines.</summary>
    private static readonly string[] HeaderTemplate = ReadHeaderTemplate();

    private static string[] ReadHeaderTemplate()
    {
        using var stream = typeof(Emitter).Assembly.GetManifestResourceStream("DeepEquals.SourceGenerator.Templates.AutoGeneratedHeader.cs");
        if (stream is null)
            throw new InvalidOperationException("The embedded header template 'Templates/AutoGeneratedHeader.cs' is missing from the generator assembly.");

        using var reader = new System.IO.StreamReader(stream);
        return reader.ReadToEnd().Replace("\r\n", "\n").TrimEnd('\n').Split('\n');
    }

    private const string CommentIndent = "    ";

    /// <summary>
    /// A name for the block comment: no <c>global::</c>, and no <c>*/</c> that would end the comment early.
    /// </summary>
    private static string Display(string globalName) => 
        globalName.Replace("global::", string.Empty).Replace("*/", "* /");

    /// <summary>
    /// One indented line per entry, or a single "none" line,
    /// for a list placeholder inside the header's block comment.
    /// </summary>
    private static string CommentList(IEnumerable<string> entries, string none = "none")
    {
        var lines = entries.ToArray();
        return lines.Length == 0 
            ? CommentIndent + none 
            : string.Join("\n", lines.Select(l => CommentIndent + l));
    }

    /// <summary>Every value the header template can ask for, computed from the model alone so output stays deterministic.</summary>
    private Dictionary<string, string> HeaderValues()
    {
        var contextName = _model.Namespace.Length > 0 ? $"{_model.Namespace}.{_model.Name}" : _model.Name;
        var c = _model.Capabilities;
        var o = _model.Options;

        string KindLabel(TypeModel t) => t.Kind switch
        {
            TypeKind.Leaf => t.LeafRule switch
            {
                LeafRule.Custom => "leaf, custom comparer",
                LeafRule.UserSimple => "leaf, [SimpleType]",
                LeafRule.Enum => "leaf, enum",
                _ => "leaf, built-in",
            },
            TypeKind.Nullable => "nullable wrapper",
            TypeKind.Class => t.IsSealed ? "class, compared by members" : "class, compared by members, dispatches to derived types",
            TypeKind.Struct => "struct, compared by members",
            TypeKind.Dispatch => t.IsObject 
                ? "object, dispatches on runtime type"
                : t.IsInterface ? "interface, dispatches on runtime type" : "abstract class, dispatches on runtime type",
            TypeKind.Array or TypeKind.List or TypeKind.ImmutableArray or TypeKind.ArraySegment or TypeKind.Memory or TypeKind.ListInterface or TypeKind.EnumerableInterface => 
                "ordered collection",
            TypeKind.Set => "set, unordered",
            TypeKind.Dictionary => "dictionary, unordered",
            TypeKind.KeyValuePair or TypeKind.ValueTuple or TypeKind.Tuple => "product, compared item by item",
            _ => t.Kind.ToString().ToLowerInvariant(),
        };

        var wrappers = _types.Where(t => t.EmitWrapper).ToList();
        (string Name, bool Present)[] capabilities =
        [
            ("ReadOnlySpan<T>", c.HasReadOnlySpan),
            ("Memory<T>", c.HasMemory),
            ("CollectionsMarshal.AsSpan", c.HasCollectionsMarshal),
            ("MemoryMarshal", c.HasMemoryMarshal),
            ("IReadOnlySet<T>", c.HasIReadOnlySet),
            ("ImmutableArray<T>", c.HasImmutableArray),
            ("[UnsafeAccessor]", c.HasUnsafeAccessor),
            ("[UnsafeAccessor] on generic types", c.HasGenericUnsafeAccessor),
            ("framework TryGetSpan/HashSpan", c.HasFrameworkSpanHelpers),
            ("framework Hash(Int128)", c.HasFrameworkHash128),
            ("Nullable.GetValueRefOrDefaultRef", c.HasNullableGetValueRefOrDefaultRef),
            ("BitConverter.SingleToInt32Bits", c.HasSingleToInt32Bits),
            ("decimal.GetBits(Span<int>)", c.HasDecimalGetBitsSpan),
            ("[RequiresUnreferencedCode]", c.HasRequiresUnreferencedCode),
            ("[RequiresDynamicCode]", c.HasRequiresDynamicCode),
            ("[UnconditionalSuppressMessage]", c.HasUnconditionalSuppressMessage)
        ];

        var suppressed = new HashSet<string>(_model.SuppressedDiagnosticIds, StringComparer.Ordinal) 
            { "CS0162", "CS0168", "CS0219", "CS0108", "CS1591", "CS8019" };

        return new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Version"] = GeneratorVersion,
            ["ContextName"] = contextName,
            ["ContextShortName"] = _model.Name,
            ["ContextAccessibility"] = _model.Accessibility,
            ["Roots"] = CommentList(_types.Where(t => t.IsRoot).Select(t => Display(t.GlobalName))),
            ["TypeCount"] = _types.Length.ToString(System.Globalization.CultureInfo.InvariantCulture),
            ["WrapperCount"] = wrappers.Count.ToString(System.Globalization.CultureInfo.InvariantCulture),
            ["Closure"] = CommentList(wrappers.Select(t => $"{Display(t.GlobalName)}  ({KindLabel(t)}{(t.EmitConvenienceProperty ? string.Empty : "; convenience property omitted")})")),
            ["CustomComparers"] = CommentList(_model.CustomComparers.Select(cc => $"{Display(cc.TargetTypeGlobalName)}  by {Display(cc.ComparerTypeGlobalName)}{(cc.HandleNulls ? ", handles null itself" : string.Empty)}")),
            ["UnsafeTypes"] = CommentList(_types.Where(t => t.IsUnsafe && t.EmitWrapper).Select(t => Display(t.GlobalName))),
            ["MaxSwitchCases"] = o.MaxSwitchCases.ToString(System.Globalization.CultureInfo.InvariantCulture),
            ["MaxUnorderedCollisionRun"] = o.MaxUnorderedCollisionRun.ToString(System.Globalization.CultureInfo.InvariantCulture),
            ["MaxComparisonPairs"] = o.MaxComparisonPairs.ToString("N0", System.Globalization.CultureInfo.InvariantCulture),
            ["MaxBinaryExpressionArity"] = o.MaxBinaryExpressionArity.ToString(System.Globalization.CultureInfo.InvariantCulture),
            ["StructPassByValueMaxByteSize"] = o.StructPassByValueMaxByteSize.ToString(System.Globalization.CultureInfo.InvariantCulture),
            ["ExcludeInterfacesByPrefix"] = o.ExcludeInterfacesByPrefix.Count == 0 ? "(none)" : string.Join(", ", o.ExcludeInterfacesByPrefix),
            ["LanguageVersion"] = $"{c.LanguageVersion / 100}.{c.LanguageVersion % 100}",
            ["CapabilitiesPresent"] = string.Join(", ", capabilities.Where(x => x.Present).Select(x => x.Name)).OrDefault("(none)"),
            ["CapabilitiesAbsent"] = string.Join(", ", capabilities.Where(x => !x.Present).Select(x => x.Name)).OrDefault("(none)"),
            ["Diagnostics"] = CommentList(_model.Diagnostics.Select(d => 
                $"{d.Descriptor.Id}: {string.Format(System.Globalization.CultureInfo.InvariantCulture, d.Descriptor.MessageFormat.ToString(System.Globalization.CultureInfo.InvariantCulture), d.Arguments.Cast<object>().ToArray()).Replace("*/", "* /")}")),
            ["SuppressedDiagnostics"] = string.Join(", ", suppressed.OrderBy(s => s, StringComparer.Ordinal)),
            ["NullableDirective"] = Annotations
                ? "// Annotations only: generated code declares nullability for its callers but opts out of flow analysis,\n// so the consuming project's warning policy cannot fail the build on emitted source.\n#nullable enable annotations\n"
                : string.Empty,
        };
    }

    private void EmitHeader()
    {
        var values = HeaderValues();
        foreach (var templateLine in HeaderTemplate)
        {
            var line = values.Aggregate(
                templateLine, 
                (current, value) => current.Replace("{{" + value.Key + "}}", value.Value));

            if (line.Length == 0 && templateLine.Length > 0)
                continue; // a placeholder that expanded to nothing leaves no blank line behind

            foreach (var part in line.Split('\n'))
                _w.Line(part);
        }
    }

    private void EmitFile()
    {
        EmitHeader();
        _w.Line();

        var closes = 0;
        if (_model.Namespace.Length > 0)
        {
            _w.Open($"namespace {_model.Namespace}");
            closes++;
        }

        foreach (var containing in _model.ContainingTypes)
        {
            _w.Open($"partial class {containing}");
            closes++;
        }

        using (_w.Block($"{_model.Accessibility} partial class {_model.Name}"))
        {
            EmitConstants();
            EmitLookup();
            EmitConvenienceProperties();
            foreach (var type in _types)
            {
                _cancellationToken.ThrowIfCancellationRequested();
                if (type.EmitWrapper) 
                    EmitWrapper(type);
            }

            foreach (var type in _types)
            {
                _cancellationToken.ThrowIfCancellationRequested();
                EmitCores(type);
            }

            foreach (var element in _spanCores.OrderBy(i => i))
                EmitSpanCores(Type(element));

            EmitDispatchHolders();
            EmitAccessors();
            EmitAccessorHolders();
            EmitCustomComparerHolders();
        }

        // The namespace and containing types opened above, however many there were.
        for (var i = 0; i < closes; i++) _w.Close();
    }

    private void EmitConstants()
    {
        _w.Line($"private const int MaxComparisonPairs = {_model.Options.MaxComparisonPairs};");
        _w.Line($"private const int MaxUnorderedCollisionRun = {_model.Options.MaxUnorderedCollisionRun};");
        foreach (var type in _types)
        {
            if (type.IsGuarded)
                _w.Line($"private const int Kind_{type.ShortName} = {type.GuardKind};");

            if (type.BoxedAdapterGuarded)
                _w.Line($"private const int Kind_Boxed_{type.ShortName} = {type.BoxedGuardKind};");
        }
        _w.Line();
    }

    private void EmitLookup()
    {
        var mapped = _types.Where(t => t.EmitWrapper).ToList();
        using (_w.Block("private static class ComparerMap"))
        {
            _w.Line("static ComparerMap() { }");
            _w.Line($"internal static readonly global::System.Collections.Generic.Dictionary<{KnownTypes.GlobalType}, object> Value = Build();");
            using (_w.Block($"private static global::System.Collections.Generic.Dictionary<{KnownTypes.GlobalType}, object> Build()"))
            {
                _w.Line($"global::System.Collections.Generic.Dictionary<{KnownTypes.GlobalType}, object> map = new global::System.Collections.Generic.Dictionary<{KnownTypes.GlobalType}, object>({mapped.Count});");
                foreach (var type in mapped)
                    _w.Line($"map.Add(typeof({type.GlobalName}), {type.ShortName}EqualityComparer.Instance);");

                _w.Return("map");
            }
        }
        _w.Line();
        using (_w.Block("private static class Cache<T>")) 
            _w.Line($"internal static readonly object{Q()} Value = LookupEqualityComparer(ComparerMap.Value, typeof(T));");
        _w.Line();
        EmitUnsafeAttributes(_model.HasUnsafeTypes);
        _w.Arrow(
            $"public static {KnownTypes.GlobalIEqualityComparer}<T> GetEqualityComparer<T>()", 
            "RequireEqualityComparer<T>(Cache<T>.Value)");
        _w.Line();
    }

    private void EmitConvenienceProperties()
    {
        foreach (var type in _types)
        {
            if (!type.EmitConvenienceProperty)
                continue;

            if (type.IsUnsafe)
            {
                // The attributes belong on the getter: RequiresUnreferencedCode targets methods, not properties.
                using (_w.Block($"{type.Accessibility} static {type.ShortName}EqualityComparer {Identifier(type.ShortName)}"))
                {
                    EmitUnsafeAttributes(true);
                    _w.Arrow("get", $"{type.ShortName}EqualityComparer.Instance");
                }
            }
            else
            {
                _w.Arrow(
                    $"{type.Accessibility} static {type.ShortName}EqualityComparer {Identifier(type.ShortName)}",
                    $"{type.ShortName}EqualityComparer.Instance");
            }
        }

        _w.Line();
    }

    private void EmitUnsafeAttributes(bool unsafeType)
    {
        if (!unsafeType) 
            return;

        if (_model.Capabilities.HasRequiresUnreferencedCode)
            _w.Line("[global::System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode(\"This comparer reads private fields through reflection-built delegates; trimming can remove them.\")]");

        if (_model.Capabilities.HasRequiresDynamicCode) 
            _w.Line("[global::System.Diagnostics.CodeAnalysis.RequiresDynamicCode(\"This comparer compiles expression trees for private field access.\")]");
    }

    private void EmitSuppressions(TypeModel type)
    {
        if (!_model.Capabilities.HasUnconditionalSuppressMessage || 
            type.Members.All(m => m.Access != MemberAccess.Delegate)) 
            return;

        _w.Line("[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"Trimming\", \"IL2026\", Justification = \"The warning is surfaced on the context's convenience property and GetEqualityComparer<T>().\")]");
        _w.Line("[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"AOT\", \"IL3050\", Justification = \"The warning is surfaced on the context's convenience property and GetEqualityComparer<T>().\")]");
    }

    /// <summary>Suppressions for a method, then the method itself: the attributes and what they decorate are one unit.</summary>
    private IDisposable Method(TypeModel type, string signature)
    {
        EmitSuppressions(type);
        return _w.Block(signature);
    }

    /// <summary>Same reference is equal and one null is not; every reference-type Equals_ starts here.</summary>
    private void EmitReferencePrelude()
    {
        _w.Line($"if ({RefEq("x", "y")}) return true;");
        _w.Line("if (x is null || y is null) return false;");
    }

    /// <summary>
    /// The cycle guard, for the types that need one: a pair already being compared is taken as equal, which is what
    /// bounds the recursion. The boxed adapter has its own kind, and its own reason to be guarded.
    /// </summary>
    private void EmitCycleGuard(TypeModel type, bool boxed = false)
    {
        if (!(boxed ? type.BoxedAdapterGuarded : type.IsGuarded)) 
            return;

        _w.Line($"if (!state.TryEnter(Kind_{(boxed ? "Boxed_" : string.Empty)}{type.ShortName}, x, y)) return true;");
    }

    // ----- helpers -----------------------------------------------------------------------------------------------------

    /// <summary>Returns the nullable annotation symbol if it is availble, otherwise empty string.</summary>
    private string Q() => Annotations ? "?" : string.Empty;

    private string Param(TypeModel type) => type.IsValueType ? type.GlobalName : type.GlobalName + Q();

    /// <summary>
    /// Returns csharp-safe identifier for a name (@ prefixed if it is a keyword).
    /// </summary>
    private static string Identifier(string name) => 
        SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None ? $"@{name}" : name;

    private static string StateParam(TypeModel type) =>
        type.NeedsState ? $", ref {KnownTypes.GlobalState} state" : string.Empty;

    private static string StateArg(TypeModel type) => type.NeedsState ? ", ref state" : string.Empty;

    /// <summary>Call <see cref="object.ReferenceEquals"/></summary>
    private static string RefEq(string x, string y) => $"{KnownTypes.GlobalObject}.ReferenceEquals({x}, {y})";

    private static string Combine<T>(IEnumerable<T> inputs, Func<T, string> selector) => 
        Combine(inputs.Select(selector).ToList());
    
    private static string Combine(List<string> inputs)
    {
        while (true)
            switch (inputs.Count)
            {
                case 0:
                    return "1";
                case <= MaxCombineArity:
                    return ItemList($"{KnownTypes.GlobalHashCode}.Combine(", inputs, ",", ")");
                default:
                    inputs = Chunk(inputs);
                    break;
            }
        
        // 1 round of grouping: each group of at most MaxCombineArity inputs becomes a nested call
        static List<string> Chunk(List<string> inputs)
        {
            var nested = new List<string>(capacity: inputs.Count);
            for (var i = 0; i < inputs.Count; i += MaxCombineArity) 
                nested.Add(Combine(inputs.GetRange(i, Math.Min(MaxCombineArity, inputs.Count - i))));

            return nested;
        }
    }

    private void EmitPredicates<T>(IEnumerable<T> items, Func<T, string> selector, bool terminalReturnTrue) => 
        EmitPredicates(items.Select(selector).ToList(), terminalReturnTrue);
    
    /// <summary>
    /// Emits a predicate chain as chunks of at most MaxBinaryExpressionArity,
    /// returning false on the first failed chunk.
    /// </summary>
    private void EmitPredicates(List<string> predicates, bool terminalReturnTrue)
    {
        var arity = _model.Options.MaxBinaryExpressionArity;
        if (predicates.Count == 0)
        {
            if (terminalReturnTrue) 
                _w.Line("return true;");

            return;
        }

        if (predicates.Count <= arity && terminalReturnTrue)
        {
            // "return" alone on the first line, since a single predicate is the only case that fits beside it.
            _w.Line(ItemList(predicates.Count == 1 ? "return " : "return", predicates, " &&", ";"));
            return;
        }

        for (var i = 0; i < predicates.Count; i += arity)
        {
            var chunk = predicates.GetRange(i, Math.Min(arity, predicates.Count - i));
            _w.Line(ItemList("if (!(", chunk, " &&", ")) return false;"));
        }

        if (terminalReturnTrue) 
            _w.Line("return true;");
    }

    // ----- member reads ---------------------------------------------------------------------------------------------------

    /// <summary>
    /// The expression that reads a member from a receiver of the declaring type;
    /// <paramref name="inReceiver"/> when the receiver is an in parameter.
    /// </summary>
    private static string Read(MemberModel member, string receiver, bool inReceiver)
    {
        switch (member.Access)
        {
            case MemberAccess.Direct:
                return $"{receiver}.{Identifier(member.FieldMetadataName)}";
            
            case MemberAccess.UnsafeAccessor:
                var accessor = member.GenericAccessor 
                    ? $"{member.GenericHolderName}{member.GenericTypeArguments}.{member.AccessorName}"
                    : member.AccessorName;
                return member.DeclaringTypeIsValueType
                    ? $"{accessor}(ref {WritableReceiver(receiver, inReceiver)})"
                    : $"{accessor}({receiver})";

            case MemberAccess.Delegate:
            default:
                return member.DeclaringTypeIsValueType
                    ? $"{member.DeclaringTypeShortName}_Accessors.{member.AccessorName}(ref {WritableReceiver(receiver, inReceiver)})"
                    : $"{member.DeclaringTypeShortName}_Accessors.{member.AccessorName}({receiver})";
        }
    }

    private static string WritableReceiver(string receiver, bool inReceiver) =>
        inReceiver ? $"{KnownTypes.GlobalHelpers}.AsWritableRef(in {receiver})" : receiver;

    // ----- equality expressions ---------------------------------------------------------------------------------------------

    /// <summary>A boolean expression comparing two values of <paramref name="type"/>; state is passed when the type needs it.</summary>
    private string Eq(TypeModel type, string x, string y)
    {
        switch (type.Kind)
        {
            case TypeKind.Leaf:
                return LeafEq(type, x, y);
            
            case TypeKind.Nullable:
                var payload = Type(type.PayloadTypeId);
                return $"({x}.HasValue == {y}.HasValue && (!{x}.HasValue || {Eq(payload, $"{x}.GetValueOrDefault()", $"{y}.GetValueOrDefault()")}))";
            
            case TypeKind.Struct:
                if (type.InlineAsSmallStruct)
                {
                    var predicates = type.Members.Select(m => Eq(Type(m.TypeId), Read(m, x, false), Read(m, y, false))).ToList();
                    return predicates.Count == 0 ? "true" : ItemList("(", predicates, " &&", ")");
                }

                // An `in` parameter binds by reference without the keyword at the call site; writing `in` would require a
                // variable, and arguments such as `e.Value` or `GetValueOrDefault()` are not (CS8156).
                return $"Equals_{type.ShortName}({x}, {y}{StateArg(type)})";
            
            default:
                return $"Equals_{type.ShortName}({x}, {y}{StateArg(type)})";
        }
    }

    private string LeafEq(TypeModel type, string x, string y)
    {
        switch (type.LeafRule)
        {
            case LeafRule.Primitive:
            case LeafRule.WideInteger:
            case LeafRule.Guid:
                return $"{x} == {y}";
            
            case LeafRule.Enum:
                return $"({type.EnumUnderlyingGlobalName}){x} == ({type.EnumUnderlyingGlobalName}){y}";
            
            case LeafRule.String:
                return $"string.Equals({x}, {y}, {KnownTypes.GlobalStringComparison}.Ordinal)";
            
            case LeafRule.Single:
                return $"{SingleBits(x)} == {SingleBits(y)}";
            
            case LeafRule.Double:
                return $"{KnownTypes.GlobalBitConverter}.DoubleToInt64Bits({x}) == {KnownTypes.GlobalBitConverter}.DoubleToInt64Bits({y})";
            
            case LeafRule.Half:
                return $"{KnownTypes.GlobalBitConverter}.HalfToInt16Bits({x}) == {KnownTypes.GlobalBitConverter}.HalfToInt16Bits({y})";
            
            case LeafRule.Decimal:
                return $"Equals_{type.ShortName}({x}, {y})";
            
            case LeafRule.DateTime:
                return $"{KnownTypes.GlobalHelpers}.DateTimeBits({x}) == {KnownTypes.GlobalHelpers}.DateTimeBits({y})";
            
            case LeafRule.DateTimeOffset:
                return $"({x}.Ticks == {y}.Ticks && {x}.Offset == {y}.Offset)";
            
            case LeafRule.FloatAggregate:
                // Matrix4x4 is sixteen of these; a component is as much a member as a property is.
                return ItemList("(", type.AggregateComponents.Select(c => c.IsDouble
                    ? $"{KnownTypes.GlobalBitConverter}.DoubleToInt64Bits({x}.{c.Expression}) == {KnownTypes.GlobalBitConverter}.DoubleToInt64Bits({y}.{c.Expression})"
                    : $"{SingleBits($"{x}.{c.Expression}")} == {SingleBits($"{y}.{c.Expression}")}").ToList(), " &&", ")");
            
            case LeafRule.Uri:
                return RefLeaf(x, y, 
                    $"(string.Equals({x}.OriginalString, {y}.OriginalString, {KnownTypes.GlobalStringComparison}.Ordinal) && {x}.IsAbsoluteUri == {y}.IsAbsoluteUri)");
            
            case LeafRule.Regex:
                return RefEq(x, y);
            
            case LeafRule.Custom:
                return CustomEq(type, x, y);
            
            case LeafRule.UserSimple:
            case LeafRule.Default:
            default:
                return type.IsValueType ? DefaultEq(type, x, y) : RefLeaf(x, y, DefaultEq(type, x, y));
        }
    }

    /// <summary>
    /// The default-equality rule for two non-null operands of the exact static type.
    /// A type implementing <c>IEquatable{Self}</c> is called directly:
    /// <c>x.Equals(y)</c> when that implementation is a public method on a struct or sealed class, otherwise through the constrained framework shim.
    /// Everything else, including a derived type that only inherits <c>IEquatable{Base}</c>, keeps <c>EqualityComparer{T}.Default</c>.
    /// Both direct forms are what the default comparer does for such a type after its null checks.
    /// </summary>
    private static string DefaultEq(TypeModel type, string x, string y)
    {
        if (!type.ImplementsIEquatable) 
            return $"{KnownTypes.GlobalEqualityComparer}<{type.GlobalName}>.Default.Equals({x}, {y})";

        return type is { HasPublicEquatableEquals: true, IsSealed: true }
            ? $"({x}).Equals({y})"
            : $"{KnownTypes.GlobalHelpers}.EquatableEquals<{type.GlobalName}>({x}, {y})";
    }

    private static string RefLeaf(string x, string y, string rule) => 
        $"({RefEq(x, y)} || (!({x} is null) && !({y} is null) && {rule}))";

    private string SingleBits(string value) => 
        _model.Capabilities.HasSingleToInt32Bits
            ? $"{KnownTypes.GlobalBitConverter}.SingleToInt32Bits({value})"
            : $"{KnownTypes.GlobalHelpers}.SingleToInt32Bits({value})";

    private string CustomEq(TypeModel type, string x, string y)
    {
        var custom = _model.CustomComparers[type.CustomComparerIndex];
        if (type.CustomWrapsNullable)
            return $"{custom.HolderName}.Value.Equals((global::System.Nullable<{type.GlobalName}>){x}, (global::System.Nullable<{type.GlobalName}>){y})";

        var call = $"{custom.HolderName}.Value.Equals({x}, {y})";
        if (custom.HandleNulls || (type.IsValueType && !IsNullableName(type))) 
            return call;

        return type.IsValueType 
            ? $"({x}.HasValue == {y}.HasValue && (!{x}.HasValue || {call}))" 
            : RefLeaf(x, y, call);
    }

    private static bool IsNullableName(TypeModel type) => type.GlobalName.EndsWith("?", StringComparison.Ordinal);

    // ----- hash expressions ------------------------------------------------------------------------------------------------

    /// <summary>The hash of a value reached through an edge; null means the edge is omitted at this level.</summary>
    private string? HashOrOmit(TypeModel type, string value, int level, bool sameScc)
    {
        switch (type.Kind)
        {
            case TypeKind.Leaf:
                return LeafHash(type, value);
            
            case TypeKind.Nullable:
                var payload = HashOrOmit(Type(type.PayloadTypeId), $"{value}.GetValueOrDefault()", level, sameScc);
                return payload is null ? null : $"({value}.HasValue ? {payload} : 0)";
            
            case TypeKind.Struct:
                if (type.InlineAsSmallStruct) 
                    return Combine(type.Members,
                        m => LeafHash(Type(m.TypeId), Read(m, value, false)));

                break;
        }

        var container = IsContainerOrProduct(type);
        if (level == 1)
        {
            if (container) 
                return $"GetHashCode_{type.ShortName}({value})";
            return sameScc ? $"ShallowHashCode_{type.ShortName}({value})" : $"GetHashCode_{type.ShortName}({value})";
        }

        if (sameScc) 
            return container ? $"ShallowHashCode_{type.ShortName}({value})" : null;

        return $"GetHashCode_{type.ShortName}({value})";
    }

    private static bool IsContainerOrProduct(TypeModel type) => type.Kind is 
        TypeKind.Array or TypeKind.List or TypeKind.ImmutableArray or TypeKind.ArraySegment or TypeKind.Memory or 
        TypeKind.ListInterface or TypeKind.EnumerableInterface or TypeKind.Set or TypeKind.Dictionary or 
        TypeKind.KeyValuePair or TypeKind.ValueTuple or TypeKind.Tuple;

    private string LeafHash(TypeModel type, string value)
    {
        switch (type.LeafRule)
        {
            case LeafRule.Primitive:
                return PrimitiveHash(type, value);
            case LeafRule.WideInteger:
                if (type.GlobalName.EndsWith("IntPtr", StringComparison.Ordinal)) 
                    return type.GlobalName.EndsWith("UIntPtr", StringComparison.Ordinal) 
                        ? $"{KnownTypes.GlobalHashCode}.Hash((ulong){value})" 
                        : $"{KnownTypes.GlobalHashCode}.Hash((long){value})";

                if (type.GlobalName.EndsWith("Int128", StringComparison.Ordinal) && !_model.Capabilities.HasFrameworkHash128)
                    // The resolved framework asset predates Int128: seed both 64-bit halves through the long overload.
                    return $"{KnownTypes.GlobalHashCode}.Combine({KnownTypes.GlobalHashCode}.Hash(unchecked((long){value})), {KnownTypes.GlobalHashCode}.Hash(unchecked((long)({value} >> 64))))";

                return $"{KnownTypes.GlobalHashCode}.Hash({value})";
            
            case LeafRule.Guid:
                return $"{KnownTypes.GlobalHashCode}.Hash({value})";
            
            case LeafRule.Enum:
                return type.EnumUnderlyingWidth switch
                {
                    8 => type.EnumUnderlyingUnsigned ? $"{KnownTypes.GlobalHashCode}.Hash((ulong){value})" : $"{KnownTypes.GlobalHashCode}.Hash((long){value})",
                    4 => type.EnumUnderlyingUnsigned ? $"unchecked((int)(uint){value})" : $"(int){value}",
                    _ => $"(int)({type.EnumUnderlyingGlobalName}){value}",
                };
            
            case LeafRule.String:
                return $"{KnownTypes.GlobalHashCode}.Hash({value})";
            
            case LeafRule.Single:
                return SingleBits(value);
            
            case LeafRule.Double:
                return $"{KnownTypes.GlobalHashCode}.Hash({KnownTypes.GlobalBitConverter}.DoubleToInt64Bits({value}))";
            
            case LeafRule.Half:
                return $"(int){KnownTypes.GlobalBitConverter}.HalfToInt16Bits({value})";
            
            case LeafRule.Decimal:
                return $"GetHashCode_{type.ShortName}({value})";
            
            case LeafRule.DateTime:
                return $"{KnownTypes.GlobalHashCode}.Hash({KnownTypes.GlobalHelpers}.DateTimeBits({value}))";
            
            case LeafRule.DateTimeOffset:
                return $"{KnownTypes.GlobalHashCode}.Combine({KnownTypes.GlobalHashCode}.Hash({value}.Ticks), {KnownTypes.GlobalHashCode}.Hash({value}.Offset.Ticks))";
            
            case LeafRule.FloatAggregate:
                return Combine(type.AggregateComponents,
                    c => c.IsDouble
                        ? $"{KnownTypes.GlobalHashCode}.Hash({KnownTypes.GlobalBitConverter}.DoubleToInt64Bits({value}.{c.Expression}))"
                        : SingleBits($"{value}.{c.Expression}"));
            
            case LeafRule.Uri:
                return $"({value} is null ? 0 : {KnownTypes.GlobalHashCode}.Combine({KnownTypes.GlobalHashCode}.Hash({value}.OriginalString), {value}.IsAbsoluteUri ? 1 : 0))";
            
            case LeafRule.Regex:
                return $"{KnownTypes.GlobalRuntimeHelpers}.GetHashCode({value})";
            
            case LeafRule.Custom:
                return CustomHash(type, value);
            
            case LeafRule.UserSimple:
            case LeafRule.Default:
            default:
                return type.IsValueType
                    ? $"{value}.GetHashCode()"
                    : $"({value} is null ? 0 : {value}.GetHashCode())";
        }
    }

    private static string PrimitiveHash(TypeModel type, string value) =>
        type.GlobalName switch
        {
            "int" => value,
            "uint" => $"unchecked((int){value})",
            "bool" => $"({value} ? 1 : 0)",
            _ => $"(int){value}"
        };

    private string CustomHash(TypeModel type, string value)
    {
        var custom = _model.CustomComparers[type.CustomComparerIndex];
        if (type.CustomWrapsNullable)
            return $"{custom.HolderName}.Value.GetHashCode((global::System.Nullable<{type.GlobalName}>){value})";

        var call = $"{custom.HolderName}.Value.GetHashCode({value})";
        if (custom.HandleNulls || (type.IsValueType && !IsNullableName(type))) 
            return call;

        return type.IsValueType 
            ? $"({value}.HasValue ? {call} : 0)" 
            : $"({value} is null ? 0 : {call})";
    }

    // ----- wrappers -----------------------------------------------------------------------------------------------------

    private void EmitWrapper(TypeModel type)
    {
        var name = $"{type.ShortName}EqualityComparer";
        _w.Line($"[global::System.CodeDom.Compiler.GeneratedCode(\"DeepEquals.SourceGenerator\", \"{GeneratorVersion}\")]");
        
        // A reference-type wrapper accepts null on both sides, so under nullable annotations it implements IEqualityComparer<T?>.
        using (_w.Block($"{type.Accessibility} sealed class {name} : {KnownTypes.GlobalIEqualityComparer}<{Param(type)}>"))
        {
            _w.Line($"public static readonly {name} Instance = new {name}();");
            _w.Line($"private {name}() {{ }}");
            _w.Line();
            
            // The comparer for object declares an instance Equals(object, object),
            // which hides the static one every class inherits from object; `new` states that this is meant.
            using (Method(type, $"public {(type.IsObject ? "new " : string.Empty)}bool Equals({Param(type)} x, {Param(type)} y)"))
            {
                _w.Line($"{KnownTypes.GlobalRuntimeHelpers}.EnsureSufficientExecutionStack();");
                var body = WrapperEqualsBody(type);
                if (type.NeedsState)
                {
                    _w.Line($"{KnownTypes.GlobalState} state = new {KnownTypes.GlobalState}(MaxComparisonPairs);");
                    using (_w.Block("try"))
                        _w.Return(body);
                    using (_w.Block("finally")) 
                        _w.Line("state.Dispose();");
                }
                else
                {
                    _w.Return(body);
                }
            }
            
            _w.Line();
            using (Method(type, $"public int GetHashCode({Param(type)} o)"))
            {
                _w.Line($"{KnownTypes.GlobalRuntimeHelpers}.EnsureSufficientExecutionStack();");
                _w.Return(WrapperHashBody(type));
            }
        }
        _w.Line();
    }

    private string WrapperEqualsBody(TypeModel type) => Eq(type, "x", "y");

    private string WrapperHashBody(TypeModel type)
    {
        var hash = HashOrOmit(type, "o", 1, sameScc: false);
        return hash ?? "1";
    }

    // ----- cores per kind ----------------------------------------------------------------------------------------------------

    private void EmitCores(TypeModel type)
    {
        switch (type.Kind)
        {
            case TypeKind.Leaf:
                if (type.LeafRule == LeafRule.Decimal) 
                    EmitDecimalCores(type);

                break;
            case TypeKind.Nullable:
                break;
            
            case TypeKind.Class:
                EmitClassCores(type);
                break;
            
            case TypeKind.Struct:
                EmitStructCores(type);
                break;
            
            case TypeKind.Dispatch:
                EmitDispatchCores(type);
                break;
            
            case TypeKind.Array:
            case TypeKind.List:
                EmitArrayOrListCores(type);
                break;
            
            case TypeKind.ListInterface:
                EmitListInterfaceCores(type);
                break;
            
            case TypeKind.EnumerableInterface:
                EmitEnumerableCores(type);
                break;
            
            case TypeKind.Set:
            case TypeKind.Dictionary:
                EmitUnorderedCores(type);
                break;
            
            case TypeKind.KeyValuePair:
            case TypeKind.ValueTuple:
            case TypeKind.Tuple:
                EmitProductCores(type);
                break;
            
            case TypeKind.Memory:
            case TypeKind.ImmutableArray:
            case TypeKind.ArraySegment:
                EmitValueSequenceCores(type);
                break;
            
            default:
                throw new NotSupportedException($"The {type.Kind} shape ({type.GlobalName}) is not implemented by this generator version yet.");
        }

        if (type.HasBoxedAdapter && type.Kind != TypeKind.Struct) 
            EmitBoxedAdapter(type);
    }

    /// <summary>
    /// The reference-valued guard boundary of a boxed value shape:
    /// guards on the original boxes, then unboxes into the value body.
    /// </summary>
    private void EmitBoxedAdapter(TypeModel type)
    {
        var unboxX = Unbox(type, "x");
        var unboxY = Unbox(type, "y");
        var stateParam = type.BoxedAdapterGuarded || type.NeedsState ? $", ref {KnownTypes.GlobalState} state" : string.Empty;
        using (_w.Block($"private static bool EqualsBoxed_{type.ShortName}(object x, object y{stateParam})"))
        {
            EmitCycleGuard(type, boxed: true);
            _w.Return($"Equals_{type.ShortName}({unboxX}, {unboxY}{StateArg(type)})");
        }
        _w.Line();
    }

    /// <summary>Memory, ReadOnlyMemory, ImmutableArray and ArraySegment: value shapes whose represented sequence is compared in order.</summary>
    private void EmitValueSequenceCores(TypeModel type)
    {
        var element = Type(type.ElementTypeId);
        var p = type.GlobalName;
        var spans = _model.Capabilities.HasReadOnlySpan;
        var span = $"global::System.ReadOnlySpan<{element.GlobalName}>";

        using (_w.Block($"private static bool Equals_{type.ShortName}({p} x, {p} y{StateParam(type)})"))
        {
            switch (type.Kind)
            {
                case TypeKind.Memory:
                    _w.Line("if (x.Length != y.Length) return false;");
                    _spanCores.Add(element.Id);
                    _w.Return($"Equals_SpanOf{element.ShortName}(x.Span, y.Span{(element.NeedsState ? ", ref state" : string.Empty)})");
                    break;
            
                case TypeKind.ImmutableArray:
                    _w.Line("if (x.IsDefault || y.IsDefault) return x.IsDefault && y.IsDefault;");
                    _w.Line("if (x.Length != y.Length) return false;");
                    if (spans)
                    {
                        _spanCores.Add(element.Id);
                        _w.Return($"Equals_SpanOf{element.ShortName}(x.AsSpan(), y.AsSpan(){(element.NeedsState ? ", ref state" : string.Empty)})");
                    }
                    else
                    {
                        _w.Line("int n = x.Length;");
                        using (_w.For("n")) _w.Line($"if (!({Eq(element, "x[i]", "y[i]")})) return false;");
                        _w.Return("true");
                    }
                
                    break;
            
                default:
                    _w.Line("if (x.Count != y.Count) return false;");
                    _w.Line("if (x.Count == 0) return true;");
                    if (spans)
                    {
                        _spanCores.Add(element.Id);
                        _w.Return($"Equals_SpanOf{element.ShortName}(({span})x, ({span})y{(element.NeedsState ? ", ref state" : string.Empty)})");
                    }
                    else
                    {
                        _w.Line("int n = x.Count;");
                        using (_w.For("n")) _w.Line($"if (!({Eq(element, "x.Array![x.Offset + i]", "y.Array![y.Offset + i]").Replace("![", Annotations ? "![" : "[")})) return false;");
                        _w.Return("true");
                    }

                    break;
            }

        }

        // Level 1 hash over the represented sequence; ImmutableArray default hashes to 0.
        using (_w.Block($"private static int GetHashCode_{type.ShortName}({p} o)"))
        {
            if (type.Kind == TypeKind.ImmutableArray) 
                _w.Line("if (o.IsDefault) return 0;");

            var spanOf = type.Kind switch
            {
                TypeKind.Memory => "o.Span",
                TypeKind.ImmutableArray => "o.AsSpan()",
                _ => $"({span})o",
            };
            if (spans && _model.Capabilities.HasFrameworkSpanHelpers)
            {
                if (type.Kind == TypeKind.ArraySegment) 
                    _w.Line("if (o.Count == 0) return 1;");
                var ops = type.ElementIsSameScc ? $"{type.ShortName}ShallowOps" : $"{type.ShortName}Ops";
                _w.Return($"{KnownTypes.GlobalHashCode}.HashSpan<{element.GlobalName}, {ops}>({spanOf})");
            }
            else
            {
                // The three walks differ only in what they iterate and how an element is read.
                var (local, limit, item) = type.Kind == TypeKind.ArraySegment
                    ? ("int n = o.Count;", "n", "o.Array[o.Offset + i]")
                    : spans
                        ? ($"{span} s = {spanOf};", "s.Length", "s[i]")
                        : ("int n = o.Length;", "n", "o[i]");
                _w.Line($"{KnownTypes.GlobalHashCode}.Streaming h = default;");
                _w.Line(local);
                using (_w.For(limit)) 
                    _w.Line($"h.Add({ElementHashForContainer(type, element, item)});");
                _w.Return("h.ToHashCode()");
            }
        }

        if (type.HasShallowHash)
        {
            var count = type.Kind == TypeKind.ArraySegment ? "o.Count" : "o.Length";
            var guard = type.Kind == TypeKind.ImmutableArray ? "o.IsDefault ? 0 : " : string.Empty;
            _w.Arrow(
                $"private static int ShallowHashCode_{type.ShortName}({p} o)", 
                $"{guard}({count} == 0 ? 1 : {count})");
        }

        if (spans && _model.Capabilities.HasFrameworkSpanHelpers) 
            EmitHashOps(type, element);

        _w.Line();
    }

    private void EmitDecimalCores(TypeModel type)
    {
        // Both shapes compare the four GetBits words; only where those words live differs.
        var spanBits = _model.Capabilities.HasDecimalGetBitsSpan;
        using (_w.Block($"private static bool Equals_{type.ShortName}(decimal x, decimal y)"))
        {
            if (spanBits)
            {
                _w.Line("global::System.Span<int> a = stackalloc int[4];");
                _w.Line("global::System.Span<int> b = stackalloc int[4];");
                _w.Line("decimal.GetBits(x, a);");
                _w.Line("decimal.GetBits(y, b);");
            }
            else
            {
                _w.Line("int[] a = decimal.GetBits(x);");
                _w.Line("int[] b = decimal.GetBits(y);");
            }

            _w.Return("a[0] == b[0] && a[1] == b[1] && a[2] == b[2] && a[3] == b[3]");
        }

        using (_w.Block($"private static int GetHashCode_{type.ShortName}(decimal o)"))
        {
            if (spanBits)
            {
                _w.Line("global::System.Span<int> a = stackalloc int[4];");
                _w.Line("decimal.GetBits(o, a);");
            }
            else
            {
                _w.Line("int[] a = decimal.GetBits(o);");
            }

            _w.Return($"{KnownTypes.GlobalHashCode}.Combine(a[0], a[1], a[2], a[3])");
        }

        _w.Line();
    }

    // ----- classes ------------------------------------------------------------------------------------------------------------

    private void EmitClassCores(TypeModel type)
    {
        var p = Param(type);
        var dispatch = !type.IsSealed;

        // Equals_T: the entry core.
        using (Method(type, $"private static bool Equals_{type.ShortName}({p} x, {p} y{StateParam(type)})"))
        {
            if (dispatch)
            {
                EmitDispatchEqualsBody(type);
            }
            else if (type.TailMemberIndex >= 0)
            {
                using (_w.Block("while (true)"))
                {
                    EmitReferencePrelude();
                    EmitCycleGuard(type);

                    var predicates = type.Members
                        .Where((_, i) => i != type.TailMemberIndex)
                        .Select(t => MemberEq(t, type, "x", "y"))
                        .ToList();

                    EmitPredicates(predicates, false);
                    var tail = type.Members[type.TailMemberIndex];
                    _w.Line($"{type.GlobalName}{Q()} nextX = {Read(tail, "x", false)};");
                    _w.Line($"{type.GlobalName}{Q()} nextY = {Read(tail, "y", false)};");
                    _w.Line("x = nextX;");
                    _w.Line("y = nextY;");
                }
            }
            else
            {
                EmitReferencePrelude();
                EmitCycleGuard(type);

                _w.Return($"EqualsMembers_{type.ShortName}(x, y{StateArg(type)})");
            }

        }

        // EqualsMembers_T: the member chain, called from dispatch cores and from Equals_T.
        using (Method(type, $"private static bool EqualsMembers_{type.ShortName}({type.GlobalName} x, {type.GlobalName} y{StateParam(type)})"))
            EmitPredicates(type.Members, m => MemberEq(m, type, "x", "y"), true);

        if (type.IsGuarded)
        {
            using (_w.Block($"private static bool EqualsExact_{type.ShortName}({type.GlobalName} x, {type.GlobalName} y, ref {KnownTypes.GlobalState} state)"))
            {
                EmitCycleGuard(type);
                _w.Return($"EqualsMembers_{type.ShortName}(x, y, ref state)");
            }
        }

        // Hashes.
        if (dispatch)
        {
            EmitDispatchHash(type, level: 1);
            if (type.HasShallowHash) 
                EmitDispatchHash(type, level: 0);

            EmitMembersHash(type, level: 1, membersOnly: true);
            if (type.HasShallowHash) 
                EmitMembersHash(type, level: 0, membersOnly: true);
        }
        else
        {
            EmitMembersHash(type, level: 1, membersOnly: false);
            if (type.HasShallowHash) 
                EmitMembersHash(type, level: 0, membersOnly: false);
        }

        _w.Line();
    }

    private string MemberEq(MemberModel member, TypeModel owner, string x, string y)
    {
        var inReceiver = owner is { Kind: TypeKind.Struct, PassByValue: false };
        return Eq(
            Type(member.TypeId),
            HoistedRead(member, x, inReceiver, "X"),
            HoistedRead(member, y, inReceiver, "Y"));
    }

    /// <summary>A delegate-accessor read of a struct or nullable member is evaluated once into a local; every other read is inline.</summary>
    private string HoistedRead(MemberModel member, string receiver, bool inReceiver, string suffix)
    {
        var type = Type(member.TypeId);
        var copies = 
            member.Access == MemberAccess.Delegate && 
            (type.Kind == TypeKind.Nullable || type.Kind == TypeKind.Struct || IsContainerOrProduct(type) && type.IsValueType);
        if (!copies)
            return Read(member, receiver, inReceiver);

        var local = $"h{member.DeclarationOrder}_{suffix}";
        _w.Line($"{Param(type)} {local} = {Read(member, receiver, inReceiver)};");
        return local;
    }

    /// <summary>
    /// GetHashCode_T / ShallowHashCode_T (null-checked entry) or
    /// HashMembers_T / ShallowHashMembers_T (members only, for dispatch).
    /// </summary>
    private void EmitMembersHash(TypeModel type, int level, bool membersOnly)
    {
        var name = membersOnly
            ? (level == 1 ? "HashMembers_" : "ShallowHashMembers_") + type.ShortName
            : (level == 1 ? "GetHashCode_" : "ShallowHashCode_") + type.ShortName;
        var inReceiver = type is { Kind: TypeKind.Struct, PassByValue: false };
        var param = type.Kind == TypeKind.Struct 
            ? inReceiver ? $"in {type.GlobalName} o" : $"{type.GlobalName} o" 
            : membersOnly ? $"{type.GlobalName} o" : $"{Param(type)} o";
        using (Method(type, $"private static int {name}({param})"))
        {
            if (!membersOnly && type.Kind == TypeKind.Class) 
                _w.Line("if (o is null) return 0;");

            var inputs = new List<string>(type.Members.Count);
            foreach (var member in type.Members)
            {
                var hash = HashOrOmit(
                    Type(member.TypeId), 
                    HoistedRead(member, "o", inReceiver, "O"),
                    level, 
                    member.IsSameScc);
                if (hash is not null) 
                    inputs.Add(hash);
            }

            _w.Return(Combine(inputs));
        }
    }

    // ----- structs ------------------------------------------------------------------------------------------------------------

    private void EmitStructCores(TypeModel type)
    {
        var param = type.PassByValue ? $"{type.GlobalName}" : $"in {type.GlobalName}";
        using (Method(type, $"private static bool Equals_{type.ShortName}({param} x, {param} y{StateParam(type)})"))
            EmitPredicates(type.Members, m => MemberEq(m, type, "x", "y"), true);

        if (type.HasBoxedAdapter) 
            EmitBoxedAdapter(type);

        EmitMembersHash(type, level: 1, membersOnly: false);
        if (type.HasShallowHash) 
            EmitMembersHash(type, level: 0, membersOnly: false);

        _w.Line();
    }

    // ----- dispatch -----------------------------------------------------------------------------------------------------------

    private void EmitDispatchCores(TypeModel type)
    {
        var p = Param(type);
        using (_w.Block($"private static bool Equals_{type.ShortName}({p} x, {p} y{StateParam(type)})")) EmitDispatchEqualsBody(type);
        
        EmitDispatchHash(type, level: 1);
        if (type.HasShallowHash) 
            EmitDispatchHash(type, level: 0);
        
        _w.Line();
    }

    private void EmitDispatchEqualsBody(TypeModel type)
    {
        EmitReferencePrelude();

        var assignable = type.Cases.Where(c => !c.IsExact).ToList();
        var exact = type.Cases.Where(c => c.IsExact).ToList();

        foreach (var c in assignable)
        {
            var target = Type(c.TypeId);
            var local = $"c{c.TypeId}";
            using (_w.Block($"if (x is {target.GlobalName} x{local})"))
            {
                _w.Line($"if (!(y is {target.GlobalName} y{local})) return false;");
                _w.Return($"{AssignableEq(target, $"x{local}", $"y{local}")}");
            }
            _w.Line($"if (y is {target.GlobalName}) return false;");
        }

        _w.Line($"{KnownTypes.GlobalType} t = x.GetType();");
        _w.Line("if (t != y.GetType()) return false;");

        if (exact.Count > _model.Options.MaxSwitchCases)
        {
            using (_w.Block($"switch ({type.ShortName}_Dispatch.CaseIndex.TryGetValue(t, out int i) ? i : -1)"))
            {
                for (var k = 0; k < exact.Count; k++) 
                    _w.Line($"case {k}: return {ExactEq(type, Type(exact[k].TypeId))};");

                _w.Line($"default: throw new {KnownTypes.GlobalUnknownTypeException}(t);");
            }
        }
        else
        {
            foreach (var c in exact)
            {
                var target = Type(c.TypeId);
                _w.Line($"if (t == typeof({target.GlobalName})) return {ExactEq(type, target)};");
            }

            _w.Line($"throw new {KnownTypes.GlobalUnknownTypeException}(t);");
        }

        if (exact.Count > _model.Options.MaxSwitchCases)
            _pendingDispatchHolders.Add((type, exact));
    }

    /// <summary>The Dictionary{Type, int} holders of large dispatch shapes, emitted after every core.</summary>
    private void EmitDispatchHolders()
    {
        foreach (var (type, exact) in _pendingDispatchHolders)
        {
            using (_w.Block($"private static class {type.ShortName}_Dispatch"))
            {
                _w.Line($"static {type.ShortName}_Dispatch() {{ }}");
                _w.Line($"internal static readonly global::System.Collections.Generic.Dictionary<{KnownTypes.GlobalType}, int> CaseIndex = Build();");
                using (_w.Block($"private static global::System.Collections.Generic.Dictionary<{KnownTypes.GlobalType}, int> Build()"))
                {
                    _w.Line($"global::System.Collections.Generic.Dictionary<{KnownTypes.GlobalType}, int> map = new global::System.Collections.Generic.Dictionary<{KnownTypes.GlobalType}, int>({exact.Count});");
                    for (var k = 0; k < exact.Count; k++)
                        _w.Line($"map.Add(typeof({Type(exact[k].TypeId).GlobalName}), {k});");

                    _w.Return("map");
                }
            }
            _w.Line();
        }
    }

    /// <summary>
    /// Equality of two operands that both selected an assignable case;
    /// the operands are non-null and typed as the case.
    /// </summary>
    private string AssignableEq(TypeModel target, string x, string y)
    {
        if (target.Kind != TypeKind.Leaf) 
            return Eq(target, x, y);
        
        switch (target.LeafRule)
        {
            case LeafRule.Custom:
                var custom = _model.CustomComparers[target.CustomComparerIndex];
                return $"{custom.HolderName}.Value.Equals({x}, {y})";
            
            case LeafRule.UserSimple:
            case LeafRule.Default:
                return DefaultEq(target, x, y);
            
            default:
                return LeafEq(target, x, y);
        }
    }

    /// <summary>
    /// Equality of two operands whose exact runtime type is the case;
    /// lands past the reference, null and type checks.
    /// </summary>
    private string ExactEq(TypeModel dispatch, TypeModel target)
    {
        if (target.IsObject)
            return "true";   // two non-null values whose runtime type is exactly object have no state to differ in

        var stateArg = StateArg(target);
        switch (target.Kind)
        {
            case TypeKind.Class:
                if (target.Id == dispatch.Id)
                    return target.IsGuarded
                        ? $"EqualsExact_{target.ShortName}(x, y, ref state)"
                        : $"EqualsMembers_{target.ShortName}(x, y{stateArg})";

                var cx = $"{KnownTypes.GlobalUnsafe}.As<{target.GlobalName}>(x)";
                var cy = $"{KnownTypes.GlobalUnsafe}.As<{target.GlobalName}>(y)";
                return target.IsGuarded
                    ? $"EqualsExact_{target.ShortName}({cx}, {cy}, ref state)"
                    : $"EqualsMembers_{target.ShortName}({cx}, {cy}{stateArg})";
            
            case TypeKind.Struct:
                return target.BoxedAdapterGuarded
                    ? $"EqualsBoxed_{target.ShortName}(x, y, ref state)" 
                    : $"Equals_{target.ShortName}({Unbox(target, "x")}, {Unbox(target, "y")}{stateArg})";

            case TypeKind.Leaf:
                return LeafEq(target, $"(({target.GlobalName})x)", $"(({target.GlobalName})y)");
            
            case TypeKind.Tuple:
                return $"Equals_{target.ShortName}({KnownTypes.GlobalUnsafe}.As<{target.GlobalName}>(x), {KnownTypes.GlobalUnsafe}.As<{target.GlobalName}>(y){stateArg})";
            
            default:
                if (target.BoxedAdapterGuarded) 
                    return $"EqualsBoxed_{target.ShortName}(x, y, ref state)";

                return target.IsValueType
                    ? $"Equals_{target.ShortName}({Unbox(target, "x")}, {Unbox(target, "y")}{stateArg})"
                    : $"Equals_{target.ShortName}({KnownTypes.GlobalUnsafe}.As<{target.GlobalName}>(x), {KnownTypes.GlobalUnsafe}.As<{target.GlobalName}>(y){stateArg})";
        }
    }

    private static string Unbox(TypeModel target, string value) 
        => $"{KnownTypes.GlobalUnsafe}.Unbox<{target.GlobalName}>({value})";

    private void EmitDispatchHash(TypeModel type, int level)
    {
        var name = (level == 1 ? "GetHashCode_" : "ShallowHashCode_") + type.ShortName;
        using (_w.Block($"private static int {name}({Param(type)} o)"))
        {
            _w.Line("if (o is null) return 0;");
            var exact = type.Cases.Where(c => c.IsExact).ToList();
            foreach (var c in type.Cases.Where(c => !c.IsExact))
            {
                var target = Type(c.TypeId);
                var local = $"c{c.TypeId}";
                _w.Line($"if (o is {target.GlobalName} {local}) return {CaseHash(type, target, local, level, c.IsSameScc, isExact: false)};");
            }

            _w.Line($"{KnownTypes.GlobalType} t = o.GetType();");
            if (exact.Count > _model.Options.MaxSwitchCases)
            {
                using (_w.Block($"switch ({type.ShortName}_Dispatch.CaseIndex.TryGetValue(t, out int i) ? i : -1)"))
                {
                    for (var k = 0; k < exact.Count; k++)
                        _w.Line($"case {k}: return {CaseHash(type, Type(exact[k].TypeId), "o", level, exact[k].IsSameScc, isExact: true)};");

                    _w.Line($"default: throw new {KnownTypes.GlobalUnknownTypeException}(t);");
                }
            }
            else
            {
                foreach (var c in exact)
                {
                    var target = Type(c.TypeId);
                    _w.Line($"if (t == typeof({target.GlobalName})) return {CaseHash(type, target, "o", level, c.IsSameScc, isExact: true)};");
                }

                _w.Line($"throw new {KnownTypes.GlobalUnknownTypeException}(t);");
            }

        }
    }

    /// <summary>The hash of a dispatch case at the level the dispatch preserves: a same-SCC case keeps the level, any other is full.</summary>
    private string CaseHash(TypeModel dispatch, TypeModel target, string value, int level, bool sameScc, bool isExact)
    {
        if (target.IsObject) 
            return "1";

        var caseLevel = sameScc ? level : 1;
        switch (target.Kind)
        {
            case TypeKind.Leaf:
                var typed = isExact ? $"(({target.GlobalName}){value})" : value;
                return target.LeafRule == LeafRule.Custom 
                    ? $"{_model.CustomComparers[target.CustomComparerIndex].HolderName}.Value.GetHashCode({typed})" 
                    
                    // UserSimple and Default hash through LeafHash's direct GetHashCode() call, which is all the default comparer does.
                    : LeafHash(target, typed);

            case TypeKind.Class:
                if (target.Id == dispatch.Id) return $"{(caseLevel == 1 ? "HashMembers_" : "ShallowHashMembers_")}{target.ShortName}(o)";

                var cast = $"{KnownTypes.GlobalUnsafe}.As<{target.GlobalName}>({value})";
                return target.IsSealed
                    ? $"{(caseLevel == 1 ? "GetHashCode_" : "ShallowHashCode_")}{target.ShortName}({cast})" 
                    : $"{(caseLevel == 1 ? "HashMembers_" : "ShallowHashMembers_")}{target.ShortName}({cast})";

            case TypeKind.Struct:
                var unboxed = Unbox(target, value);
                return
                    $"{(caseLevel == 1 || !target.HasShallowHash ? "GetHashCode_" : "ShallowHashCode_")}{target.ShortName}({unboxed})";
            
            case TypeKind.Tuple:
                return
                    $"{(caseLevel == 1 || !target.HasShallowHash ? "GetHashCode_" : "ShallowHashCode_")}{target.ShortName}({KnownTypes.GlobalUnsafe}.As<{target.GlobalName}>({value}))";
            
            default:
                var operand = isExact ? target.IsValueType ? Unbox(target, value) : $"{KnownTypes.GlobalUnsafe}.As<{target.GlobalName}>({value})" : value;
                return
                    $"{(caseLevel == 1 || !target.HasShallowHash ? "GetHashCode_" : "ShallowHashCode_")}{target.ShortName}({operand})";
        }
    }

    // ----- ordered collections ------------------------------------------------------------------------------------------------

    private bool SpanAvailable(TypeModel type) => type.Kind switch
    {
        TypeKind.Array => _model.Capabilities.HasReadOnlySpan,
        TypeKind.List => _model.Capabilities is { HasReadOnlySpan: true, HasCollectionsMarshal: true },
        _ => false,
    };

    private static string SpanOf(TypeModel type, string value) => 
        type.Kind == TypeKind.List
            ? $"global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan({value})"
            : value;

    private string ElementHashForContainer(TypeModel container, TypeModel element, string value)
        => HashOrOmit(element, value, 1, container.ElementIsSameScc) ?? "0";

    private void EmitArrayOrListCores(TypeModel type)
    {
        var element = Type(type.ElementTypeId);
        var p = Param(type);
        var count = type.Kind == TypeKind.Array ? "Length" : "Count";

        using (_w.Block($"private static bool Equals_{type.ShortName}({p} x, {p} y{StateParam(type)})"))
        {
            _w.Line($"if ({RefEq("x", "y")}) return true;");
            _w.Line($"if (x is null || y is null || x.{count} != y.{count}) return false;");
            EmitCycleGuard(type);

            if (SpanAvailable(type))
            {
                _spanCores.Add(element.Id);
                _w.Return($"Equals_SpanOf{element.ShortName}({SpanOf(type, "x")}, {SpanOf(type, "y")}{StateArg(type)})");
            }
            else
            {
                _w.Line($"int n = x.{count};");
                using (_w.For("n")) _w.Line($"if (!({Eq(element, "x[i]", "y[i]")})) return false;");
                _w.Return("true");
            }

        }

        // Level 1 hash.
        using (_w.Block($"private static int GetHashCode_{type.ShortName}({p} o)"))
        {
            _w.Line("if (o is null) return 0;");
            if (SpanAvailable(type) && _model.Capabilities.HasFrameworkSpanHelpers)
            {
                var ops = type.ElementIsSameScc ? $"{type.ShortName}ShallowOps" : $"{type.ShortName}Ops";
                _w.Return($"{KnownTypes.GlobalHashCode}.HashSpan<{element.GlobalName}, {ops}>({SpanOf(type, "o")})");
            }
            else
            {
                _w.Line($"{KnownTypes.GlobalHashCode}.Streaming h = default;");
                _w.Line($"int n = o.{count};");
                using (_w.For("n")) _w.Line($"h.Add({ElementHashForContainer(type, element, "o[i]")});");
                _w.Return("h.ToHashCode()");
            }

        }

        if (type.HasShallowHash)
            _w.Arrow($"private static int ShallowHashCode_{type.ShortName}({p} o)", $"o is null ? 0 : (o.{count} == 0 ? 1 : o.{count})");

        if (SpanAvailable(type) && _model.Capabilities.HasFrameworkSpanHelpers)
            EmitHashOps(type, element);

        _w.Line();
    }

    private void EmitHashOps(TypeModel container, TypeModel element)
    {
        var name = container.ElementIsSameScc ? $"{container.ShortName}ShallowOps" : $"{container.ShortName}Ops";
        using (_w.Block($"private struct {name} : {KnownTypes.GlobalHashOps}<{element.GlobalName}>"))
        {
            _w.Arrow($"public int GetHashCode({element.GlobalName} value)", ElementHashForContainer(container, element, "value"));
        }
    }

    private void EmitSpanCores(TypeModel element)
    {
        var needsState = element.NeedsState;
        var stateParam = needsState ? $", ref {KnownTypes.GlobalState} state" : string.Empty;
        var span = $"global::System.ReadOnlySpan<{element.GlobalName}>";
        using (_w.Block($"private static bool Equals_SpanOf{element.ShortName}({span} xs, {span} ys{stateParam})"))
        {
            _w.Line("if (xs.Length != ys.Length) return false;");
            if (element is { Kind: TypeKind.Leaf, DefaultCompatible: true, ImplementsIEquatable: true } && 
                element.LeafRule != LeafRule.Custom && element.LeafRule != LeafRule.Enum) _w.Return("global::System.MemoryExtensions.SequenceEqual(xs, ys)");
            else
            {
                using (_w.For("xs.Length")) _w.Line($"if (!({Eq(element, "xs[i]", "ys[i]")})) return false;");
                _w.Return("true");
            }

        }
        _w.Line();
    }

    private void EmitListInterfaceCores(TypeModel type)
    {
        var element = Type(type.ElementTypeId);
        var p = Param(type);
        var iface = type.CollectionInterfaceGlobalName.Length > 0 ? type.CollectionInterfaceGlobalName : type.GlobalName;

        using (_w.Block($"private static bool Equals_{type.ShortName}({p} x, {p} y{StateParam(type)})"))
        {
            EmitReferencePrelude();
            EmitImmutablePreflight(element, "x", "y");
            _w.Line($"{iface} xi = x;");
            _w.Line($"{iface} yi = y;");
            _w.Line("int count = xi.Count;");
            _w.Line("if (count != yi.Count) return false;");
            EmitCycleGuard(type);

            if (_model.Capabilities.HasFrameworkSpanHelpers)
            {
                _spanCores.Add(element.Id);
                _w.Line($"if ({KnownTypes.GlobalCollections}.TryGetSpan(x, out global::System.ReadOnlySpan<{element.GlobalName}> xs) && {KnownTypes.GlobalCollections}.TryGetSpan(y, out global::System.ReadOnlySpan<{element.GlobalName}> ys)) return Equals_SpanOf{element.ShortName}(xs, ys{(element.NeedsState ? ", ref state" : string.Empty)});");
            }

            using (_w.For("count")) _w.Line($"if (!({Eq(element, "xi[i]", "yi[i]")})) return false;");
            _w.Return("true");
        }

        using (_w.Block($"private static int GetHashCode_{type.ShortName}({p} o)"))
        {
            _w.Line("if (o is null) return 0;");
            EmitImmutablePreflightHash(element, "o");
            _w.Line($"{iface} oi = o;");
            _w.Line($"{KnownTypes.GlobalHashCode}.Streaming h = default;");
            _w.Line("int n = oi.Count;");
            using (_w.For("n")) _w.Line($"h.Add({ElementHashForContainer(type, element, "oi[i]")});");
            _w.Return("h.ToHashCode()");
        }

        if (type.HasShallowHash) 
            _w.Arrow($"private static int ShallowHashCode_{type.ShortName}({p} o)", $"o is null ? 0 : ((({iface})o).Count == 0 ? 1 : (({iface})o).Count)");

        _w.Line();
    }

    private void EmitImmutablePreflight(TypeModel element, string x, string y)
    {
        if (!_model.Capabilities.HasImmutableArray) 
            return;

        var immutable = $"global::System.Collections.Immutable.ImmutableArray<{element.GlobalName}>";
        _w.Line($"bool {x}Default = {x} is {immutable} i{x} && i{x}.IsDefault;");
        _w.Line($"bool {y}Default = {y} is {immutable} i{y} && i{y}.IsDefault;");
        _w.Line($"if ({x}Default || {y}Default) return {x}Default && {y}Default;");
    }

    private void EmitImmutablePreflightHash(TypeModel element, string o)
    {
        if (!_model.Capabilities.HasImmutableArray) 
            return;

        _w.Line($"if ({o} is global::System.Collections.Immutable.ImmutableArray<{element.GlobalName}> io && io.IsDefault) return 0;");
    }

    private void EmitEnumerableCores(TypeModel type)
    {
        var element = Type(type.ElementTypeId);
        var p = Param(type);
        var enumerable = $"global::System.Collections.Generic.IEnumerable<{element.GlobalName}>";

        using (_w.Block($"private static bool Equals_{type.ShortName}({p} x, {p} y{StateParam(type)})"))
        {
            EmitReferencePrelude();
            EmitImmutablePreflight(element, "x", "y");
            _w.Line($"int xCount = x is global::System.Collections.Generic.ICollection<{element.GlobalName}> xc ? xc.Count : (x is global::System.Collections.Generic.IReadOnlyCollection<{element.GlobalName}> xr ? xr.Count : -1);");
            _w.Line($"int yCount = y is global::System.Collections.Generic.ICollection<{element.GlobalName}> yc ? yc.Count : (y is global::System.Collections.Generic.IReadOnlyCollection<{element.GlobalName}> yr ? yr.Count : -1);");
            _w.Line("if (xCount >= 0 && yCount >= 0 && xCount != yCount) return false;");
            EmitCycleGuard(type);

            if (_model.Capabilities.HasFrameworkSpanHelpers)
            {
                _spanCores.Add(element.Id);
                _w.Line($"if ({KnownTypes.GlobalCollections}.TryGetSpan(x, out global::System.ReadOnlySpan<{element.GlobalName}> xs) && {KnownTypes.GlobalCollections}.TryGetSpan(y, out global::System.ReadOnlySpan<{element.GlobalName}> ys)) return Equals_SpanOf{element.ShortName}(xs, ys{(element.NeedsState ? ", ref state" : string.Empty)});");
            }

            _w.Line("int n = 0;");
            using (_w.Block($"using (global::System.Collections.Generic.IEnumerator<{element.GlobalName}> ex = (({enumerable})x).GetEnumerator())"))
            {
                using (_w.Block($"using (global::System.Collections.Generic.IEnumerator<{element.GlobalName}> ey = (({enumerable})y).GetEnumerator())"))
                {
                    using (_w.Block("while (true)"))
                    {
                        _w.Line("bool mx = ex.MoveNext();");
                        _w.Line("bool my = ey.MoveNext();");
                        _w.Line("if (mx != my) return false;");
                        _w.Line("if (!mx) break;");
                        _w.Line($"if (!({Eq(element, "ex.Current", "ey.Current")})) return false;");
                        _w.Line("n++;");
                    }
                }
            }
            _w.Line("if ((xCount >= 0 && n != xCount) || (yCount >= 0 && n != yCount)) throw new global::System.InvalidOperationException(\"A collection enumerated a different number of elements than its Count advertised.\");");
            _w.Return("true");
        }

        using (_w.Block($"private static int GetHashCode_{type.ShortName}({p} o)"))
        {
            _w.Line("if (o is null) return 0;");
            EmitImmutablePreflightHash(element, "o");
            _w.Line($"{KnownTypes.GlobalHashCode}.Streaming h = default;");
            using (_w.Block($"foreach ({element.GlobalName} e in ({enumerable})o)")) _w.Line($"h.Add({ElementHashForContainer(type, element, "e")});");
            _w.Return("h.ToHashCode()");
        }

        if (type.HasShallowHash)
        {
            using (_w.Block($"private static int ShallowHashCode_{type.ShortName}({p} o)"))
            {
                _w.Line("if (o is null) return 0;");
                _w.Line($"int count = o is global::System.Collections.Generic.ICollection<{element.GlobalName}> c ? c.Count : (o is global::System.Collections.Generic.IReadOnlyCollection<{element.GlobalName}> r ? r.Count : -1);");
                using (_w.Block("if (count < 0)"))
                {
                    _w.Line("count = 0;");
                    _w.Line($"foreach ({element.GlobalName} e in ({enumerable})o) count++;");
                }
                _w.Return("count == 0 ? 1 : count");
            }
        }

        _w.Line();
    }

    // ----- unordered collections -----------------------------------------------------------------------------------------------

    private void EmitUnorderedCores(TypeModel type)
    {
        var dictionary = type.Kind == TypeKind.Dictionary;
        var key = dictionary ? Type(type.KeyTypeId) : Type(type.ElementTypeId);
        var value = dictionary ? Type(type.ValueTypeId) : null;
        var elementName = dictionary ? $"global::System.Collections.Generic.KeyValuePair<{key.GlobalName}, {value!.GlobalName}>" : key.GlobalName;
        var p = Param(type);
        var iface = type.CollectionInterfaceGlobalName.Length > 0 ? type.CollectionInterfaceGlobalName : type.GlobalName;
        var ops = $"{type.ShortName}Ops";

        using (_w.Block($"private static bool Equals_{type.ShortName}({p} x, {p} y{StateParam(type)})"))
        {
            EmitReferencePrelude();
            _w.Line($"{iface} xi = x;");
            _w.Line($"{iface} yi = y;");
            _w.Line("int count = xi.Count;");
            _w.Line("if (count != yi.Count) return false;");
            if (!dictionary && key is { Kind: TypeKind.Leaf, DefaultCompatible: true } && key.LeafRule != LeafRule.Custom)
            {
                var hashSet = $"global::System.Collections.Generic.HashSet<{key.GlobalName}>";
                _w.Line($"if (x is {hashSet} hx && y is {hashSet} hy && {RefEq("hx.Comparer", $"{KnownTypes.GlobalEqualityComparer}<{key.GlobalName}>.Default")} && {RefEq("hy.Comparer", $"{KnownTypes.GlobalEqualityComparer}<{key.GlobalName}>.Default")}) return hx.SetEquals(hy);");
            }

            EmitCycleGuard(type);

            var call = dictionary
                ? $"{KnownTypes.GlobalUnordered}.DictionaryEquals<{key.GlobalName}, {value!.GlobalName}, {ops}>(xi, yi, count, MaxUnorderedCollisionRun{StateArg(type)})"
                : $"{KnownTypes.GlobalUnordered}.SetEquals<{key.GlobalName}, {ops}>(xi, yi, count, MaxUnorderedCollisionRun{StateArg(type)})";
            _w.Return(call);
        }

        // Ops struct: equality and full hash of one entry.
        var opsInterface = type.NeedsState ? KnownTypes.GlobalElementOps : KnownTypes.GlobalStatelessElementOps;
        using (_w.Block($"private struct {ops} : {opsInterface}<{elementName}>"))
        {
            var stateParam = type.NeedsState ? $", ref {KnownTypes.GlobalState} state" : string.Empty;
            var entryEq = dictionary
                ? $"{Eq(key, "a.Key", "b.Key")} && {Eq(value!, "a.Value", "b.Value")}"
                : Eq(key, "a", "b");
            _w.Arrow($"public bool Equals({elementName} a, {elementName} b{stateParam})", entryEq);
            _w.Arrow($"public int GetHashCode({elementName} a)", EntryHash(type, key, value, "a", forMatching: true));
        }

        // Level 1 hash: Combine(Count, sum of entry hashes) with empty-zero finalization.
        using (_w.Block($"private static int GetHashCode_{type.ShortName}({p} o)"))
        {
            _w.Line("if (o is null) return 0;");
            _w.Line($"{iface} oi = o;");
            _w.Line("int count = oi.Count;");
            _w.Line("int sum = 0;");
            var concrete = dictionary
                ? $"global::System.Collections.Generic.Dictionary<{key.GlobalName}, {value!.GlobalName}>"
                : $"global::System.Collections.Generic.HashSet<{key.GlobalName}>";
            using (_w.Block($"if (o is {concrete} known)")) _w.Line($"foreach ({elementName} e in known) {{ unchecked {{ sum += {EntryHash(type, key, value, "e", forMatching: false)}; }} }}");
            using (_w.Block("else"))
            {
                _w.Line($"foreach ({elementName} e in (global::System.Collections.Generic.IEnumerable<{elementName}>)o) {{ unchecked {{ sum += {EntryHash(type, key, value, "e", forMatching: false)}; }} }}");
            }
            _w.Line($"int h = {KnownTypes.GlobalHashCode}.Combine(count, sum);");
            _w.Return("count == 0 && h == 0 ? 1 : h");
        }

        if (type.HasShallowHash) _w.Arrow($"private static int ShallowHashCode_{type.ShortName}({p} o)", $"o is null ? 0 : ((({iface})o).Count == 0 ? 1 : (({iface})o).Count)");

        _w.Line();
    }

    /// <summary>
    /// The hash of one set element or dictionary pair.
    /// Matching uses full element hashes; the container hash uses the SCC level.
    /// </summary>
    private string EntryHash(TypeModel container, TypeModel key, TypeModel? value, string entry, bool forMatching)
    {
        if (value is null) return forMatching ? HashOrOmit(key, entry, 1, sameScc: false) ?? "0" : ElementHashForContainer(container, key, entry);

        var k = forMatching ? HashOrOmit(key, $"{entry}.Key", 1, sameScc: false) ?? "0" : HashOrOmit(key,
            $"{entry}.Key", 1, container.KeyIsSameScc) ?? "0";
        var v = forMatching ? HashOrOmit(value, $"{entry}.Value", 1, sameScc: false) ?? "0" : HashOrOmit(value,
            $"{entry}.Value", 1, container.ValueIsSameScc) ?? "0";
        return $"{KnownTypes.GlobalHashCode}.Combine({k}, {v})";
    }

    // ----- products -------------------------------------------------------------------------------------------------------------

    private static string TupleItem(int index)
    {
        var path = string.Empty;
        while (index >= 7)
        {
            path += "Rest.";
            index -= 7;
        }

        return $"{path}Item{index + 1}";
    }

    private void EmitProductCores(TypeModel type)
    {
        var reference = type.Kind == TypeKind.Tuple;
        var p = reference ? Param(type) : type.GlobalName;
        List<(TypeModel Type, string Path, bool SameScc)> items = new(type.Kind == TypeKind.KeyValuePair ? 2 : type.ItemTypeIds.Count);
        if (type.Kind == TypeKind.KeyValuePair)
        {
            items.Add((Type(type.KeyTypeId), "Key", type.KeyIsSameScc));
            items.Add((Type(type.ValueTypeId), "Value", type.ValueIsSameScc));
        }
        else
            items.AddRange(type.ItemTypeIds.Select((t, i) => (Type(t), TupleItem(i), type.ItemsAreSameScc[i])));

        using (_w.Block($"private static bool Equals_{type.ShortName}({p} x, {p} y{StateParam(type)})"))
        {
            if (reference)
            {
                EmitReferencePrelude();
                EmitCycleGuard(type);
            }

            EmitPredicates(items, i => Eq(i.Type, $"x.{i.Path}", $"y.{i.Path}"), terminalReturnTrue: true);
        }

        for (var level = 1; level >= (type.HasShallowHash ? 0 : 1); level--)
        {
            var name = (level == 1 ? "GetHashCode_" : "ShallowHashCode_") + type.ShortName;
            using (_w.Block($"private static int {name}({p} o)"))
            {
                if (reference) _w.Line("if (o is null) return 0;");

                var inputs = new List<string>(items.Count);
                foreach (var (itemType, path, sameScc) in items)
                {
                    var hash = HashOrOmit(itemType, $"o.{path}", level, sameScc);
                    if (hash is not null) inputs.Add(hash);
                }

                _w.Return(Combine(inputs));
            }
        }

        _w.Line();
    }

    // ----- accessors ------------------------------------------------------------------------------------------------------------

    private void EmitAccessors()
    {
        var emitted = new HashSet<string>(StringComparer.Ordinal);
        var generic = new Dictionary<string, List<MemberModel>>(StringComparer.Ordinal);
        foreach (var type in _types)
        {
            foreach (var member in type.Members)
            {
                if (member.Access != MemberAccess.UnsafeAccessor) continue;

                if (member.GenericAccessor)
                {
                    if (!generic.TryGetValue(member.GenericHolderName, out var list))
                        generic[member.GenericHolderName] = list = [];

                    if (list.All(m => m.AccessorName != member.AccessorName))
                        list.Add(member);

                    continue;
                }

                if (!emitted.Add(member.AccessorName))
                    continue;

                var fieldType = Type(member.TypeId);
                var receiver = member.DeclaringTypeIsValueType ? $"ref {member.DeclaringTypeGlobalName} o" : $"{member.DeclaringTypeGlobalName} o";
                _w.Line($"[{KnownTypes.GlobalUnsafeAccessor}({KnownTypes.GlobalUnsafeAccessorKind}.Field, Name = \"{member.FieldMetadataName}\")]");
                _w.Line($"private static extern ref {Param(fieldType)} {member.AccessorName}({receiver});");
            }
        }

        if (emitted.Count > 0)
            _w.Line();

        // The runtime maps the holder's class type parameters onto the declaring type's,
        // so one holder per definition carries every accessor of that definition;
        // call sites name the constructed arguments.
        foreach (var holder in generic.OrderBy(h => h.Key, StringComparer.Ordinal))
        {
            var first = holder.Value[0];
            using (_w.Block($"private static class {holder.Key}{first.GenericTypeParameters}{first.GenericConstraints}"))
            {
                foreach (var member in holder.Value.OrderBy(m => m.AccessorName, StringComparer.Ordinal))
                {
                    var openReceiver = member.DeclaringTypeIsValueType ? $"ref {member.OpenDeclaringTypeGlobalName} o" : $"{member.OpenDeclaringTypeGlobalName} o";
                    _w.Line($"[{KnownTypes.GlobalUnsafeAccessor}({KnownTypes.GlobalUnsafeAccessorKind}.Field, Name = \"{member.FieldMetadataName}\")]");
                    _w.Line($"internal static extern ref {member.OpenFieldTypeGlobalName} {member.AccessorName}({openReceiver});");
                }

            }
            _w.Line();
        }
    }

    private void EmitAccessorHolders()
    {
        foreach (var holder in _model.AccessorHolders)
        {
            if (_model.Capabilities.HasRequiresUnreferencedCode)
                _w.Line("[global::System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode(\"Reads private fields by name through reflection-built delegates.\")]");

            if (_model.Capabilities.HasRequiresDynamicCode)
                _w.Line("[global::System.Diagnostics.CodeAnalysis.RequiresDynamicCode(\"Compiles expression trees for private field access.\")]");

            using (_w.Block($"private static class {holder.HolderName}"))
            {
                _w.Line($"static {holder.HolderName}() {{ }}");
                foreach (var member in holder.Members)
                {
                    var fieldType = Type(member.TypeId);
                    var getter = $"{KnownTypes.GlobalFieldGetter}<{holder.DeclaringTypeGlobalName}, {Param(fieldType)}>";
                    _w.Line($"private static readonly {getter} s_{member.AccessorName} = {KnownTypes.GlobalReflection}.CreateFieldGetter<{holder.DeclaringTypeGlobalName}, {Param(fieldType)}>(typeof({holder.DeclaringTypeGlobalName}), \"{member.FieldMetadataName}\");");
                    _w.Line(holder.DeclaringTypeIsValueType
                        ? $"internal static {Param(fieldType)} {member.AccessorName}(ref {holder.DeclaringTypeGlobalName} o) => s_{member.AccessorName}(ref o);"
                        : $"internal static {Param(fieldType)} {member.AccessorName}({holder.DeclaringTypeGlobalName} o) => s_{member.AccessorName}(ref o);");
                }

            }
            _w.Line();
        }
    }

    private void EmitCustomComparerHolders()
    {
        foreach (var custom in _model.CustomComparers)
        {
            var fieldType = custom.HolderTypedAsComparer ? custom.ComparerTypeGlobalName : $"{KnownTypes.GlobalIEqualityComparer}<{custom.TargetTypeGlobalName}>";
            using (_w.Block($"private static class {custom.HolderName}"))
            {
                _w.Line($"static {custom.HolderName}() {{ }}");
                _w.Line($"internal static readonly {fieldType} Value = {custom.AcquisitionExpression};");
            }
            _w.Line();
        }
    }
}

internal static class HeaderStringExtensions
{
    /// <summary>The string, or the fallback when it is empty.</summary>
    public static string OrDefault(this string value, string fallback) => value.Length == 0 ? fallback : value;
}
