using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using DeepEquals.SourceGenerator.Model;

namespace DeepEquals.SourceGenerator.Emit;

/// <summary>A straight walk over the model. No decisions are made here that the model does not already record.</summary>
internal sealed class Emitter
{
    private const int MaxCombineArity = 32;

    private readonly ContextModel _model;
    private readonly CancellationToken _cancellationToken;
    private readonly CodeWriter _w;
    private readonly TypeModel[] _types;
    private readonly HashSet<int> _spanCores = new HashSet<int>();
    private readonly List<(TypeModel Type, List<DispatchCase> Exact)> _pendingDispatchHolders = new List<(TypeModel, List<DispatchCase>)>();

    private Emitter(ContextModel model, CancellationToken cancellationToken)
    {
        _model = model;
        _cancellationToken = cancellationToken;
        _w = new CodeWriter(Math.Min(model.Types.Count * 2048 + 4096, 4 * 1024 * 1024));
        _types = model.Types.ToArray();
    }

    public static string Emit(ContextModel model, CancellationToken cancellationToken)
    {
        Emitter emitter = new Emitter(model, cancellationToken);
        emitter.EmitFile();
        return emitter._w.ToString();
    }

    private TypeModel T(int id) => _types[id];

    private bool Annotations => _model.Capabilities.NullableAnnotations;

    // ----- file ---------------------------------------------------------------------------------------------------------

    /// <summary>The package version of the generator, read once from the assembly's informational version without its build metadata.</summary>
    private static readonly string GeneratorVersion = ReadGeneratorVersion();

    private static string ReadGeneratorVersion()
    {
        System.Reflection.Assembly assembly = typeof(Emitter).Assembly;
        string? informational = (assembly.GetCustomAttributes(typeof(System.Reflection.AssemblyInformationalVersionAttribute), inherit: false).FirstOrDefault() as System.Reflection.AssemblyInformationalVersionAttribute)?.InformationalVersion;
        if (!string.IsNullOrEmpty(informational))
        {
            int plus = informational!.IndexOf('+');
            return plus < 0 ? informational : informational.Substring(0, plus);
        }

        return assembly.GetName().Version?.ToString(3) ?? "1.0.0";
    }

    /// <summary>The header template, an embedded resource with <c>{{placeholders}}</c>, read once and split into lines.</summary>
    private static readonly string[] HeaderTemplate = ReadHeaderTemplate();

    private static string[] ReadHeaderTemplate()
    {
        using System.IO.Stream? stream = typeof(Emitter).Assembly.GetManifestResourceStream("DeepEquals.SourceGenerator.Templates.AutoGeneratedHeader.cs");
        if (stream is null)
        {
            throw new InvalidOperationException("The embedded header template 'Templates/AutoGeneratedHeader.cs' is missing from the generator assembly.");
        }

        using System.IO.StreamReader reader = new System.IO.StreamReader(stream);
        return reader.ReadToEnd().Replace("\r\n", "\n").TrimEnd('\n').Split('\n');
    }

    private const string CommentIndent = "    ";

    /// <summary>A name for the block comment: no <c>global::</c>, and no <c>*/</c> that would end the comment early.</summary>
    private static string Display(string globalName) => globalName.Replace("global::", string.Empty).Replace("*/", "* /");

    /// <summary>One indented line per entry, or a single "none" line, for a list placeholder inside the header's block comment.</summary>
    private static string CommentList(IEnumerable<string> entries, string none = "none")
    {
        string[] lines = entries.ToArray();
        return lines.Length == 0 ? CommentIndent + none : string.Join("\n", lines.Select(l => CommentIndent + l));
    }

    /// <summary>Every value the header template can ask for, computed from the model alone so output stays deterministic.</summary>
    private Dictionary<string, string> HeaderValues()
    {
        string contextName = _model.Namespace.Length > 0 ? _model.Namespace + "." + _model.Name : _model.Name;
        TargetCapabilities c = _model.Capabilities;
        ContextOptions o = _model.Options;

        string KindLabel(TypeModel t) => t.Kind switch
        {
            TypeKind.Leaf => t.LeafRule switch
            {
                LeafRule.Custom => "leaf, custom comparer",
                LeafRule.UserSimple => "leaf, [SimpleType]",
                LeafRule.Enum => "leaf, enum",
                _ => "leaf, built-in",
            },
            TypeKind.Nullable => "nullable wrapper",
            TypeKind.Class => t.IsSealed ? "class, compared by members" : "class, compared by members, dispatches to derived types",
            TypeKind.Struct => "struct, compared by members",
            TypeKind.Dispatch => t.IsObject ? "object, dispatches on runtime type" : t.IsInterface ? "interface, dispatches on runtime type" : "abstract class, dispatches on runtime type",
            TypeKind.Array or TypeKind.List or TypeKind.ImmutableArray or TypeKind.ArraySegment or TypeKind.Memory or TypeKind.ListInterface or TypeKind.EnumerableInterface => "ordered collection",
            TypeKind.Set => "set, unordered",
            TypeKind.Dictionary => "dictionary, unordered",
            TypeKind.KeyValuePair or TypeKind.ValueTuple or TypeKind.Tuple => "product, compared item by item",
            _ => t.Kind.ToString().ToLowerInvariant(),
        };

        IEnumerable<TypeModel> wrappers = _types.Where(t => t.EmitWrapper);
        (string Name, bool Present)[] capabilities =
        {
            ("ReadOnlySpan<T>", c.HasReadOnlySpan),
            ("Memory<T>", c.HasMemory),
            ("CollectionsMarshal.AsSpan", c.HasCollectionsMarshal),
            ("MemoryMarshal", c.HasMemoryMarshal),
            ("IReadOnlySet<T>", c.HasIReadOnlySet),
            ("ImmutableArray<T>", c.HasImmutableArray),
            ("[UnsafeAccessor]", c.HasUnsafeAccessor),
            ("[UnsafeAccessor] on generic types", c.HasGenericUnsafeAccessor),
            ("framework TryGetSpan/HashSpan", c.HasFrameworkSpanHelpers),
            ("framework Hash(Int128)", c.HasFrameworkHash128),
            ("Nullable.GetValueRefOrDefaultRef", c.HasNullableGetValueRefOrDefaultRef),
            ("BitConverter.SingleToInt32Bits", c.HasSingleToInt32Bits),
            ("decimal.GetBits(Span<int>)", c.HasDecimalGetBitsSpan),
            ("[RequiresUnreferencedCode]", c.HasRequiresUnreferencedCode),
            ("[RequiresDynamicCode]", c.HasRequiresDynamicCode),
            ("[UnconditionalSuppressMessage]", c.HasUnconditionalSuppressMessage),
        };

        HashSet<string> suppressed = new HashSet<string>(_model.SuppressedDiagnosticIds, StringComparer.Ordinal) { "CS0162", "CS0168", "CS0219", "CS0108", "CS1591", "CS8019" };

        return new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Version"] = GeneratorVersion,
            ["ContextName"] = contextName,
            ["ContextShortName"] = _model.Name,
            ["ContextAccessibility"] = _model.Accessibility,
            ["Roots"] = CommentList(_types.Where(t => t.IsRoot).Select(t => Display(t.GlobalName))),
            ["TypeCount"] = _types.Length.ToString(System.Globalization.CultureInfo.InvariantCulture),
            ["WrapperCount"] = wrappers.Count().ToString(System.Globalization.CultureInfo.InvariantCulture),
            ["Closure"] = CommentList(wrappers.Select(t => $"{Display(t.GlobalName)}  ({KindLabel(t)}{(t.EmitConvenienceProperty ? string.Empty : "; convenience property omitted")})")),
            ["CustomComparers"] = CommentList(_model.CustomComparers.Select(cc => $"{Display(cc.TargetTypeGlobalName)}  by {Display(cc.ComparerTypeGlobalName)}{(cc.HandleNulls ? ", handles null itself" : string.Empty)}")),
            ["UnsafeTypes"] = CommentList(_types.Where(t => t.IsUnsafe && t.EmitWrapper).Select(t => Display(t.GlobalName))),
            ["MaxSwitchCases"] = o.MaxSwitchCases.ToString(System.Globalization.CultureInfo.InvariantCulture),
            ["MaxUnorderedCollisionRun"] = o.MaxUnorderedCollisionRun.ToString(System.Globalization.CultureInfo.InvariantCulture),
            ["MaxComparisonPairs"] = o.MaxComparisonPairs.ToString("N0", System.Globalization.CultureInfo.InvariantCulture),
            ["MaxBinaryExpressionArity"] = o.MaxBinaryExpressionArity.ToString(System.Globalization.CultureInfo.InvariantCulture),
            ["StructPassByValueMaxByteSize"] = o.StructPassByValueMaxByteSize.ToString(System.Globalization.CultureInfo.InvariantCulture),
            ["ExcludeInterfacesByPrefix"] = o.ExcludeInterfacesByPrefix.Count == 0 ? "(none)" : string.Join(", ", o.ExcludeInterfacesByPrefix),
            ["LanguageVersion"] = $"{c.LanguageVersion / 100}.{c.LanguageVersion % 100}",
            ["CapabilitiesPresent"] = string.Join(", ", capabilities.Where(x => x.Present).Select(x => x.Name)).OrDefault("(none)"),
            ["CapabilitiesAbsent"] = string.Join(", ", capabilities.Where(x => !x.Present).Select(x => x.Name)).OrDefault("(none)"),
            ["Diagnostics"] = CommentList(_model.Diagnostics.Select(d => $"{d.Descriptor.Id}: {string.Format(System.Globalization.CultureInfo.InvariantCulture, d.Descriptor.MessageFormat.ToString(System.Globalization.CultureInfo.InvariantCulture), d.Arguments.ToArray()).Replace("*/", "* /")}")),
            ["SuppressedDiagnostics"] = string.Join(", ", suppressed.OrderBy(s => s, StringComparer.Ordinal)),
            ["NullableDirective"] = Annotations
                ? "// Annotations only: generated code declares nullability for its callers but opts out of flow analysis,\n// so the consuming project's warning policy cannot fail the build on emitted source.\n#nullable enable annotations\n"
                : string.Empty,
        };
    }

    private void EmitHeader()
    {
        Dictionary<string, string> values = HeaderValues();
        foreach (string templateLine in HeaderTemplate)
        {
            string line = templateLine;
            foreach (KeyValuePair<string, string> value in values)
            {
                line = line.Replace("{{" + value.Key + "}}", value.Value);
            }

            if (line.Length == 0 && templateLine.Length > 0)
            {
                continue;   // a placeholder that expanded to nothing leaves no blank line behind
            }

            foreach (string part in line.Split('\n'))
            {
                _w.Line(part);
            }
        }
    }

    private void EmitFile()
    {
        EmitHeader();
        _w.Line();

        int closes = 0;
        if (_model.Namespace.Length > 0)
        {
            _w.Open("namespace " + _model.Namespace);
            closes++;
        }

        foreach (string containing in _model.ContainingTypes)
        {
            _w.Open("partial class " + containing);
            closes++;
        }

        _w.Open($"{_model.Accessibility} partial class {_model.Name}");
        EmitConstants();
        EmitLookup();
        EmitConvenienceProperties();
        foreach (TypeModel type in _types)
        {
            _cancellationToken.ThrowIfCancellationRequested();
            if (type.EmitWrapper)
            {
                EmitWrapper(type);
            }
        }

        foreach (TypeModel type in _types)
        {
            _cancellationToken.ThrowIfCancellationRequested();
            EmitCores(type);
        }

        foreach (int element in _spanCores.OrderBy(i => i))
        {
            EmitSpanCores(T(element));
        }

        EmitDispatchHolders();
        EmitAccessors();
        EmitAccessorHolders();
        EmitCustomComparerHolders();
        _w.Close();
        for (int i = 0; i < closes; i++)
        {
            _w.Close();
        }
    }

    private void EmitConstants()
    {
        _w.Line($"private const int MaxComparisonPairs = {_model.Options.MaxComparisonPairs};");
        _w.Line($"private const int MaxUnorderedCollisionRun = {_model.Options.MaxUnorderedCollisionRun};");
        foreach (TypeModel type in _types)
        {
            if (type.IsGuarded)
            {
                _w.Line($"private const int Kind_{type.ShortName} = {type.GuardKind};");
            }

            if (type.BoxedAdapterGuarded)
            {
                _w.Line($"private const int Kind_Boxed_{type.ShortName} = {type.BoxedGuardKind};");
            }
        }

        _w.Line();
    }

    private void EmitLookup()
    {
        List<TypeModel> mapped = _types.Where(t => t.EmitWrapper).ToList();
        _w.Open("private static class ComparerMap");
        _w.Line("static ComparerMap() { }");
        _w.Line($"internal static readonly global::System.Collections.Generic.Dictionary<{KnownTypes.GlobalType}, object> Value = Build();");
        _w.Open($"private static global::System.Collections.Generic.Dictionary<{KnownTypes.GlobalType}, object> Build()");
        _w.Line($"global::System.Collections.Generic.Dictionary<{KnownTypes.GlobalType}, object> map = new global::System.Collections.Generic.Dictionary<{KnownTypes.GlobalType}, object>({mapped.Count});");
        foreach (TypeModel type in mapped)
        {
            _w.Line($"map.Add(typeof({type.GlobalName}), {type.ShortName}EqualityComparer.Instance);");
        }

        _w.Line("return map;");
        _w.Close();
        _w.Close();
        _w.Line();
        _w.Open("private static class Cache<T>");
        _w.Line($"internal static readonly object{Q()} Value = LookupEqualityComparer(ComparerMap.Value, typeof(T));");
        _w.Close();
        _w.Line();
        EmitUnsafeAttributes(_model.HasUnsafeTypes);
        _w.Line($"public static {KnownTypes.GlobalIEqualityComparer}<T> GetEqualityComparer<T>() => RequireEqualityComparer<T>(Cache<T>.Value);");
        _w.Line();
    }

    private void EmitConvenienceProperties()
    {
        foreach (TypeModel type in _types)
        {
            if (!type.EmitConvenienceProperty)
            {
                continue;
            }

            if (type.IsUnsafe)
            {
                // The attributes belong on the getter: RequiresUnreferencedCode targets methods, not properties.
                _w.Open($"{type.Accessibility} static {type.ShortName}EqualityComparer {Identifier(type.ShortName)}");
                EmitUnsafeAttributes(true);
                _w.Line($"get => {type.ShortName}EqualityComparer.Instance;");
                _w.Close();
            }
            else
            {
                _w.Line($"{type.Accessibility} static {type.ShortName}EqualityComparer {Identifier(type.ShortName)} => {type.ShortName}EqualityComparer.Instance;");
            }
        }

        _w.Line();
    }

    private void EmitUnsafeAttributes(bool unsafeType)
    {
        if (!unsafeType)
        {
            return;
        }

        if (_model.Capabilities.HasRequiresUnreferencedCode)
        {
            _w.Line("[global::System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode(\"This comparer reads private fields through reflection-built delegates; trimming can remove them.\")]");
        }

        if (_model.Capabilities.HasRequiresDynamicCode)
        {
            _w.Line("[global::System.Diagnostics.CodeAnalysis.RequiresDynamicCode(\"This comparer compiles expression trees for private field access.\")]");
        }
    }

    private void EmitSuppressions(TypeModel type)
    {
        if (!_model.Capabilities.HasUnconditionalSuppressMessage || !type.Members.Any(m => m.Access == MemberAccess.Delegate))
        {
            return;
        }

        _w.Line("[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"Trimming\", \"IL2026\", Justification = \"The warning is surfaced on the context's convenience property and GetEqualityComparer<T>().\")]");
        _w.Line("[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"AOT\", \"IL3050\", Justification = \"The warning is surfaced on the context's convenience property and GetEqualityComparer<T>().\")]");
    }

    // ----- helpers -----------------------------------------------------------------------------------------------------

    private string Q() => Annotations ? "?" : string.Empty;

    private string Param(TypeModel type) => type.IsValueType ? type.GlobalName : type.GlobalName + Q();

    private static string Identifier(string name) => Microsoft.CodeAnalysis.CSharp.SyntaxFacts.GetKeywordKind(name) != Microsoft.CodeAnalysis.CSharp.SyntaxKind.None ? "@" + name : name;

    private static string StateParam(TypeModel type) => type.NeedsState ? $", ref {KnownTypes.GlobalState} state" : string.Empty;

    private static string StateArg(TypeModel type) => type.NeedsState ? ", ref state" : string.Empty;

    private static string RefEq(string x, string y) => $"{KnownTypes.GlobalObject}.ReferenceEquals({x}, {y})";

    private static string Combine(List<string> inputs)
    {
        if (inputs.Count == 0)
        {
            return "1";
        }

        if (inputs.Count == 1)
        {
            return $"{KnownTypes.GlobalHashCode}.Combine({inputs[0]})";
        }

        if (inputs.Count <= MaxCombineArity)
        {
            return $"{KnownTypes.GlobalHashCode}.Combine({string.Join(", ", inputs)})";
        }

        List<string> nested = new List<string>();
        for (int i = 0; i < inputs.Count; i += MaxCombineArity)
        {
            nested.Add(Combine(inputs.GetRange(i, Math.Min(MaxCombineArity, inputs.Count - i))));
        }

        return Combine(nested);
    }

    /// <summary>Emits a predicate chain as chunks of at most MaxBinaryExpressionArity, returning false on the first failed chunk.</summary>
    private void EmitPredicates(List<string> predicates, bool terminalReturnTrue)
    {
        int arity = _model.Options.MaxBinaryExpressionArity;
        if (predicates.Count == 0)
        {
            if (terminalReturnTrue)
            {
                _w.Line("return true;");
            }

            return;
        }

        if (predicates.Count <= arity && terminalReturnTrue)
        {
            _w.Line("return " + string.Join(" && ", predicates) + ";");
            return;
        }

        for (int i = 0; i < predicates.Count; i += arity)
        {
            List<string> chunk = predicates.GetRange(i, Math.Min(arity, predicates.Count - i));
            _w.Line($"if (!({string.Join(" && ", chunk)})) return false;");
        }

        if (terminalReturnTrue)
        {
            _w.Line("return true;");
        }
    }

    // ----- member reads ---------------------------------------------------------------------------------------------------

    /// <summary>The expression that reads a member from a receiver of the declaring type; <paramref name="inReceiver"/> when the receiver is an in parameter.</summary>
    private string Read(MemberModel member, string receiver, bool inReceiver)
    {
        switch (member.Access)
        {
            case MemberAccess.Direct:
                return $"{receiver}.{Identifier(member.FieldMetadataName)}";
            case MemberAccess.UnsafeAccessor:
                string accessor = member.GenericAccessor ? $"{member.GenericHolderName}{member.GenericTypeArguments}.{member.AccessorName}" : member.AccessorName;
                return member.DeclaringTypeIsValueType
                    ? $"{accessor}(ref {WritableReceiver(receiver, inReceiver)})"
                    : $"{accessor}({receiver})";
            default:
                return member.DeclaringTypeIsValueType
                    ? $"{member.DeclaringTypeShortName}_Accessors.{member.AccessorName}(ref {WritableReceiver(receiver, inReceiver)})"
                    : $"{member.DeclaringTypeShortName}_Accessors.{member.AccessorName}({receiver})";
        }
    }

    private static string WritableReceiver(string receiver, bool inReceiver)
        => inReceiver ? $"{KnownTypes.GlobalHelpers}.AsWritableRef(in {receiver})" : receiver;

    // ----- equality expressions ---------------------------------------------------------------------------------------------

    /// <summary>A boolean expression comparing two values of <paramref name="type"/>; state is passed when the type needs it.</summary>
    private string Eq(TypeModel type, string x, string y)
    {
        switch (type.Kind)
        {
            case TypeKind.Leaf:
                return LeafEq(type, x, y);
            case TypeKind.Nullable:
                TypeModel payload = T(type.PayloadTypeId);
                return $"({x}.HasValue == {y}.HasValue && (!{x}.HasValue || {Eq(payload, $"{x}.GetValueOrDefault()", $"{y}.GetValueOrDefault()")}))";
            case TypeKind.Struct:
                if (type.InlineAsSmallStruct)
                {
                    List<string> predicates = type.Members.Select(m => Eq(T(m.TypeId), Read(m, x, false), Read(m, y, false))).ToList();
                    return predicates.Count == 0 ? "true" : "(" + string.Join(" && ", predicates) + ")";
                }

                // An `in` parameter binds by reference without the keyword at the call site; writing `in` would require a
                // variable, and arguments such as `e.Value` or `GetValueOrDefault()` are not (CS8156).
                return $"Equals_{type.ShortName}({x}, {y}{StateArg(type)})";
            default:
                return $"Equals_{type.ShortName}({x}, {y}{StateArg(type)})";
        }
    }

    private string LeafEq(TypeModel type, string x, string y)
    {
        switch (type.LeafRule)
        {
            case LeafRule.Primitive:
            case LeafRule.WideInteger:
            case LeafRule.Guid:
                return $"{x} == {y}";
            case LeafRule.Enum:
                return $"({type.EnumUnderlyingGlobalName}){x} == ({type.EnumUnderlyingGlobalName}){y}";
            case LeafRule.String:
                return $"string.Equals({x}, {y}, {KnownTypes.GlobalStringComparison}.Ordinal)";
            case LeafRule.Single:
                return $"{SingleBits(x)} == {SingleBits(y)}";
            case LeafRule.Double:
                return $"{KnownTypes.GlobalBitConverter}.DoubleToInt64Bits({x}) == {KnownTypes.GlobalBitConverter}.DoubleToInt64Bits({y})";
            case LeafRule.Half:
                return $"{KnownTypes.GlobalBitConverter}.HalfToInt16Bits({x}) == {KnownTypes.GlobalBitConverter}.HalfToInt16Bits({y})";
            case LeafRule.Decimal:
                return $"Equals_{type.ShortName}({x}, {y})";
            case LeafRule.DateTime:
                return $"{KnownTypes.GlobalHelpers}.DateTimeBits({x}) == {KnownTypes.GlobalHelpers}.DateTimeBits({y})";
            case LeafRule.DateTimeOffset:
                return $"({x}.Ticks == {y}.Ticks && {x}.Offset == {y}.Offset)";
            case LeafRule.FloatAggregate:
                return "(" + string.Join(" && ", type.AggregateComponents.Select(c => c.IsDouble
                    ? $"{KnownTypes.GlobalBitConverter}.DoubleToInt64Bits({x}.{c.Expression}) == {KnownTypes.GlobalBitConverter}.DoubleToInt64Bits({y}.{c.Expression})"
                    : $"{SingleBits(x + "." + c.Expression)} == {SingleBits(y + "." + c.Expression)}")) + ")";
            case LeafRule.Uri:
                return RefLeaf(x, y, $"(string.Equals({x}.OriginalString, {y}.OriginalString, {KnownTypes.GlobalStringComparison}.Ordinal) && {x}.IsAbsoluteUri == {y}.IsAbsoluteUri)");
            case LeafRule.Regex:
                return RefEq(x, y);
            case LeafRule.Custom:
                return CustomEq(type, x, y);
            case LeafRule.UserSimple:
            case LeafRule.Default:
            default:
                return type.IsValueType ? DefaultEq(type, x, y) : RefLeaf(x, y, DefaultEq(type, x, y));
        }
    }

    /// <summary>
    /// The default-equality rule for two non-null operands of the exact static type. A type implementing <c>IEquatable&lt;Self&gt;</c>
    /// is called directly: <c>x.Equals(y)</c> when that implementation is a public method on a struct or sealed class, otherwise through
    /// the constrained framework shim. Everything else, including a derived type that only inherits <c>IEquatable&lt;Base&gt;</c>, keeps
    /// <c>EqualityComparer&lt;T&gt;.Default</c>. Both direct forms are what the default comparer does for such a type after its null checks.
    /// </summary>
    private static string DefaultEq(TypeModel type, string x, string y)
    {
        if (!type.ImplementsIEquatable)
        {
            return $"{KnownTypes.GlobalEqualityComparer}<{type.GlobalName}>.Default.Equals({x}, {y})";
        }

        return type.HasPublicEquatableEquals && type.IsSealed
            ? $"({x}).Equals({y})"
            : $"{KnownTypes.GlobalHelpers}.EquatableEquals<{type.GlobalName}>({x}, {y})";
    }

    private static string RefLeaf(string x, string y, string rule) => $"({RefEq(x, y)} || (!({x} is null) && !({y} is null) && {rule}))";

    private string SingleBits(string value)
        => _model.Capabilities.HasSingleToInt32Bits
            ? $"{KnownTypes.GlobalBitConverter}.SingleToInt32Bits({value})"
            : $"{KnownTypes.GlobalHelpers}.SingleToInt32Bits({value})";

    private string CustomEq(TypeModel type, string x, string y)
    {
        CustomComparerModel custom = _model.CustomComparers[type.CustomComparerIndex];
        if (type.CustomWrapsNullable)
        {
            return $"{custom.HolderName}.Value.Equals((global::System.Nullable<{type.GlobalName}>){x}, (global::System.Nullable<{type.GlobalName}>){y})";
        }

        string call = $"{custom.HolderName}.Value.Equals({x}, {y})";
        if (custom.HandleNulls || (type.IsValueType && !IsNullableName(type)))
        {
            return call;
        }

        if (type.IsValueType)
        {
            return $"({x}.HasValue == {y}.HasValue && (!{x}.HasValue || {call}))";
        }

        return RefLeaf(x, y, call);
    }

    private static bool IsNullableName(TypeModel type) => type.GlobalName.EndsWith("?", StringComparison.Ordinal);

    // ----- hash expressions ------------------------------------------------------------------------------------------------

    /// <summary>The hash of a value reached through an edge; null means the edge is omitted at this level.</summary>
    private string? HashOrOmit(TypeModel type, string value, int level, bool sameScc)
    {
        switch (type.Kind)
        {
            case TypeKind.Leaf:
                return LeafHash(type, value);
            case TypeKind.Nullable:
                string? payload = HashOrOmit(T(type.PayloadTypeId), $"{value}.GetValueOrDefault()", level, sameScc);
                return payload is null ? null : $"({value}.HasValue ? {payload} : 0)";
            case TypeKind.Struct:
                if (type.InlineAsSmallStruct)
                {
                    return Combine(type.Members.Select(m => LeafHash(T(m.TypeId), Read(m, value, false))).ToList());
                }

                break;
        }

        bool container = IsContainerOrProduct(type);
        string argument = value;
        if (level == 1)
        {
            if (container)
            {
                return $"GetHashCode_{type.ShortName}({argument})";
            }

            return sameScc ? $"ShallowHashCode_{type.ShortName}({argument})" : $"GetHashCode_{type.ShortName}({argument})";
        }

        if (sameScc)
        {
            return container ? $"ShallowHashCode_{type.ShortName}({argument})" : null;
        }

        return $"GetHashCode_{type.ShortName}({argument})";
    }

    private static bool IsContainerOrProduct(TypeModel type) => type.Kind is TypeKind.Array or TypeKind.List or TypeKind.ImmutableArray or TypeKind.ArraySegment or TypeKind.Memory
        or TypeKind.ListInterface or TypeKind.EnumerableInterface or TypeKind.Set or TypeKind.Dictionary or TypeKind.KeyValuePair or TypeKind.ValueTuple or TypeKind.Tuple;

    private string LeafHash(TypeModel type, string value)
    {
        switch (type.LeafRule)
        {
            case LeafRule.Primitive:
                return PrimitiveHash(type, value);
            case LeafRule.WideInteger:
                if (type.GlobalName.EndsWith("IntPtr", StringComparison.Ordinal))
                {
                    return type.GlobalName.EndsWith("UIntPtr", StringComparison.Ordinal) ? $"{KnownTypes.GlobalHashCode}.Hash((ulong){value})" : $"{KnownTypes.GlobalHashCode}.Hash((long){value})";
                }

                if (type.GlobalName.EndsWith("Int128", StringComparison.Ordinal) && !_model.Capabilities.HasFrameworkHash128)
                {
                    // The resolved framework asset predates Int128: seed both 64-bit halves through the long overload.
                    return $"{KnownTypes.GlobalHashCode}.Combine({KnownTypes.GlobalHashCode}.Hash(unchecked((long){value})), {KnownTypes.GlobalHashCode}.Hash(unchecked((long)({value} >> 64))))";
                }

                return $"{KnownTypes.GlobalHashCode}.Hash({value})";
            case LeafRule.Guid:
                return $"{KnownTypes.GlobalHashCode}.Hash({value})";
            case LeafRule.Enum:
                return type.EnumUnderlyingWidth switch
                {
                    8 => type.EnumUnderlyingUnsigned ? $"{KnownTypes.GlobalHashCode}.Hash((ulong){value})" : $"{KnownTypes.GlobalHashCode}.Hash((long){value})",
                    4 => type.EnumUnderlyingUnsigned ? $"unchecked((int)(uint){value})" : $"(int){value}",
                    _ => $"(int)({type.EnumUnderlyingGlobalName}){value}",
                };
            case LeafRule.String:
                return $"{KnownTypes.GlobalHashCode}.Hash({value})";
            case LeafRule.Single:
                return SingleBits(value);
            case LeafRule.Double:
                return $"{KnownTypes.GlobalHashCode}.Hash({KnownTypes.GlobalBitConverter}.DoubleToInt64Bits({value}))";
            case LeafRule.Half:
                return $"(int){KnownTypes.GlobalBitConverter}.HalfToInt16Bits({value})";
            case LeafRule.Decimal:
                return $"GetHashCode_{type.ShortName}({value})";
            case LeafRule.DateTime:
                return $"{KnownTypes.GlobalHashCode}.Hash({KnownTypes.GlobalHelpers}.DateTimeBits({value}))";
            case LeafRule.DateTimeOffset:
                return $"{KnownTypes.GlobalHashCode}.Combine({KnownTypes.GlobalHashCode}.Hash({value}.Ticks), {KnownTypes.GlobalHashCode}.Hash({value}.Offset.Ticks))";
            case LeafRule.FloatAggregate:
                return Combine(type.AggregateComponents.Select(c => c.IsDouble
                    ? $"{KnownTypes.GlobalHashCode}.Hash({KnownTypes.GlobalBitConverter}.DoubleToInt64Bits({value}.{c.Expression}))"
                    : SingleBits(value + "." + c.Expression)).ToList());
            case LeafRule.Uri:
                return $"({value} is null ? 0 : {KnownTypes.GlobalHashCode}.Combine({KnownTypes.GlobalHashCode}.Hash({value}.OriginalString), {value}.IsAbsoluteUri ? 1 : 0))";
            case LeafRule.Regex:
                return $"{KnownTypes.GlobalRuntimeHelpers}.GetHashCode({value})";
            case LeafRule.Custom:
                return CustomHash(type, value);
            case LeafRule.UserSimple:
            case LeafRule.Default:
            default:
                return type.IsValueType
                    ? $"{value}.GetHashCode()"
                    : $"({value} is null ? 0 : {value}.GetHashCode())";
        }
    }

    private static string PrimitiveHash(TypeModel type, string value)
    {
        string name = type.GlobalName;
        switch (name)
        {
            case "int":
                return value;
            case "uint":
                return $"unchecked((int){value})";
            case "bool":
                return $"({value} ? 1 : 0)";
            default:
                return $"(int){value}";
        }
    }

    private string CustomHash(TypeModel type, string value)
    {
        CustomComparerModel custom = _model.CustomComparers[type.CustomComparerIndex];
        if (type.CustomWrapsNullable)
        {
            return $"{custom.HolderName}.Value.GetHashCode((global::System.Nullable<{type.GlobalName}>){value})";
        }

        string call = $"{custom.HolderName}.Value.GetHashCode({value})";
        if (custom.HandleNulls || (type.IsValueType && !IsNullableName(type)))
        {
            return call;
        }

        return type.IsValueType ? $"({value}.HasValue ? {call} : 0)" : $"({value} is null ? 0 : {call})";
    }

    // ----- wrappers -----------------------------------------------------------------------------------------------------

    private void EmitWrapper(TypeModel type)
    {
        string name = type.ShortName + "EqualityComparer";
        _w.Line($"[global::System.CodeDom.Compiler.GeneratedCode(\"DeepEquals.SourceGenerator\", \"{GeneratorVersion}\")]");
        // A reference-type wrapper accepts null on both sides, so under nullable annotations it implements IEqualityComparer<T?>.
        _w.Open($"{type.Accessibility} sealed class {name} : {KnownTypes.GlobalIEqualityComparer}<{Param(type)}>");
        _w.Line($"public static readonly {name} Instance = new {name}();");
        _w.Line($"private {name}() {{ }}");
        _w.Line();
        EmitSuppressions(type);
        _w.Open($"public bool Equals({Param(type)} x, {Param(type)} y)");
        _w.Line($"{KnownTypes.GlobalRuntimeHelpers}.EnsureSufficientExecutionStack();");
        string body = WrapperEqualsBody(type);
        if (type.NeedsState)
        {
            _w.Line($"{KnownTypes.GlobalState} state = new {KnownTypes.GlobalState}(MaxComparisonPairs);");
            _w.Open("try");
            _w.Line($"return {body};");
            _w.Close();
            _w.Open("finally");
            _w.Line("state.Dispose();");
            _w.Close();
        }
        else
        {
            _w.Line($"return {body};");
        }

        _w.Close();
        _w.Line();
        EmitSuppressions(type);
        _w.Open($"public int GetHashCode({type.GlobalName} o)");
        _w.Line($"{KnownTypes.GlobalRuntimeHelpers}.EnsureSufficientExecutionStack();");
        _w.Line($"return {WrapperHashBody(type)};");
        _w.Close();
        _w.Close();
        _w.Line();
    }

    private string WrapperEqualsBody(TypeModel type) => Eq(type, "x", "y");

    private string WrapperHashBody(TypeModel type)
    {
        string? hash = HashOrOmit(type, "o", 1, sameScc: false);
        return hash ?? "1";
    }

    // ----- cores per kind ----------------------------------------------------------------------------------------------------

    private void EmitCores(TypeModel type)
    {
        switch (type.Kind)
        {
            case TypeKind.Leaf:
                if (type.LeafRule == LeafRule.Decimal)
                {
                    EmitDecimalCores(type);
                }

                break;
            case TypeKind.Nullable:
                break;
            case TypeKind.Class:
                EmitClassCores(type);
                break;
            case TypeKind.Struct:
                EmitStructCores(type);
                break;
            case TypeKind.Dispatch:
                EmitDispatchCores(type);
                break;
            case TypeKind.Array:
            case TypeKind.List:
                EmitArrayOrListCores(type);
                break;
            case TypeKind.ListInterface:
                EmitListInterfaceCores(type);
                break;
            case TypeKind.EnumerableInterface:
                EmitEnumerableCores(type);
                break;
            case TypeKind.Set:
            case TypeKind.Dictionary:
                EmitUnorderedCores(type);
                break;
            case TypeKind.KeyValuePair:
            case TypeKind.ValueTuple:
            case TypeKind.Tuple:
                EmitProductCores(type);
                break;
            case TypeKind.Memory:
            case TypeKind.ImmutableArray:
            case TypeKind.ArraySegment:
                EmitValueSequenceCores(type);
                break;
            default:
                throw new NotSupportedException($"The {type.Kind} shape ({type.GlobalName}) is not implemented by this generator version yet.");
        }

        if (type.HasBoxedAdapter && type.Kind != TypeKind.Struct)
        {
            EmitBoxedAdapter(type);
        }
    }

    /// <summary>The reference-valued guard boundary of a boxed value shape: guards on the original boxes, then unboxes into the value body.</summary>
    private void EmitBoxedAdapter(TypeModel type)
    {
        string unboxX = Unbox(type, "x");
        string unboxY = Unbox(type, "y");
        string stateParam = type.BoxedAdapterGuarded || type.NeedsState ? $", ref {KnownTypes.GlobalState} state" : string.Empty;
        _w.Open($"private static bool EqualsBoxed_{type.ShortName}(object x, object y{stateParam})");
        if (type.BoxedAdapterGuarded)
        {
            _w.Line($"if (!state.TryEnter(Kind_Boxed_{type.ShortName}, x, y)) return true;");
        }

        _w.Line($"return Equals_{type.ShortName}({unboxX}, {unboxY}{StateArg(type)});");
        _w.Close();
        _w.Line();
    }

    /// <summary>Memory, ReadOnlyMemory, ImmutableArray and ArraySegment: value shapes whose represented sequence is compared in order.</summary>
    private void EmitValueSequenceCores(TypeModel type)
    {
        TypeModel element = T(type.ElementTypeId);
        string p = type.GlobalName;
        bool spans = _model.Capabilities.HasReadOnlySpan;
        string span = $"global::System.ReadOnlySpan<{element.GlobalName}>";

        _w.Open($"private static bool Equals_{type.ShortName}({p} x, {p} y{StateParam(type)})");
        switch (type.Kind)
        {
            case TypeKind.Memory:
                _w.Line("if (x.Length != y.Length) return false;");
                _spanCores.Add(element.Id);
                _w.Line($"return Equals_SpanOf{element.ShortName}(x.Span, y.Span{(element.NeedsState ? ", ref state" : string.Empty)});");
                break;
            case TypeKind.ImmutableArray:
                _w.Line("if (x.IsDefault || y.IsDefault) return x.IsDefault && y.IsDefault;");
                _w.Line("if (x.Length != y.Length) return false;");
                if (spans)
                {
                    _spanCores.Add(element.Id);
                    _w.Line($"return Equals_SpanOf{element.ShortName}(x.AsSpan(), y.AsSpan(){(element.NeedsState ? ", ref state" : string.Empty)});");
                }
                else
                {
                    _w.Line("int n = x.Length;");
                    _w.Open("for (int i = 0; i < n; i++)");
                    _w.Line($"if (!({Eq(element, "x[i]", "y[i]")})) return false;");
                    _w.Close();
                    _w.Line("return true;");
                }

                break;
            default:
                _w.Line("if (x.Count != y.Count) return false;");
                _w.Line("if (x.Count == 0) return true;");
                if (spans)
                {
                    _spanCores.Add(element.Id);
                    _w.Line($"return Equals_SpanOf{element.ShortName}(({span})x, ({span})y{(element.NeedsState ? ", ref state" : string.Empty)});");
                }
                else
                {
                    _w.Line("int n = x.Count;");
                    _w.Open("for (int i = 0; i < n; i++)");
                    _w.Line($"if (!({Eq(element, "x.Array![x.Offset + i]", "y.Array![y.Offset + i]").Replace("![", Annotations ? "![" : "[")})) return false;");
                    _w.Close();
                    _w.Line("return true;");
                }

                break;
        }

        _w.Close();

        // Level 1 hash over the represented sequence; ImmutableArray default hashes to 0.
        _w.Open($"private static int GetHashCode_{type.ShortName}({p} o)");
        if (type.Kind == TypeKind.ImmutableArray)
        {
            _w.Line("if (o.IsDefault) return 0;");
        }

        string spanOf = type.Kind switch
        {
            TypeKind.Memory => "o.Span",
            TypeKind.ImmutableArray => "o.AsSpan()",
            _ => $"({span})o",
        };
        if (spans && _model.Capabilities.HasFrameworkSpanHelpers && type.Kind != TypeKind.ArraySegment)
        {
            string ops = type.ElementIsSameScc ? type.ShortName + "ShallowOps" : type.ShortName + "Ops";
            _w.Line($"return {KnownTypes.GlobalHashCode}.HashSpan<{element.GlobalName}, {ops}>({spanOf});");
        }
        else if (spans && _model.Capabilities.HasFrameworkSpanHelpers)
        {
            string ops = type.ElementIsSameScc ? type.ShortName + "ShallowOps" : type.ShortName + "Ops";
            _w.Line("if (o.Count == 0) return 1;");
            _w.Line($"return {KnownTypes.GlobalHashCode}.HashSpan<{element.GlobalName}, {ops}>({spanOf});");
        }
        else
        {
            _w.Line($"{KnownTypes.GlobalHashCode}.Streaming h = default;");
            if (type.Kind == TypeKind.ArraySegment)
            {
                _w.Line("int n = o.Count;");
                _w.Open("for (int i = 0; i < n; i++)");
                _w.Line($"h.Add({ElementHashForContainer(type, element, "o.Array[o.Offset + i]")});");
                _w.Close();
            }
            else if (spans)
            {
                _w.Line($"{span} s = {spanOf};");
                _w.Open("for (int i = 0; i < s.Length; i++)");
                _w.Line($"h.Add({ElementHashForContainer(type, element, "s[i]")});");
                _w.Close();
            }
            else
            {
                _w.Line("int n = o.Length;");
                _w.Open("for (int i = 0; i < n; i++)");
                _w.Line($"h.Add({ElementHashForContainer(type, element, "o[i]")});");
                _w.Close();
            }

            _w.Line("return h.ToHashCode();");
        }

        _w.Close();

        if (type.HasShallowHash)
        {
            string count = type.Kind == TypeKind.ArraySegment ? "o.Count" : "o.Length";
            string guard = type.Kind == TypeKind.ImmutableArray ? "o.IsDefault ? 0 : " : string.Empty;
            _w.Line($"private static int ShallowHashCode_{type.ShortName}({p} o) => {guard}({count} == 0 ? 1 : {count});");
        }

        if (spans && _model.Capabilities.HasFrameworkSpanHelpers)
        {
            EmitHashOps(type, element);
        }

        _w.Line();
    }

    private void EmitDecimalCores(TypeModel type)
    {
        if (_model.Capabilities.HasDecimalGetBitsSpan)
        {
            _w.Open($"private static bool Equals_{type.ShortName}(decimal x, decimal y)");
            _w.Line("global::System.Span<int> a = stackalloc int[4];");
            _w.Line("global::System.Span<int> b = stackalloc int[4];");
            _w.Line("decimal.GetBits(x, a);");
            _w.Line("decimal.GetBits(y, b);");
            _w.Line("return a[0] == b[0] && a[1] == b[1] && a[2] == b[2] && a[3] == b[3];");
            _w.Close();
            _w.Open($"private static int GetHashCode_{type.ShortName}(decimal o)");
            _w.Line("global::System.Span<int> a = stackalloc int[4];");
            _w.Line("decimal.GetBits(o, a);");
            _w.Line($"return {KnownTypes.GlobalHashCode}.Combine(a[0], a[1], a[2], a[3]);");
            _w.Close();
        }
        else
        {
            _w.Open($"private static bool Equals_{type.ShortName}(decimal x, decimal y)");
            _w.Line("int[] a = decimal.GetBits(x);");
            _w.Line("int[] b = decimal.GetBits(y);");
            _w.Line("return a[0] == b[0] && a[1] == b[1] && a[2] == b[2] && a[3] == b[3];");
            _w.Close();
            _w.Open($"private static int GetHashCode_{type.ShortName}(decimal o)");
            _w.Line("int[] a = decimal.GetBits(o);");
            _w.Line($"return {KnownTypes.GlobalHashCode}.Combine(a[0], a[1], a[2], a[3]);");
            _w.Close();
        }

        _w.Line();
    }

    // ----- classes ------------------------------------------------------------------------------------------------------------

    private void EmitClassCores(TypeModel type)
    {
        string p = Param(type);
        bool dispatch = !type.IsSealed;

        // Equals_T: the entry core.
        EmitSuppressions(type);
        _w.Open($"private static bool Equals_{type.ShortName}({p} x, {p} y{StateParam(type)})");
        if (dispatch)
        {
            EmitDispatchEqualsBody(type);
        }
        else if (type.TailMemberIndex >= 0)
        {
            _w.Open("while (true)");
            _w.Line($"if ({RefEq("x", "y")}) return true;");
            _w.Line("if (x is null || y is null) return false;");
            if (type.IsGuarded)
            {
                _w.Line($"if (!state.TryEnter(Kind_{type.ShortName}, x, y)) return true;");
            }

            List<string> predicates = new List<string>();
            for (int i = 0; i < type.Members.Count; i++)
            {
                if (i != type.TailMemberIndex)
                {
                    predicates.Add(MemberEq(type.Members[i], type, "x", "y"));
                }
            }

            EmitPredicates(predicates, terminalReturnTrue: false);
            MemberModel tail = type.Members[type.TailMemberIndex];
            _w.Line($"{type.GlobalName}{Q()} nextX = {Read(tail, "x", false)};");
            _w.Line($"{type.GlobalName}{Q()} nextY = {Read(tail, "y", false)};");
            _w.Line("x = nextX;");
            _w.Line("y = nextY;");
            _w.Close();
        }
        else
        {
            _w.Line($"if ({RefEq("x", "y")}) return true;");
            _w.Line("if (x is null || y is null) return false;");
            if (type.IsGuarded)
            {
                _w.Line($"if (!state.TryEnter(Kind_{type.ShortName}, x, y)) return true;");
            }

            _w.Line($"return EqualsMembers_{type.ShortName}(x, y{StateArg(type)});");
        }

        _w.Close();

        // EqualsMembers_T: the member chain, called from dispatch cores and from Equals_T.
        EmitSuppressions(type);
        _w.Open($"private static bool EqualsMembers_{type.ShortName}({type.GlobalName} x, {type.GlobalName} y{StateParam(type)})");
        EmitPredicates(type.Members.Select(m => MemberEq(m, type, "x", "y")).ToList(), terminalReturnTrue: true);
        _w.Close();

        if (type.IsGuarded)
        {
            _w.Open($"private static bool EqualsExact_{type.ShortName}({type.GlobalName} x, {type.GlobalName} y, ref {KnownTypes.GlobalState} state)");
            _w.Line($"if (!state.TryEnter(Kind_{type.ShortName}, x, y)) return true;");
            _w.Line($"return EqualsMembers_{type.ShortName}(x, y, ref state);");
            _w.Close();
        }

        // Hashes.
        if (dispatch)
        {
            EmitDispatchHash(type, level: 1);
            if (type.HasShallowHash)
            {
                EmitDispatchHash(type, level: 0);
            }

            EmitMembersHash(type, level: 1, membersOnly: true);
            if (type.HasShallowHash)
            {
                EmitMembersHash(type, level: 0, membersOnly: true);
            }
        }
        else
        {
            EmitMembersHash(type, level: 1, membersOnly: false);
            if (type.HasShallowHash)
            {
                EmitMembersHash(type, level: 0, membersOnly: false);
            }
        }

        _w.Line();
    }

    private string MemberEq(MemberModel member, TypeModel owner, string x, string y)
    {
        bool inReceiver = owner.Kind == TypeKind.Struct && !owner.PassByValue;
        return Eq(T(member.TypeId), HoistedRead(member, owner, x, inReceiver, "X"), HoistedRead(member, owner, y, inReceiver, "Y"));
    }

    /// <summary>A delegate-accessor read of a struct or nullable member is evaluated once into a local; every other read is inline.</summary>
    private string HoistedRead(MemberModel member, TypeModel owner, string receiver, bool inReceiver, string suffix)
    {
        TypeModel type = T(member.TypeId);
        bool copies = member.Access == MemberAccess.Delegate && (type.Kind == TypeKind.Nullable || type.Kind == TypeKind.Struct || IsContainerOrProduct(type) && type.IsValueType);
        if (!copies)
        {
            return Read(member, receiver, inReceiver);
        }

        string local = "h" + member.DeclarationOrder + "_" + suffix;
        _w.Line($"{Param(type)} {local} = {Read(member, receiver, inReceiver)};");
        return local;
    }

    /// <summary>GetHashCode_T / ShallowHashCode_T (null-checked entry) or HashMembers_T / ShallowHashMembers_T (members only, for dispatch).</summary>
    private void EmitMembersHash(TypeModel type, int level, bool membersOnly)
    {
        string name = membersOnly
            ? (level == 1 ? "HashMembers_" : "ShallowHashMembers_") + type.ShortName
            : (level == 1 ? "GetHashCode_" : "ShallowHashCode_") + type.ShortName;
        bool inReceiver = type.Kind == TypeKind.Struct && !type.PassByValue;
        string param = type.Kind == TypeKind.Struct ? (inReceiver ? $"in {type.GlobalName} o" : $"{type.GlobalName} o") : (membersOnly ? $"{type.GlobalName} o" : $"{Param(type)} o");
        EmitSuppressions(type);
        _w.Open($"private static int {name}({param})");
        if (!membersOnly && type.Kind == TypeKind.Class)
        {
            _w.Line("if (o is null) return 0;");
        }

        List<string> inputs = new List<string>();
        foreach (MemberModel member in type.Members)
        {
            string? hash = HashOrOmit(T(member.TypeId), HoistedRead(member, type, "o", inReceiver, "O"), level, member.IsSameScc);
            if (hash is not null)
            {
                inputs.Add(hash);
            }
        }

        _w.Line($"return {Combine(inputs)};");
        _w.Close();
    }

    // ----- structs ------------------------------------------------------------------------------------------------------------

    private void EmitStructCores(TypeModel type)
    {
        string param = type.PassByValue ? $"{type.GlobalName}" : $"in {type.GlobalName}";
        EmitSuppressions(type);
        _w.Open($"private static bool Equals_{type.ShortName}({param} x, {param} y{StateParam(type)})");
        EmitPredicates(type.Members.Select(m => MemberEq(m, type, "x", "y")).ToList(), terminalReturnTrue: true);
        _w.Close();

        if (type.HasBoxedAdapter)
        {
            EmitBoxedAdapter(type);
        }

        EmitMembersHash(type, level: 1, membersOnly: false);
        if (type.HasShallowHash)
        {
            EmitMembersHash(type, level: 0, membersOnly: false);
        }

        _w.Line();
    }

    // ----- dispatch -----------------------------------------------------------------------------------------------------------

    private void EmitDispatchCores(TypeModel type)
    {
        string p = Param(type);
        _w.Open($"private static bool Equals_{type.ShortName}({p} x, {p} y{StateParam(type)})");
        EmitDispatchEqualsBody(type);
        _w.Close();
        EmitDispatchHash(type, level: 1);
        if (type.HasShallowHash)
        {
            EmitDispatchHash(type, level: 0);
        }

        _w.Line();
    }

    private void EmitDispatchEqualsBody(TypeModel type)
    {
        _w.Line($"if ({RefEq("x", "y")}) return true;");
        _w.Line("if (x is null || y is null) return false;");

        List<DispatchCase> assignable = type.Cases.Where(c => !c.IsExact).ToList();
        List<DispatchCase> exact = type.Cases.Where(c => c.IsExact).ToList();

        foreach (DispatchCase c in assignable)
        {
            TypeModel target = T(c.TypeId);
            string local = "c" + c.TypeId;
            _w.Open($"if (x is {target.GlobalName} x{local})");
            _w.Line($"if (!(y is {target.GlobalName} y{local})) return false;");
            _w.Line($"return {AssignableEq(target, "x" + local, "y" + local)};");
            _w.Close();
            _w.Line($"if (y is {target.GlobalName}) return false;");
        }

        _w.Line($"{KnownTypes.GlobalType} t = x.GetType();");
        _w.Line("if (t != y.GetType()) return false;");

        if (exact.Count > _model.Options.MaxSwitchCases)
        {
            _w.Open($"switch ({type.ShortName}_Dispatch.CaseIndex.TryGetValue(t, out int i) ? i : -1)");
            for (int k = 0; k < exact.Count; k++)
            {
                _w.Line($"case {k}: return {ExactEq(type, T(exact[k].TypeId))};");
            }

            _w.Line($"default: throw new {KnownTypes.GlobalUnknownTypeException}(t);");
            _w.Close();
        }
        else
        {
            foreach (DispatchCase c in exact)
            {
                TypeModel target = T(c.TypeId);
                _w.Line($"if (t == typeof({target.GlobalName})) return {ExactEq(type, target)};");
            }

            _w.Line($"throw new {KnownTypes.GlobalUnknownTypeException}(t);");
        }

        if (exact.Count > _model.Options.MaxSwitchCases)
        {
            _pendingDispatchHolders.Add((type, exact));
        }
    }

    /// <summary>The Dictionary&lt;Type, int&gt; holders of large dispatch shapes, emitted after every core.</summary>
    private void EmitDispatchHolders()
    {
        foreach ((TypeModel type, List<DispatchCase> exact) in _pendingDispatchHolders)
        {
            _w.Open($"private static class {type.ShortName}_Dispatch");
            _w.Line($"static {type.ShortName}_Dispatch() {{ }}");
            _w.Line($"internal static readonly global::System.Collections.Generic.Dictionary<{KnownTypes.GlobalType}, int> CaseIndex = Build();");
            _w.Open($"private static global::System.Collections.Generic.Dictionary<{KnownTypes.GlobalType}, int> Build()");
            _w.Line($"global::System.Collections.Generic.Dictionary<{KnownTypes.GlobalType}, int> map = new global::System.Collections.Generic.Dictionary<{KnownTypes.GlobalType}, int>({exact.Count});");
            for (int k = 0; k < exact.Count; k++)
            {
                _w.Line($"map.Add(typeof({T(exact[k].TypeId).GlobalName}), {k});");
            }

            _w.Line("return map;");
            _w.Close();
            _w.Close();
            _w.Line();
        }
    }

    /// <summary>Equality of two operands that both selected an assignable case; the operands are non-null and typed as the case.</summary>
    private string AssignableEq(TypeModel target, string x, string y)
    {
        if (target.Kind == TypeKind.Leaf)
        {
            switch (target.LeafRule)
            {
                case LeafRule.Custom:
                    CustomComparerModel custom = _model.CustomComparers[target.CustomComparerIndex];
                    return $"{custom.HolderName}.Value.Equals({x}, {y})";
                case LeafRule.UserSimple:
                case LeafRule.Default:
                    return DefaultEq(target, x, y);
                default:
                    return LeafEq(target, x, y);
            }
        }

        return Eq(target, x, y);
    }

    /// <summary>Equality of two operands whose exact runtime type is the case; lands past the reference, null and type checks.</summary>
    private string ExactEq(TypeModel dispatch, TypeModel target)
    {
        if (target.IsObject)
        {
            return "true";   // two non-null values whose runtime type is exactly object have no state to differ in
        }

        string stateArg = StateArg(target);
        switch (target.Kind)
        {
            case TypeKind.Class:
                if (target.Id == dispatch.Id)
                {
                    return target.IsGuarded
                        ? $"EqualsExact_{target.ShortName}(x, y, ref state)"
                        : $"EqualsMembers_{target.ShortName}(x, y{stateArg})";
                }

                string cx = $"{KnownTypes.GlobalUnsafe}.As<{target.GlobalName}>(x)";
                string cy = $"{KnownTypes.GlobalUnsafe}.As<{target.GlobalName}>(y)";
                return target.IsGuarded
                    ? $"EqualsExact_{target.ShortName}({cx}, {cy}, ref state)"
                    : $"EqualsMembers_{target.ShortName}({cx}, {cy}{stateArg})";
            case TypeKind.Struct:
                if (target.BoxedAdapterGuarded)
                {
                    return $"EqualsBoxed_{target.ShortName}(x, y, ref state)";
                }

                return $"Equals_{target.ShortName}({Unbox(target, "x")}, {Unbox(target, "y")}{stateArg})";
            case TypeKind.Leaf:
                return LeafEq(target, $"(({target.GlobalName})x)", $"(({target.GlobalName})y)");
            case TypeKind.Tuple:
                return $"Equals_{target.ShortName}({KnownTypes.GlobalUnsafe}.As<{target.GlobalName}>(x), {KnownTypes.GlobalUnsafe}.As<{target.GlobalName}>(y){stateArg})";
            default:
                if (target.BoxedAdapterGuarded)
                {
                    return $"EqualsBoxed_{target.ShortName}(x, y, ref state)";
                }

                return target.IsValueType
                    ? $"Equals_{target.ShortName}({Unbox(target, "x")}, {Unbox(target, "y")}{stateArg})"
                    : $"Equals_{target.ShortName}({KnownTypes.GlobalUnsafe}.As<{target.GlobalName}>(x), {KnownTypes.GlobalUnsafe}.As<{target.GlobalName}>(y){stateArg})";
        }
    }

    private static string Unbox(TypeModel target, string value) => $"{KnownTypes.GlobalUnsafe}.Unbox<{target.GlobalName}>({value})";

    private void EmitDispatchHash(TypeModel type, int level)
    {
        string name = (level == 1 ? "GetHashCode_" : "ShallowHashCode_") + type.ShortName;
        _w.Open($"private static int {name}({Param(type)} o)");
        _w.Line("if (o is null) return 0;");
        List<DispatchCase> exact = type.Cases.Where(c => c.IsExact).ToList();
        foreach (DispatchCase c in type.Cases.Where(c => !c.IsExact))
        {
            TypeModel target = T(c.TypeId);
            string local = "c" + c.TypeId;
            _w.Line($"if (o is {target.GlobalName} {local}) return {CaseHash(type, target, local, level, c.IsSameScc, isExact: false)};");
        }

        _w.Line($"{KnownTypes.GlobalType} t = o.GetType();");
        if (exact.Count > _model.Options.MaxSwitchCases)
        {
            _w.Open($"switch ({type.ShortName}_Dispatch.CaseIndex.TryGetValue(t, out int i) ? i : -1)");
            for (int k = 0; k < exact.Count; k++)
            {
                _w.Line($"case {k}: return {CaseHash(type, T(exact[k].TypeId), "o", level, exact[k].IsSameScc, isExact: true)};");
            }

            _w.Line($"default: throw new {KnownTypes.GlobalUnknownTypeException}(t);");
            _w.Close();
        }
        else
        {
            foreach (DispatchCase c in exact)
            {
                TypeModel target = T(c.TypeId);
                _w.Line($"if (t == typeof({target.GlobalName})) return {CaseHash(type, target, "o", level, c.IsSameScc, isExact: true)};");
            }

            _w.Line($"throw new {KnownTypes.GlobalUnknownTypeException}(t);");
        }

        _w.Close();
    }

    /// <summary>The hash of a dispatch case at the level the dispatch preserves: a same-SCC case keeps the level, any other is full.</summary>
    private string CaseHash(TypeModel dispatch, TypeModel target, string value, int level, bool sameScc, bool isExact)
    {
        if (target.IsObject)
        {
            return "1";
        }

        int caseLevel = sameScc ? level : 1;
        switch (target.Kind)
        {
            case TypeKind.Leaf:
                string typed = isExact ? $"(({target.GlobalName}){value})" : value;
                if (target.LeafRule == LeafRule.Custom)
                {
                    return $"{_model.CustomComparers[target.CustomComparerIndex].HolderName}.Value.GetHashCode({typed})";
                }

                // UserSimple and Default hash through LeafHash's direct GetHashCode() call, which is all the default comparer does.
                return LeafHash(target, typed);
            case TypeKind.Class:
                if (target.Id == dispatch.Id)
                {
                    return (caseLevel == 1 ? "HashMembers_" : "ShallowHashMembers_") + target.ShortName + "(o)";
                }

                string cast = $"{KnownTypes.GlobalUnsafe}.As<{target.GlobalName}>({value})";
                if (target.IsSealed)
                {
                    return (caseLevel == 1 ? "GetHashCode_" : "ShallowHashCode_") + target.ShortName + $"({cast})";
                }

                return (caseLevel == 1 ? "HashMembers_" : "ShallowHashMembers_") + target.ShortName + $"({cast})";
            case TypeKind.Struct:
                string unboxed = Unbox(target, value);
                return (caseLevel == 1 || !target.HasShallowHash ? "GetHashCode_" : "ShallowHashCode_") + target.ShortName + $"({unboxed})";
            case TypeKind.Tuple:
                return (caseLevel == 1 || !target.HasShallowHash ? "GetHashCode_" : "ShallowHashCode_") + target.ShortName + $"({KnownTypes.GlobalUnsafe}.As<{target.GlobalName}>({value}))";
            default:
                string operand = isExact ? (target.IsValueType ? Unbox(target, value) : $"{KnownTypes.GlobalUnsafe}.As<{target.GlobalName}>({value})") : value;
                return (caseLevel == 1 || !target.HasShallowHash ? "GetHashCode_" : "ShallowHashCode_") + target.ShortName + $"({operand})";
        }
    }

    // ----- ordered collections ------------------------------------------------------------------------------------------------

    private bool SpanAvailable(TypeModel type) => type.Kind switch
    {
        TypeKind.Array => _model.Capabilities.HasReadOnlySpan,
        TypeKind.List => _model.Capabilities.HasReadOnlySpan && _model.Capabilities.HasCollectionsMarshal,
        _ => false,
    };

    private string SpanOf(TypeModel type, string value) => type.Kind == TypeKind.List
        ? $"global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan({value})"
        : value;

    private string ElementHashForContainer(TypeModel container, TypeModel element, string value)
        => HashOrOmit(element, value, 1, container.ElementIsSameScc) ?? "0";

    private void EmitArrayOrListCores(TypeModel type)
    {
        TypeModel element = T(type.ElementTypeId);
        string p = Param(type);
        string count = type.Kind == TypeKind.Array ? "Length" : "Count";

        _w.Open($"private static bool Equals_{type.ShortName}({p} x, {p} y{StateParam(type)})");
        _w.Line($"if ({RefEq("x", "y")}) return true;");
        _w.Line($"if (x is null || y is null || x.{count} != y.{count}) return false;");
        if (type.IsGuarded)
        {
            _w.Line($"if (!state.TryEnter(Kind_{type.ShortName}, x, y)) return true;");
        }

        if (SpanAvailable(type))
        {
            _spanCores.Add(element.Id);
            _w.Line($"return Equals_SpanOf{element.ShortName}({SpanOf(type, "x")}, {SpanOf(type, "y")}{StateArg(type)});");
        }
        else
        {
            _w.Line($"int n = x.{count};");
            _w.Open("for (int i = 0; i < n; i++)");
            _w.Line($"if (!({Eq(element, "x[i]", "y[i]")})) return false;");
            _w.Close();
            _w.Line("return true;");
        }

        _w.Close();

        // Level 1 hash.
        _w.Open($"private static int GetHashCode_{type.ShortName}({p} o)");
        _w.Line("if (o is null) return 0;");
        if (SpanAvailable(type) && _model.Capabilities.HasFrameworkSpanHelpers)
        {
            string ops = type.ElementIsSameScc ? type.ShortName + "ShallowOps" : type.ShortName + "Ops";
            _w.Line($"return {KnownTypes.GlobalHashCode}.HashSpan<{element.GlobalName}, {ops}>({SpanOf(type, "o")});");
        }
        else
        {
            _w.Line($"{KnownTypes.GlobalHashCode}.Streaming h = default;");
            _w.Line($"int n = o.{count};");
            _w.Open("for (int i = 0; i < n; i++)");
            _w.Line($"h.Add({ElementHashForContainer(type, element, "o[i]")});");
            _w.Close();
            _w.Line("return h.ToHashCode();");
        }

        _w.Close();

        if (type.HasShallowHash)
        {
            _w.Line($"private static int ShallowHashCode_{type.ShortName}({p} o) => o is null ? 0 : (o.{count} == 0 ? 1 : o.{count});");
        }

        if (SpanAvailable(type) && _model.Capabilities.HasFrameworkSpanHelpers)
        {
            EmitHashOps(type, element);
        }

        _w.Line();
    }

    private void EmitHashOps(TypeModel container, TypeModel element)
    {
        string name = container.ElementIsSameScc ? container.ShortName + "ShallowOps" : container.ShortName + "Ops";
        _w.Open($"private struct {name} : {KnownTypes.GlobalHashOps}<{element.GlobalName}>");
        _w.Line($"public int GetHashCode({element.GlobalName} value) => {ElementHashForContainer(container, element, "value")};");
        _w.Close();
    }

    private void EmitSpanCores(TypeModel element)
    {
        bool needsState = element.NeedsState;
        string stateParam = needsState ? $", ref {KnownTypes.GlobalState} state" : string.Empty;
        string span = $"global::System.ReadOnlySpan<{element.GlobalName}>";
        _w.Open($"private static bool Equals_SpanOf{element.ShortName}({span} xs, {span} ys{stateParam})");
        _w.Line("if (xs.Length != ys.Length) return false;");
        if (element.Kind == TypeKind.Leaf && element.DefaultCompatible && element.ImplementsIEquatable && element.LeafRule != LeafRule.Custom && element.LeafRule != LeafRule.Enum)
        {
            _w.Line("return global::System.MemoryExtensions.SequenceEqual(xs, ys);");
        }
        else
        {
            _w.Open("for (int i = 0; i < xs.Length; i++)");
            _w.Line($"if (!({Eq(element, "xs[i]", "ys[i]")})) return false;");
            _w.Close();
            _w.Line("return true;");
        }

        _w.Close();
        _w.Line();
    }

    private void EmitListInterfaceCores(TypeModel type)
    {
        TypeModel element = T(type.ElementTypeId);
        string p = Param(type);
        string iface = type.CollectionInterfaceGlobalName.Length > 0 ? type.CollectionInterfaceGlobalName : type.GlobalName;

        _w.Open($"private static bool Equals_{type.ShortName}({p} x, {p} y{StateParam(type)})");
        _w.Line($"if ({RefEq("x", "y")}) return true;");
        _w.Line("if (x is null || y is null) return false;");
        EmitImmutablePreflight(element, "x", "y");
        _w.Line($"{iface} xi = x;");
        _w.Line($"{iface} yi = y;");
        _w.Line("int count = xi.Count;");
        _w.Line("if (count != yi.Count) return false;");
        if (type.IsGuarded)
        {
            _w.Line($"if (!state.TryEnter(Kind_{type.ShortName}, x, y)) return true;");
        }

        if (_model.Capabilities.HasFrameworkSpanHelpers)
        {
            _spanCores.Add(element.Id);
            _w.Line($"if ({KnownTypes.GlobalCollections}.TryGetSpan(x, out global::System.ReadOnlySpan<{element.GlobalName}> xs) && {KnownTypes.GlobalCollections}.TryGetSpan(y, out global::System.ReadOnlySpan<{element.GlobalName}> ys)) return Equals_SpanOf{element.ShortName}(xs, ys{(element.NeedsState ? ", ref state" : string.Empty)});");
        }

        _w.Open("for (int i = 0; i < count; i++)");
        _w.Line($"if (!({Eq(element, "xi[i]", "yi[i]")})) return false;");
        _w.Close();
        _w.Line("return true;");
        _w.Close();

        _w.Open($"private static int GetHashCode_{type.ShortName}({p} o)");
        _w.Line("if (o is null) return 0;");
        EmitImmutablePreflightHash(element, "o");
        _w.Line($"{iface} oi = o;");
        _w.Line($"{KnownTypes.GlobalHashCode}.Streaming h = default;");
        _w.Line("int n = oi.Count;");
        _w.Open("for (int i = 0; i < n; i++)");
        _w.Line($"h.Add({ElementHashForContainer(type, element, "oi[i]")});");
        _w.Close();
        _w.Line("return h.ToHashCode();");
        _w.Close();

        if (type.HasShallowHash)
        {
            _w.Line($"private static int ShallowHashCode_{type.ShortName}({p} o) => o is null ? 0 : ((({iface})o).Count == 0 ? 1 : (({iface})o).Count);");
        }

        _w.Line();
    }

    private void EmitImmutablePreflight(TypeModel element, string x, string y)
    {
        if (!_model.Capabilities.HasImmutableArray)
        {
            return;
        }

        string immutable = $"global::System.Collections.Immutable.ImmutableArray<{element.GlobalName}>";
        _w.Line($"bool {x}Default = {x} is {immutable} i{x} && i{x}.IsDefault;");
        _w.Line($"bool {y}Default = {y} is {immutable} i{y} && i{y}.IsDefault;");
        _w.Line($"if ({x}Default || {y}Default) return {x}Default && {y}Default;");
    }

    private void EmitImmutablePreflightHash(TypeModel element, string o)
    {
        if (!_model.Capabilities.HasImmutableArray)
        {
            return;
        }

        _w.Line($"if ({o} is global::System.Collections.Immutable.ImmutableArray<{element.GlobalName}> io && io.IsDefault) return 0;");
    }

    private void EmitEnumerableCores(TypeModel type)
    {
        TypeModel element = T(type.ElementTypeId);
        string p = Param(type);
        string enumerable = $"global::System.Collections.Generic.IEnumerable<{element.GlobalName}>";

        _w.Open($"private static bool Equals_{type.ShortName}({p} x, {p} y{StateParam(type)})");
        _w.Line($"if ({RefEq("x", "y")}) return true;");
        _w.Line("if (x is null || y is null) return false;");
        EmitImmutablePreflight(element, "x", "y");
        _w.Line($"int xCount = x is global::System.Collections.Generic.ICollection<{element.GlobalName}> xc ? xc.Count : (x is global::System.Collections.Generic.IReadOnlyCollection<{element.GlobalName}> xr ? xr.Count : -1);");
        _w.Line($"int yCount = y is global::System.Collections.Generic.ICollection<{element.GlobalName}> yc ? yc.Count : (y is global::System.Collections.Generic.IReadOnlyCollection<{element.GlobalName}> yr ? yr.Count : -1);");
        _w.Line("if (xCount >= 0 && yCount >= 0 && xCount != yCount) return false;");
        if (type.IsGuarded)
        {
            _w.Line($"if (!state.TryEnter(Kind_{type.ShortName}, x, y)) return true;");
        }

        if (_model.Capabilities.HasFrameworkSpanHelpers)
        {
            _spanCores.Add(element.Id);
            _w.Line($"if ({KnownTypes.GlobalCollections}.TryGetSpan(x, out global::System.ReadOnlySpan<{element.GlobalName}> xs) && {KnownTypes.GlobalCollections}.TryGetSpan(y, out global::System.ReadOnlySpan<{element.GlobalName}> ys)) return Equals_SpanOf{element.ShortName}(xs, ys{(element.NeedsState ? ", ref state" : string.Empty)});");
        }

        _w.Line("int n = 0;");
        _w.Open($"using (global::System.Collections.Generic.IEnumerator<{element.GlobalName}> ex = (({enumerable})x).GetEnumerator())");
        _w.Open($"using (global::System.Collections.Generic.IEnumerator<{element.GlobalName}> ey = (({enumerable})y).GetEnumerator())");
        _w.Open("while (true)");
        _w.Line("bool mx = ex.MoveNext();");
        _w.Line("bool my = ey.MoveNext();");
        _w.Line("if (mx != my) return false;");
        _w.Line("if (!mx) break;");
        _w.Line($"if (!({Eq(element, "ex.Current", "ey.Current")})) return false;");
        _w.Line("n++;");
        _w.Close();
        _w.Close();
        _w.Close();
        _w.Line("if ((xCount >= 0 && n != xCount) || (yCount >= 0 && n != yCount)) throw new global::System.InvalidOperationException(\"A collection enumerated a different number of elements than its Count advertised.\");");
        _w.Line("return true;");
        _w.Close();

        _w.Open($"private static int GetHashCode_{type.ShortName}({p} o)");
        _w.Line("if (o is null) return 0;");
        EmitImmutablePreflightHash(element, "o");
        _w.Line($"{KnownTypes.GlobalHashCode}.Streaming h = default;");
        _w.Open($"foreach ({element.GlobalName} e in ({enumerable})o)");
        _w.Line($"h.Add({ElementHashForContainer(type, element, "e")});");
        _w.Close();
        _w.Line("return h.ToHashCode();");
        _w.Close();

        if (type.HasShallowHash)
        {
            _w.Open($"private static int ShallowHashCode_{type.ShortName}({p} o)");
            _w.Line("if (o is null) return 0;");
            _w.Line($"int count = o is global::System.Collections.Generic.ICollection<{element.GlobalName}> c ? c.Count : (o is global::System.Collections.Generic.IReadOnlyCollection<{element.GlobalName}> r ? r.Count : -1);");
            _w.Open("if (count < 0)");
            _w.Line("count = 0;");
            _w.Line($"foreach ({element.GlobalName} e in ({enumerable})o) count++;");
            _w.Close();
            _w.Line("return count == 0 ? 1 : count;");
            _w.Close();
        }

        _w.Line();
    }

    // ----- unordered collections -----------------------------------------------------------------------------------------------

    private void EmitUnorderedCores(TypeModel type)
    {
        bool dictionary = type.Kind == TypeKind.Dictionary;
        TypeModel key = dictionary ? T(type.KeyTypeId) : T(type.ElementTypeId);
        TypeModel? value = dictionary ? T(type.ValueTypeId) : null;
        string elementName = dictionary ? $"global::System.Collections.Generic.KeyValuePair<{key.GlobalName}, {value!.GlobalName}>" : key.GlobalName;
        string p = Param(type);
        string iface = type.CollectionInterfaceGlobalName.Length > 0 ? type.CollectionInterfaceGlobalName : type.GlobalName;
        bool anySameScc = dictionary ? (type.KeyIsSameScc || type.ValueIsSameScc) : type.ElementIsSameScc;
        string ops = type.ShortName + "Ops";

        _w.Open($"private static bool Equals_{type.ShortName}({p} x, {p} y{StateParam(type)})");
        _w.Line($"if ({RefEq("x", "y")}) return true;");
        _w.Line("if (x is null || y is null) return false;");
        _w.Line($"{iface} xi = x;");
        _w.Line($"{iface} yi = y;");
        _w.Line("int count = xi.Count;");
        _w.Line("if (count != yi.Count) return false;");
        if (!dictionary && key.Kind == TypeKind.Leaf && key.DefaultCompatible && key.LeafRule != LeafRule.Custom)
        {
            string hashSet = $"global::System.Collections.Generic.HashSet<{key.GlobalName}>";
            _w.Line($"if (x is {hashSet} hx && y is {hashSet} hy && {RefEq("hx.Comparer", $"{KnownTypes.GlobalEqualityComparer}<{key.GlobalName}>.Default")} && {RefEq("hy.Comparer", $"{KnownTypes.GlobalEqualityComparer}<{key.GlobalName}>.Default")}) return hx.SetEquals(hy);");
        }

        if (type.IsGuarded)
        {
            _w.Line($"if (!state.TryEnter(Kind_{type.ShortName}, x, y)) return true;");
        }

        string call = dictionary
            ? $"{KnownTypes.GlobalUnordered}.DictionaryEquals<{key.GlobalName}, {value!.GlobalName}, {ops}>(xi, yi, count, MaxUnorderedCollisionRun{StateArg(type)})"
            : $"{KnownTypes.GlobalUnordered}.SetEquals<{key.GlobalName}, {ops}>(xi, yi, count, MaxUnorderedCollisionRun{StateArg(type)})";
        _w.Line($"return {call};");
        _w.Close();

        // Ops struct: equality and full hash of one entry.
        string opsInterface = type.NeedsState ? KnownTypes.GlobalElementOps : KnownTypes.GlobalStatelessElementOps;
        _w.Open($"private struct {ops} : {opsInterface}<{elementName}>");
        string stateParam = type.NeedsState ? $", ref {KnownTypes.GlobalState} state" : string.Empty;
        string entryEq = dictionary
            ? $"{Eq(key, "a.Key", "b.Key")} && {Eq(value!, "a.Value", "b.Value")}"
            : Eq(key, "a", "b");
        _w.Line($"public bool Equals({elementName} a, {elementName} b{stateParam}) => {entryEq};");
        _w.Line($"public int GetHashCode({elementName} a) => {EntryHash(type, key, value, "a", level: 1, forMatching: true)};");
        _w.Close();

        // Level 1 hash: Combine(Count, sum of entry hashes) with empty-zero finalization.
        _w.Open($"private static int GetHashCode_{type.ShortName}({p} o)");
        _w.Line("if (o is null) return 0;");
        _w.Line($"{iface} oi = o;");
        _w.Line("int count = oi.Count;");
        _w.Line("int sum = 0;");
        string concrete = dictionary
            ? $"global::System.Collections.Generic.Dictionary<{key.GlobalName}, {value!.GlobalName}>"
            : $"global::System.Collections.Generic.HashSet<{key.GlobalName}>";
        _w.Open($"if (o is {concrete} known)");
        _w.Line($"foreach ({elementName} e in known) {{ unchecked {{ sum += {EntryHash(type, key, value, "e", level: 1, forMatching: false)}; }} }}");
        _w.Close();
        _w.Open("else");
        _w.Line($"foreach ({elementName} e in (global::System.Collections.Generic.IEnumerable<{elementName}>)o) {{ unchecked {{ sum += {EntryHash(type, key, value, "e", level: 1, forMatching: false)}; }} }}");
        _w.Close();
        _w.Line($"int h = {KnownTypes.GlobalHashCode}.Combine(count, sum);");
        _w.Line("return count == 0 && h == 0 ? 1 : h;");
        _w.Close();

        if (type.HasShallowHash)
        {
            _w.Line($"private static int ShallowHashCode_{type.ShortName}({p} o) => o is null ? 0 : ((({iface})o).Count == 0 ? 1 : (({iface})o).Count);");
        }

        _w.Line();
    }

    /// <summary>The hash of one set element or dictionary pair. Matching uses full element hashes; the container hash uses the SCC level.</summary>
    private string EntryHash(TypeModel container, TypeModel key, TypeModel? value, string entry, int level, bool forMatching)
    {
        if (value is null)
        {
            return forMatching ? (HashOrOmit(key, entry, 1, sameScc: false) ?? "0") : ElementHashForContainer(container, key, entry);
        }

        string k = forMatching ? (HashOrOmit(key, entry + ".Key", 1, sameScc: false) ?? "0") : (HashOrOmit(key, entry + ".Key", 1, container.KeyIsSameScc) ?? "0");
        string v = forMatching ? (HashOrOmit(value, entry + ".Value", 1, sameScc: false) ?? "0") : (HashOrOmit(value, entry + ".Value", 1, container.ValueIsSameScc) ?? "0");
        return $"{KnownTypes.GlobalHashCode}.Combine({k}, {v})";
    }

    // ----- products -------------------------------------------------------------------------------------------------------------

    private static string TupleItem(int index)
    {
        string path = string.Empty;
        while (index >= 7)
        {
            path += "Rest.";
            index -= 7;
        }

        return path + "Item" + (index + 1);
    }

    private void EmitProductCores(TypeModel type)
    {
        bool reference = type.Kind == TypeKind.Tuple;
        string p = reference ? Param(type) : type.GlobalName;
        List<(TypeModel Type, string Path, bool SameScc)> items = new List<(TypeModel, string, bool)>();
        if (type.Kind == TypeKind.KeyValuePair)
        {
            items.Add((T(type.KeyTypeId), "Key", type.KeyIsSameScc));
            items.Add((T(type.ValueTypeId), "Value", type.ValueIsSameScc));
        }
        else
        {
            for (int i = 0; i < type.ItemTypeIds.Count; i++)
            {
                items.Add((T(type.ItemTypeIds[i]), TupleItem(i), type.ItemsAreSameScc[i]));
            }
        }

        _w.Open($"private static bool Equals_{type.ShortName}({p} x, {p} y{StateParam(type)})");
        if (reference)
        {
            _w.Line($"if ({RefEq("x", "y")}) return true;");
            _w.Line("if (x is null || y is null) return false;");
            if (type.IsGuarded)
            {
                _w.Line($"if (!state.TryEnter(Kind_{type.ShortName}, x, y)) return true;");
            }
        }

        EmitPredicates(items.Select(i => Eq(i.Type, "x." + i.Path, "y." + i.Path)).ToList(), terminalReturnTrue: true);
        _w.Close();

        for (int level = 1; level >= (type.HasShallowHash ? 0 : 1); level--)
        {
            string name = (level == 1 ? "GetHashCode_" : "ShallowHashCode_") + type.ShortName;
            _w.Open($"private static int {name}({p} o)");
            if (reference)
            {
                _w.Line("if (o is null) return 0;");
            }

            List<string> inputs = new List<string>();
            foreach ((TypeModel itemType, string path, bool sameScc) in items)
            {
                string? hash = HashOrOmit(itemType, "o." + path, level, sameScc);
                if (hash is not null)
                {
                    inputs.Add(hash);
                }
            }

            _w.Line($"return {Combine(inputs)};");
            _w.Close();
        }

        _w.Line();
    }

    // ----- accessors ------------------------------------------------------------------------------------------------------------

    private void EmitAccessors()
    {
        HashSet<string> emitted = new HashSet<string>(StringComparer.Ordinal);
        Dictionary<string, List<MemberModel>> generic = new Dictionary<string, List<MemberModel>>(StringComparer.Ordinal);
        foreach (TypeModel type in _types)
        {
            foreach (MemberModel member in type.Members)
            {
                if (member.Access != MemberAccess.UnsafeAccessor)
                {
                    continue;
                }

                if (member.GenericAccessor)
                {
                    if (!generic.TryGetValue(member.GenericHolderName, out List<MemberModel>? list))
                    {
                        generic[member.GenericHolderName] = list = new List<MemberModel>();
                    }

                    if (!list.Any(m => m.AccessorName == member.AccessorName))
                    {
                        list.Add(member);
                    }

                    continue;
                }

                if (!emitted.Add(member.AccessorName))
                {
                    continue;
                }

                TypeModel fieldType = T(member.TypeId);
                string receiver = member.DeclaringTypeIsValueType ? $"ref {member.DeclaringTypeGlobalName} o" : $"{member.DeclaringTypeGlobalName} o";
                _w.Line($"[{KnownTypes.GlobalUnsafeAccessor}({KnownTypes.GlobalUnsafeAccessorKind}.Field, Name = \"{member.FieldMetadataName}\")]");
                _w.Line($"private static extern ref {Param(fieldType)} {member.AccessorName}({receiver});");
            }
        }

        if (emitted.Count > 0)
        {
            _w.Line();
        }

        // The runtime maps the holder's class type parameters onto the declaring type's, so one holder per definition
        // carries every accessor of that definition; call sites name the constructed arguments.
        foreach (KeyValuePair<string, List<MemberModel>> holder in generic.OrderBy(h => h.Key, StringComparer.Ordinal))
        {
            MemberModel first = holder.Value[0];
            _w.Open($"private static class {holder.Key}{first.GenericTypeParameters}{first.GenericConstraints}");
            foreach (MemberModel member in holder.Value.OrderBy(m => m.AccessorName, StringComparer.Ordinal))
            {
                string openReceiver = member.DeclaringTypeIsValueType ? $"ref {member.OpenDeclaringTypeGlobalName} o" : $"{member.OpenDeclaringTypeGlobalName} o";
                _w.Line($"[{KnownTypes.GlobalUnsafeAccessor}({KnownTypes.GlobalUnsafeAccessorKind}.Field, Name = \"{member.FieldMetadataName}\")]");
                _w.Line($"internal static extern ref {member.OpenFieldTypeGlobalName} {member.AccessorName}({openReceiver});");
            }

            _w.Close();
            _w.Line();
        }
    }

    private void EmitAccessorHolders()
    {
        foreach (AccessorHolderModel holder in _model.AccessorHolders)
        {
            if (_model.Capabilities.HasRequiresUnreferencedCode)
            {
                _w.Line("[global::System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode(\"Reads private fields by name through reflection-built delegates.\")]");
            }

            if (_model.Capabilities.HasRequiresDynamicCode)
            {
                _w.Line("[global::System.Diagnostics.CodeAnalysis.RequiresDynamicCode(\"Compiles expression trees for private field access.\")]");
            }

            _w.Open($"private static class {holder.HolderName}");
            _w.Line($"static {holder.HolderName}() {{ }}");
            foreach (MemberModel member in holder.Members)
            {
                TypeModel fieldType = T(member.TypeId);
                string getter = $"{KnownTypes.GlobalFieldGetter}<{holder.DeclaringTypeGlobalName}, {Param(fieldType)}>";
                _w.Line($"private static readonly {getter} s_{member.AccessorName} = {KnownTypes.GlobalReflection}.CreateFieldGetter<{holder.DeclaringTypeGlobalName}, {Param(fieldType)}>(typeof({holder.DeclaringTypeGlobalName}), \"{member.FieldMetadataName}\");");
                _w.Line(holder.DeclaringTypeIsValueType
                    ? $"internal static {Param(fieldType)} {member.AccessorName}(ref {holder.DeclaringTypeGlobalName} o) => s_{member.AccessorName}(ref o);"
                    : $"internal static {Param(fieldType)} {member.AccessorName}({holder.DeclaringTypeGlobalName} o) => s_{member.AccessorName}(ref o);");
            }

            _w.Close();
            _w.Line();
        }
    }

    private void EmitCustomComparerHolders()
    {
        foreach (CustomComparerModel custom in _model.CustomComparers)
        {
            string fieldType = custom.HolderTypedAsComparer ? custom.ComparerTypeGlobalName : $"{KnownTypes.GlobalIEqualityComparer}<{custom.TargetTypeGlobalName}>";
            _w.Open($"private static class {custom.HolderName}");
            _w.Line($"static {custom.HolderName}() {{ }}");
            _w.Line($"internal static readonly {fieldType} Value = {custom.AcquisitionExpression};");
            _w.Close();
            _w.Line();
        }
    }
}

internal static class HeaderStringExtensions
{
    /// <summary>The string, or the fallback when it is empty.</summary>
    public static string OrDefault(this string value, string fallback) => value.Length == 0 ? fallback : value;
}
