#Requires -Version 5.1
<#
.SYNOPSIS
    Prepends the MIT copyright header to C# source files, and dates LICENSE.txt.

.DESCRIPTION
    The header has the following shape: a copyright line, the repository the source lives
    in, and the licence it is governed by, whose full text is in LICENSE.txt.
    The copyright year is the year the file was last touched.
    LICENSE.txt has the year of the latest commit.

    Script is idempotent: re-running is necessary and expected.

.PARAMETER Path
    Git pathspecs limiting which files are considered. Defaults to the whole repository.

.PARAMETER Author
    The copyright holder, written into the copyright line.

.PARAMETER Repository
    The repository URL. Defaults to origin's, with any .git suffix and scp-style syntax normalised
    into something that can be pasted into a browser.

.EXAMPLE
    ./eng/Add-LicenseHeader.ps1 -WhatIf

    Reports what would change without writing anything.
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [string[]] $Path = @(),
    [string] $Author = 'Jeremy Morren <jeremy.morren@outlook.com>',
    [string] $License = 'MIT License',
    [string] $LicenseFile = 'LICENSE.txt',
    [string] $Repository
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Invoke-Git {
    $output = & git @args
    if ($LASTEXITCODE -ne 0) {
        throw "git $($args -join ' ') failed with exit code $LASTEXITCODE"
    }
    return $output
}

$root = (Invoke-Git rev-parse --show-toplevel) -replace '/', [System.IO.Path]::DirectorySeparatorChar

if (-not $Repository) {
    $Repository = (Invoke-Git remote get-url origin).Trim()
    # A URL in a header is there to be followed, so give it in the form a browser accepts.
    $Repository = $Repository -replace '^git@([^:]+):', 'https://$1/' -replace '\.git$', ''
}

# The first line of a header of ours. Nothing is replaced unless a file opens with this, so a file
# whose own comment sits at the top is never mistaken for a header and eaten.
$copyright = '^// Copyright \d{4} .+\. All rights reserved\.$'

# What may follow it. Header lines are consumed while they match one of these, which stops at the
# file's own comment and still recognises the shapes earlier versions of this script wrote.
$continuation = @(
    '^// Source code is available at \S+$'
    '^// Use of this source code is governed by\b.*$'
    '^// as found in the .+ file\.?$'
    '^// https?://\S+$'
    # Add-CommitDetails.ps1 appends this in CI and it is never committed, so finding one here means
    # a stale stamp from a local experiment. Consuming it is how it gets cleaned up.
    '^// Built from source at \S+$'
)

# Tracked and untracked alike, minus everything .gitignore excludes.
$files = @(Invoke-Git ls-files --cached --others --exclude-standard -- @Path |
    Where-Object { $_ -like '*.cs' } |
    Sort-Object -Unique)

# A file with working-tree changes was touched now; an untracked one has no commit to ask about. For
# a clean file the mtime is only when it was checked out, so there the commit date is the authority.
$dirty = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
foreach ($changed in @(Invoke-Git diff --name-only HEAD) + @(Invoke-Git ls-files --others --exclude-standard)) {
    [void] $dirty.Add($changed)
}

# One walk of the history rather than a git call per file. The log runs newest first, so the first
# commit a path appears under is the one that last touched it.
$committedYear = @{}
$year = 0
foreach ($line in Invoke-Git log --format=%ad --date=format:%Y --name-only --no-renames) {
    if ($line -match '^\d{4}$') {
        $year = [int] $line
    }
    elseif ($line -and -not $committedYear.ContainsKey($line)) {
        $committedYear[$line] = $year
    }
}

$added = 0
$replaced = 0
$unchanged = 0
$skipped = 0

foreach ($file in $files) {
    $full = Join-Path $root $file

    $bytes = [System.IO.File]::ReadAllBytes($full)
    $hasBom = $bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF
    $text = [System.IO.File]::ReadAllText($full)

    # Generated files are rewritten by their generator, which would drop anything added here. The
    # emitted-header template counts: a copyright line added there would land in generated output.
    if ((($text -split '\r?\n') | Select-Object -First 5) -match '<auto-generated') {
        Write-Verbose "$file`: skipped, generated"
        $skipped++
        continue
    }

    # How much of the file is a header of ours, and so is to be replaced rather than pushed down.
    # Line by line: the anchors in these patterns are end-of-string in .NET regex, not end-of-line,
    # so they only mean what they read as when the subject is a single line.
    $keep = 0
    $first = [regex]::Match($text, '\A([^\r\n]*)(?:\r?\n|\z)')
    if ($first.Groups[1].Value -match $copyright) {
        $keep = $first.Length
        while ($true) {
            $line = [regex]::Match($text.Substring($keep), '\A([^\r\n]*)(?:\r?\n|\z)')
            if (@($continuation | Where-Object { $line.Groups[1].Value -match $_ }).Count -eq 0) {
                break
            }

            $keep += $line.Length
        }

        $keep += [regex]::Match($text.Substring($keep), '\A(?:\r?\n)+').Length
    }
    elseif ($text -match '\A(?://[^\r\n]*(?:\r?\n|\z))+' -and $Matches[0] -match '(?i)copyright') {
        Write-Warning "$file`: skipped, it carries a copyright header this script did not write"
        $skipped++
        continue
    }

    if ($dirty.Contains($file) -or -not $committedYear.ContainsKey($file)) {
        $touched = (Get-Item -LiteralPath $full).LastWriteTime.Year
    }
    else {
        $touched = $committedYear[$file]
    }

    $newline = if ($text.Contains("`r`n")) { "`r`n" } else { "`n" }
    $header = @(
        "// Copyright $touched $Author. All rights reserved."
        "// Source code is available at $Repository"
        "// Use of this source code is governed by the $License as found in the $LicenseFile file"
        ''
    ) -join $newline

    $new = $header + $newline + $text.Substring($keep)
    $action = if ($keep -gt 0) { 'replaced' } else { 'added' }

    if ($new -ceq $text) {
        Write-Verbose "$file`: unchanged"
        $unchanged++
        continue
    }

    if ($PSCmdlet.ShouldProcess($file, "$action header ($touched)")) {
        [System.IO.File]::WriteAllText($full, $new, [System.Text.UTF8Encoding]::new($hasBom))
    }

    Write-Verbose "$file`: $action ($touched)"
    if ($action -eq 'added') { $added++ } else { $replaced++ }
}

Write-Host "$($files.Count) file(s): $added added, $replaced replaced, $unchanged unchanged, $skipped skipped."

# The licence is granted over the repository as a whole, so it is dated by the last commit rather
# than by any one file. Only the year moves; the holder and the licence text are left alone.
$licensePath = Join-Path $root $LicenseFile
if (Test-Path -LiteralPath $licensePath) {
    $licenseYear = [int] (Invoke-Git log -1 --format=%ad --date=format:%Y)
    $text = [System.IO.File]::ReadAllText($licensePath)
    $new = [regex]::Replace($text, '(?m)^(Copyright \(c\) )\d{4}\b', "`${1}$licenseYear")

    if ($new -cne $text -and $PSCmdlet.ShouldProcess($LicenseFile, "set the copyright year to $licenseYear")) {
        [System.IO.File]::WriteAllText($licensePath, $new, [System.Text.UTF8Encoding]::new($false))
    }

    Write-Host "$LicenseFile`: copyright year $licenseYear."
}
