#Requires -Version 5.1
<#
.SYNOPSIS
    Appends the commit a source file was built from to its copyright header. CI only.

.DESCRIPTION
    Runs in the GitHub Actions job that packs, between checkout and dotnet pack, so that the sources
    compiled into the package carry a link to the exact blob they came from.

    The line is never committed: it names the commit being built, and a commit cannot name itself.
    That is also why this refuses to run anywhere but GitHub Actions -- outside it there is no commit
    being built, and the edit would be left behind in someone's working tree.

    Add-LicenseHeader.ps1 writes the header this appends to, so run that first and commit its result.
    A source file without a header is an error rather than something to skip: the package would ship
    a file whose provenance is missing, which is the one thing this script exists to prevent.

.PARAMETER Path
    Git pathspecs limiting which files are considered. Defaults to the whole repository.

.PARAMETER Repository
    The repository URL. Defaults to the one GitHub Actions is running against.

.PARAMETER Commit
    The full commit SHA to link to. Defaults to the one GitHub Actions is building.
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [string[]] $Path = @(),
    [string] $Repository,
    [string] $Commit
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if ($env:GITHUB_ACTIONS -ne 'true') {
    throw 'Add-CommitDetails.ps1 runs under GitHub Actions only. It rewrites tracked files in place with a line naming the commit being built, which is not something to leave behind in a working tree.'
}

function Invoke-Git {
    $output = & git @args
    if ($LASTEXITCODE -ne 0) {
        throw "git $($args -join ' ') failed with exit code $LASTEXITCODE"
    }
    return $output
}

$root = (Invoke-Git rev-parse --show-toplevel) -replace '/', [System.IO.Path]::DirectorySeparatorChar

if (-not $Repository) {
    # Composed from the environment rather than from origin, so the link points at the server the
    # workflow is actually running against.
    $Repository = "$env:GITHUB_SERVER_URL/$env:GITHUB_REPOSITORY".TrimEnd('/')
}

if (-not $Commit) {
    $Commit = $env:GITHUB_SHA
}

if ($Commit -notmatch '^[0-9a-f]{40}$') {
    throw "Expected a full commit SHA, got '$Commit'. An abbreviated or missing SHA makes a link that will not resolve."
}

# The header Add-LicenseHeader.ps1 writes, one pattern per line it may contain. The provenance line
# is in the list so that a second run replaces it instead of appending another.
$copyright = '^// Copyright \d{4} .+\. All rights reserved\.$'
$continuation = @(
    '^// Source code is available at \S+$'
    '^// Use of this source code is governed by\b.*$'
    '^// Built from source at \S+$'
)

# Tracked and untracked alike, minus everything .gitignore excludes.
$files = @(Invoke-Git ls-files --cached --others --exclude-standard -- @Path |
    Where-Object { $_ -like '*.cs' } |
    Sort-Object -Unique)

$stamped = 0
$skipped = 0
$missing = @()

foreach ($file in $files) {
    $full = Join-Path $root $file

    $bytes = [System.IO.File]::ReadAllBytes($full)
    $hasBom = $bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF
    $text = [System.IO.File]::ReadAllText($full)

    # Generated files are rewritten by their generator, and carry no header to append to.
    if ((($text -split '\r?\n') | Select-Object -First 5) -match '<auto-generated') {
        Write-Verbose "$file`: skipped, generated"
        $skipped++
        continue
    }

    # The header block, read line by line: the anchors in these patterns are end-of-string in .NET
    # regex, not end-of-line, so they only mean what they read as when the subject is a single line.
    $header = @()
    $end = 0
    while ($true) {
        $line = [regex]::Match($text.Substring($end), '\A([^\r\n]*)(?:\r?\n|\z)')
        $value = $line.Groups[1].Value
        $isHeader = if ($end -eq 0) {
            $value -match $copyright
        }
        else {
            @($continuation | Where-Object { $value -match $_ }).Count -gt 0
        }

        if (-not $isHeader) {
            break
        }

        $header += $value
        $end += $line.Length
    }

    if ($end -eq 0) {
        $missing += $file
        continue
    }

    $newline = if ($text.Contains("`r`n")) { "`r`n" } else { "`n" }
    $header = @($header | Where-Object { $_ -notmatch '^// Built from source at ' })
    $header += "// Built from source at $Repository/blob/$Commit/$file"

    $new = ($header -join $newline) + $newline + $text.Substring($end)

    if ($new -cne $text -and $PSCmdlet.ShouldProcess($file, 'append the commit it was built from')) {
        [System.IO.File]::WriteAllText($full, $new, [System.Text.UTF8Encoding]::new($hasBom))
    }

    Write-Verbose "$file`: stamped"
    $stamped++
}

if ($missing.Count -gt 0) {
    $list = ($missing | ForEach-Object { "  $_" }) -join [System.Environment]::NewLine
    throw "No copyright header on $($missing.Count) file(s), so there is nothing to append the commit to. Run eng/Add-LicenseHeader.ps1 and commit the result.$([System.Environment]::NewLine)$list"
}

Write-Host "$($files.Count) file(s): $stamped stamped at $Commit, $skipped skipped."
