<#
.SYNOPSIS
Emits the fixed-arity DeepEqualsHashCode.Combine and DeepEqualsHashCode64.Combine overloads.

.DESCRIPTION
Width 32: every overload is straight-line xxHash32 over 32-bit lanes, exactly the stream System.HashCode uses:
fewer than four inputs start from seed + Prime5 and apply queue rounds; four or more initialize the
four accumulators, apply one round per input in groups of four, mix the accumulators, then queue the
remaining one to three inputs. The input count times four is folded in before the tail, and the
final avalanche closes the hash.

Width 64: the same shape over 64-bit lanes as xxHash64 defines it: the accumulator mix merges each lane
back into the hash, the input count times eight is folded in, and every remaining word takes the 8-byte
tail round. The output is checked in and never edited by hand.
#>
param(
    [ValidateSet(32, 64)]
    [int] $Width = 32,
    [int] $MaxArity = 32,
    [string] $OutputPath = ''
)

if ($OutputPath -eq '') {
    $file = if ($Width -eq 64) { 'DeepEqualsHashCode64.Combine.g.cs' } else { 'DeepEqualsHashCode.Combine.g.cs' }
    $OutputPath = Join-Path $PSScriptRoot "..\src\DeepEquals.SourceGeneration.Framework\$file"
}

$class = if ($Width -eq 64) { 'DeepEqualsHashCode64' } else { 'DeepEqualsHashCode' }
$word = if ($Width -eq 64) { 'ulong' } else { 'int' }
$lane = if ($Width -eq 64) { 'ulong' } else { 'uint' }
$cast = if ($Width -eq 64) { '' } else { '(uint)' }
$stream = if ($Width -eq 64) { 'xxHash64' } else { 'xxHash32' }
$bytesPerWord = $Width / 8

$sb = [System.Text.StringBuilder]::new()
$sb.AppendLine('// <auto-generated/>')
$sb.AppendLine("// Generated by eng/Generate-HashCodeCombine.ps1 -Width $Width -MaxArity $MaxArity. Do not edit.")
$sb.AppendLine('using System.Runtime.CompilerServices;')
$sb.AppendLine('')
$sb.AppendLine('namespace DeepEquals.SourceGeneration.Framework;')
$sb.AppendLine('')
$sb.AppendLine("public static partial class $class")
$sb.AppendLine('{')

for ($n = 1; $n -le $MaxArity; $n++) {
    $parameters = (1..$n | ForEach-Object { "$word h$_" }) -join ', '
    $sb.AppendLine("    /// <summary>Combines $n already computed hash codes with the seeded $stream stream.</summary>")
    if ($n -le 3) {
        $sb.AppendLine('    [MethodImpl(MethodImplOptions.AggressiveInlining)]')
    }
    $sb.AppendLine("    public static $word Combine($parameters)")
    $sb.AppendLine('    {')
    $sb.AppendLine('        unchecked')
    $sb.AppendLine('        {')
    $sb.AppendLine("            $lane seed = s_seed;")
    $sb.AppendLine("            $lane hash;")
    if ($n -ge 4) {
        $sb.AppendLine("            $lane v1 = seed + Prime1 + Prime2;")
        $sb.AppendLine("            $lane v2 = seed + Prime2;")
        $sb.AppendLine("            $lane v3 = seed;")
        $sb.AppendLine("            $lane v4 = seed - Prime1;")
        $groups = [math]::Floor($n / 4)
        for ($g = 0; $g -lt $groups; $g++) {
            $base = 4 * $g
            $sb.AppendLine("            v1 = Round(v1, $cast" + "h$($base + 1));")
            $sb.AppendLine("            v2 = Round(v2, $cast" + "h$($base + 2));")
            $sb.AppendLine("            v3 = Round(v3, $cast" + "h$($base + 3));")
            $sb.AppendLine("            v4 = Round(v4, $cast" + "h$($base + 4));")
        }
        $sb.AppendLine('            hash = MixState(v1, v2, v3, v4);')
        $tailStart = 4 * $groups + 1
    }
    else {
        $sb.AppendLine('            hash = seed + Prime5;')
        $tailStart = 1
    }
    $sb.AppendLine("            hash += $($bytesPerWord * $n)U;")
    for ($i = $tailStart; $i -le $n; $i++) {
        $sb.AppendLine("            hash = QueueRound(hash, $cast" + "h$i);")
    }
    $sb.AppendLine('            hash = MixFinal(hash);')
    $sb.AppendLine("            return ($word)hash;")
    $sb.AppendLine('        }')
    $sb.AppendLine('    }')
    if ($n -lt $MaxArity) {
        $sb.AppendLine('')
    }
}

$sb.AppendLine('}')

$fullPath = [System.IO.Path]::GetFullPath($OutputPath)
[System.IO.File]::WriteAllText($fullPath, $sb.ToString().Replace("`r`n", "`n"), [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote $fullPath"
