<#
.SYNOPSIS
Emits the fixed-arity DeepEqualsHashCode.Combine overloads.

.DESCRIPTION
Every overload is straight-line xxHash32 over 32-bit lanes, exactly the stream System.HashCode uses:
fewer than four inputs start from seed + Prime5 and apply queue rounds; four or more initialize the
four accumulators, apply one round per input in groups of four, mix the accumulators, then queue the
remaining one to three inputs. The input count times four is folded in before the tail, and the
final avalanche closes the hash. The output is checked in and never edited by hand.
#>
param(
    [int] $MaxArity = 32,
    [string] $OutputPath = (Join-Path $PSScriptRoot '..\src\DeepEquals.SourceGeneration.Framework\DeepEqualsHashCode.Combine.g.cs')
)

$sb = [System.Text.StringBuilder]::new()
$sb.AppendLine('// <auto-generated/>')
$sb.AppendLine("// Generated by eng/Generate-HashCodeCombine.ps1 -MaxArity $MaxArity. Do not edit.")
$sb.AppendLine('using System.Runtime.CompilerServices;')
$sb.AppendLine('')
$sb.AppendLine('namespace DeepEquals.SourceGeneration.Framework;')
$sb.AppendLine('')
$sb.AppendLine('public static partial class DeepEqualsHashCode')
$sb.AppendLine('{')

for ($n = 1; $n -le $MaxArity; $n++) {
    $parameters = (1..$n | ForEach-Object { "int h$_" }) -join ', '
    $sb.AppendLine("    /// <summary>Combines $n already computed hash codes with the seeded xxHash32 stream.</summary>")
    if ($n -le 3) {
        $sb.AppendLine('    [MethodImpl(MethodImplOptions.AggressiveInlining)]')
    }
    $sb.AppendLine("    public static int Combine($parameters)")
    $sb.AppendLine('    {')
    $sb.AppendLine('        unchecked')
    $sb.AppendLine('        {')
    $sb.AppendLine('            uint seed = s_seed;')
    $sb.AppendLine('            uint hash;')
    if ($n -ge 4) {
        $sb.AppendLine('            uint v1 = seed + Prime1 + Prime2;')
        $sb.AppendLine('            uint v2 = seed + Prime2;')
        $sb.AppendLine('            uint v3 = seed;')
        $sb.AppendLine('            uint v4 = seed - Prime1;')
        $groups = [math]::Floor($n / 4)
        for ($g = 0; $g -lt $groups; $g++) {
            $base = 4 * $g
            $sb.AppendLine("            v1 = Round(v1, (uint)h$($base + 1));")
            $sb.AppendLine("            v2 = Round(v2, (uint)h$($base + 2));")
            $sb.AppendLine("            v3 = Round(v3, (uint)h$($base + 3));")
            $sb.AppendLine("            v4 = Round(v4, (uint)h$($base + 4));")
        }
        $sb.AppendLine('            hash = MixState(v1, v2, v3, v4);')
        $tailStart = 4 * $groups + 1
    }
    else {
        $sb.AppendLine('            hash = seed + Prime5;')
        $tailStart = 1
    }
    $sb.AppendLine("            hash += $(4 * $n)U;")
    for ($i = $tailStart; $i -le $n; $i++) {
        $sb.AppendLine("            hash = QueueRound(hash, (uint)h$i);")
    }
    $sb.AppendLine('            hash = MixFinal(hash);')
    $sb.AppendLine('            return (int)hash;')
    $sb.AppendLine('        }')
    $sb.AppendLine('    }')
    if ($n -lt $MaxArity) {
        $sb.AppendLine('')
    }
}

$sb.AppendLine('}')

$fullPath = [System.IO.Path]::GetFullPath($OutputPath)
[System.IO.File]::WriteAllText($fullPath, $sb.ToString().Replace("`r`n", "`n"), [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote $fullPath"
