// Copyright 2026 Jeremy Morren <jeremy.morren@outlook.com>. All rights reserved.
// Source code is available at https://github.com/jeremy-morren/DeepEquals.SourceGenerator
// Use of this source code is governed by the MIT License as found in the LICENSE.txt file

using System;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using FluentAssertions;
using Microsoft.CodeAnalysis;
using Xunit;
using Xunit.Abstractions;

namespace DeepEquals.SourceGenerator.Tests;

[SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments")]
public sealed class BasicGenerationTests
{
    private readonly ITestOutputHelper _output;

    public BasicGenerationTests(ITestOutputHelper output) => _output = output;

    private const string Prelude = 
        """
        using System;
        using System.Collections.Generic;
        using DeepEquals.SourceGeneration;
        namespace Tests;
        """;

    private GeneratorRun RunAndAssertClean(string source)
    {
        var run = GeneratorHost.Run(Prelude + source);
        if (run.CompileErrors.Any() || run.GeneratorDiagnostics.Any(d => d.Severity == DiagnosticSeverity.Error))
        {
            var dump = Environment.GetEnvironmentVariable("DEEPEQUALS_DUMP");
            if (dump is not null)
            {
                System.IO.Directory.CreateDirectory(dump);
                System.IO.File.WriteAllText(System.IO.Path.Combine(dump, "last.g.cs"), run.GeneratedSource);
                System.IO.File.WriteAllText(System.IO.Path.Combine(dump, "last.errors.txt"), 
                    string.Join(Environment.NewLine, run.CompileErrors.Concat(run.GeneratorDiagnostics.Select(d => d.ToString()))));
            }

            _output.WriteLine(string.Join(Environment.NewLine, run.CompileErrors));
        }

        run.GeneratorDiagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).Should().BeEmpty();
        run.CompileErrors.Should().BeEmpty();
        run.Assembly.Should().NotBeNull();
        return run;
    }

    [Fact]
    public void Output_is_one_context_file_plus_one_file_per_emitted_type()
    {
        var run = RunAndAssertClean(
            """
            public sealed class Person { public string? Name; public int Age; public int[]? Scores; }

            [GenerateDeepEquals(typeof(Person))]
            public partial class Ctx : DeepEqualsContextBase { }
            """);

        var files = run.Result.Results.Single().GeneratedSources.ToDictionary(s => s.HintName, s => s.SourceText.ToString());

        // The hint name is the context's namespace-qualified name, no hash, then the type's short name.
        files.Keys.Should().Contain("Tests.Ctx.g.cs", "Tests.Ctx.Person.g.cs", "Tests.Ctx.ArrayOfInt32.g.cs", "Tests.Ctx.Int32.g.cs", "Tests.Ctx.String.g.cs");
        files.Keys.Should().OnlyContain(k => k.StartsWith("Tests.Ctx.", StringComparison.Ordinal) && k.EndsWith(".g.cs", StringComparison.Ordinal));

        // The context file alone carries the description; a type file has only the auto-generated notice.
        files["Tests.Ctx.g.cs"].Should().Contain("GetEqualityComparer<T>()").And.Contain("Registered roots").And.Contain("Options in effect")
            .And.NotContain("Closure", "the header does not list the discovered types");
        files["Tests.Ctx.Person.g.cs"].Should().Contain("class PersonEqualityComparer").And.Contain("// <auto-generated>")
            .And.NotContain("/*").And.NotContain("Registered roots").And.NotContain("Options in effect");
        files["Tests.Ctx.Person.g.cs"].Should().NotContain("class Int32EqualityComparer", "each type lives in its own file");
        files["Tests.Ctx.Int32.g.cs"].Should().Contain("Equals_SpanOfInt32", "a span core lives with its element type");
        files.Values.Should().OnlyContain(f => f.Contains("partial class Ctx"), "every file is a partial declaration of the context");
    }

    /// <summary>
    /// A private field of a generic type is read through a delegate where the runtime has no generic
    /// <c>[UnsafeAccessor]</c>, as on .NET 8; newer runtimes take the accessor and need no notice at all.
    /// </summary>
    [Fact]
    public void Trimming_notices_sit_in_the_files_of_the_types_they_affect()
    {
        var run = RunAndAssertClean(
            """
            public sealed class Box<T> { private T _value; public Box(T value) { _value = value; } }
            public sealed class Holder { public Box<int>? B; public int N; }
            public sealed class Plain { public int X; }

            [GenerateDeepEquals(typeof(Holder))]
            [GenerateDeepEquals(typeof(Plain))]
            public partial class Ctx : DeepEqualsContextBase { }
            """);

        var files = run.Result.Results.Single().GeneratedSources.ToDictionary(s => s.HintName, s => s.SourceText.ToString());
        files["Tests.Ctx.g.cs"].Should().NotContain("Trimming:").And.NotContain("delegate field accessors", "the context file carries no trimming list");
        files["Tests.Ctx.Plain.g.cs"].Should().NotContain("Trimming:", "Plain reaches no delegate accessor");

        // Only the delegate path marks comparers; an [UnsafeAccessor] holder needs no attribute and no notice.
        if (!files.Values.Any(f => f.Contains("RequiresUnreferencedCode(")))
        {
            files.Values.Should().NotContain(f => f.Contains("Trimming:"), "no field is read through a delegate on this runtime");
            return;
        }

        files["Tests.Ctx.BoxOfInt32.g.cs"].Should()
            .Contain("// Trimming: Tests.Box<int> is compared through delegate field accessors:")
            .And.Contain("// its private fields are read through reflection-built delegates, and trimming can remove those fields.")
            .And.Contain("// Its public comparer is marked [RequiresUnreferencedCode] and [RequiresDynamicCode].");
        files["Tests.Ctx.Holder.g.cs"].Should()
            .Contain("// Trimming: Tests.Holder is compared through delegate field accessors:")
            .And.Contain("// it reaches types whose private fields are read through reflection-built delegates");
        files["Tests.Ctx.Holder.g.cs"].IndexOf("// Trimming:", StringComparison.Ordinal).Should()
            .BeGreaterThan(files["Tests.Ctx.Holder.g.cs"].IndexOf("// </auto-generated>", StringComparison.Ordinal), "the notice follows the auto-generated block");
    }

    [Fact]
    public void Sealed_class_with_leaf_members_compares_by_value()
    {
        var run = RunAndAssertClean(
            """
            public sealed class Person
            {
                public string? Name { get; set; }
                public int Age;
                private double _score;
                public Person(double score) { _score = score; }
            }

            [GenerateDeepEquals(typeof(Person))]
            public partial class Ctx : DeepEqualsContextBase { }
            """);

        run.GeneratedSource.Should().Contain(
            "PersonEqualityComparer : global::System.Collections.Generic.IEqualityComparer<global::Tests.Person?>", 
            "a reference-type wrapper accepts null and says so in its interface");
        var comparer = run.Comparer("Ctx", "Person");
        var a = run.New("Person", 1.5);
        var b = run.New("Person", 1.5);
        var c = run.New("Person", -0.0);
        var d = run.New("Person", 0.0);
        Set(a, "Name", "x"); Set(b, "Name", "x"); Set(a, "Age", 3); Set(b, "Age", 3);

        run.Equals(comparer, a, b).Should().BeTrue();
        run.Hash(comparer, a).Should().Be(run.Hash(comparer, b));
        Set(b, "Age", 4);
        run.Equals(comparer, a, b).Should().BeFalse();
        run.Equals(comparer, c, d).Should().BeFalse("+0 and -0 differ bitwise");
        run.Equals(comparer, null, null).Should().BeTrue();
        run.Equals(comparer, a, null).Should().BeFalse();
        run.Hash(comparer, null).Should().Be(0);
    }

    [Fact]
    public void Cyclic_sealed_node_terminates_and_unrolled_cycles_are_equal()
    {
        var run = RunAndAssertClean(
            """
            public sealed class Node
            {
                public int Value;
                public Node? Next { get; set; }
                public List<Node>? Children { get; set; }
            }

            [GenerateDeepEquals(typeof(Node))]
            public partial class Ctx : DeepEqualsContextBase { }
            """);

        var comparer = run.Comparer("Ctx", "Node");
        var a = run.New("Node"); Set(a, "Value", 1); Set(a, "Next", a);
        var b1 = run.New("Node"); var b2 = run.New("Node");
        Set(b1, "Value", 1); Set(b2, "Value", 1); Set(b1, "Next", b2); Set(b2, "Next", b1);

        run.Equals(comparer, a, b1).Should().BeTrue("a 1-cycle equals a 2-cycle of equal nodes");
        run.Hash(comparer, a).Should().Be(run.Hash(comparer, b1));
        Set(b2, "Value", 2);
        run.Equals(comparer, a, b1).Should().BeFalse();

        // Long chain uses the tail loop.
        var head1 = Chain(run, 100_000);
        var head2 = Chain(run, 100_000);
        run.Equals(comparer, head1, head2).Should().BeTrue();
        run.Hash(comparer, head1).Should().Be(run.Hash(comparer, head2));
    }

    [Fact]
    public void Unsealed_hierarchy_dispatches_on_runtime_type_and_throws_for_unknown()
    {
        var run = RunAndAssertClean(
            """
            public abstract class Shape { public string? Name { get; set; } }
            public sealed class Circle : Shape { public double Radius { get; set; } }
            public class Square : Shape { public int Side { get; set; } }
            public sealed class Unknown : Shape { }

            [GenerateDeepEquals(typeof(Circle))]
            [GenerateDeepEquals(typeof(Square))]
            public partial class Ctx : DeepEqualsContextBase { }
            """);

        var shapes = run.Comparer("Ctx", "Shape");
        var c1 = run.New("Circle"); Set(c1, "Radius", 2.0); Set(c1, "Name", "c");
        var c2 = run.New("Circle"); Set(c2, "Radius", 2.0); Set(c2, "Name", "c");
        var s1 = run.New("Square"); Set(s1, "Side", 2); Set(s1, "Name", "c");
        run.Equals(shapes, c1, c2).Should().BeTrue();
        run.Equals(shapes, c1, s1).Should().BeFalse("different runtime types");
        run.Hash(shapes, c1).Should().Be(run.Hash(shapes, c2));

        var u1 = run.New("Unknown"); var u2 = run.New("Unknown");
        Action act = () => run.Equals(shapes, u1, u2);
        act.Should().Throw<System.Reflection.TargetInvocationException>().WithInnerException<SourceGeneration.Framework.DeepEqualsUnknownTypeException>();

        var objects = run.Comparer("Ctx", "Object");
        run.Equals(objects, c1, c2).Should().BeTrue();
        run.Equals(objects, "abc", "abc").Should().BeTrue("built-in leaves are admitted behind object");
        run.Equals(objects, 5, 5).Should().BeTrue();
        run.Equals(objects, 5, 6).Should().BeFalse();
        run.Equals(objects, new object(), new object()).Should().BeTrue("plain object is a zero-member exact case");
    }

    [Fact]
    public void Structs_nullables_sets_and_dictionaries_work()
    {
        var run = RunAndAssertClean(
            """
            public struct Point { public int X; public int Y; }
            public struct Big { public long A; public long B; public string? Tag; public Point Inner; }
            public sealed class Holder
            {
                public Point P;
                public Point? Maybe;
                public Big Large;
                public Big? MaybeLarge;
                public Dictionary<int, Big>? LargeByKey;
                public List<Big>? Larges;
                public (Big, int) LargePair;
                public object? AnyLarge;
                public HashSet<string>? Tags;
                public Dictionary<string, int>? Counts;
                public int[]? Values;
                public IReadOnlyList<Point>? Points;
                public (int, string) Pair;
                public KeyValuePair<int, Point> Kvp;
            }

            [GenerateDeepEquals(typeof(Holder))]
            public partial class Ctx : DeepEqualsContextBase { }
            """);

        var comparer = run.Comparer("Ctx", "Holder");
        var a = run.New("Holder");
        var b = run.New("Holder");
        Set(a, "Tags", new System.Collections.Generic.HashSet<string> { "x", "y" });
        Set(b, "Tags", new System.Collections.Generic.HashSet<string> { "y", "x" });
        Set(a, "Counts", new System.Collections.Generic.Dictionary<string, int> { ["a"] = 1, ["b"] = 2 });
        Set(b, "Counts", new System.Collections.Generic.Dictionary<string, int>(StringComparer.OrdinalIgnoreCase) { ["b"] = 2, ["a"] = 1 });
        Set(a, "Values", new[] { 1, 2, 3 });
        Set(b, "Values", new[] { 1, 2, 3 });
        run.Equals(comparer, a, b).Should().BeTrue();
        run.Hash(comparer, a).Should().Be(run.Hash(comparer, b));

        // A struct above StructPassByValueMaxByteSize reached through property reads and rvalues: in cores take those without `in`.
        var big = run.Assembly!.GetTypes().Single(t => t.Name == "Big");

        object Big(long x, string tag)
        {
            var v = Activator.CreateInstance(big)!;
            Set(v, "A", x); Set(v, "B", x + 1); Set(v, "Tag", tag);
            return v;
        }
        var dict = typeof(System.Collections.Generic.Dictionary<,>).MakeGenericType(typeof(int), big);
        var list = typeof(System.Collections.Generic.List<>).MakeGenericType(big);
        foreach (var h in new[] { a, b })
        {
            Set(h, "MaybeLarge", Big(1, "m"));
            var d = (System.Collections.IDictionary)Activator.CreateInstance(dict)!; d[5] = Big(2, "d");
            Set(h, "LargeByKey", d);
            var l = (System.Collections.IList)Activator.CreateInstance(list)!; l.Add(Big(3, "l"));
            Set(h, "Larges", l);
            Set(h, "LargePair", Activator.CreateInstance(typeof(ValueTuple<,>).MakeGenericType(big, typeof(int)), Big(4, "p"), 9));
            Set(h, "AnyLarge", Big(5, "o"));
        }
        run.Equals(comparer, a, b).Should().BeTrue();
        run.Hash(comparer, a).Should().Be(run.Hash(comparer, b));
        ((System.Collections.IDictionary)run.Assembly.GetType(a.GetType().FullName!)!.GetField("LargeByKey")!.GetValue(b)!)[5] = Big(2, "changed");
        run.Equals(comparer, a, b).Should().BeFalse("a large struct dictionary value differs");
        Set(b, "LargeByKey", null);
        Set(a, "LargeByKey", null);
        Set(b, "AnyLarge", Big(6, "o"));
        run.Equals(comparer, a, b).Should().BeFalse("a large struct behind object differs");
        Set(b, "AnyLarge", Big(5, "o"));
        run.Equals(comparer, a, b).Should().BeTrue();

        Set(b, "Values", new[] { 1, 2, 4 });
        run.Equals(comparer, a, b).Should().BeFalse();
        Set(b, "Values", new[] { 1, 2, 3 });
        Set(b, "Counts", new System.Collections.Generic.Dictionary<string, int> { ["A"] = 1, ["b"] = 2 });
        run.Equals(comparer, a, b).Should().BeFalse("keys are ordinal");
    }

    [Fact]
    public void Diagnostics_for_invalid_contexts()
    {
        var run = GeneratorHost.Run(
            $$"""
              {{Prelude}}public sealed class A { public int X; }
              [GenerateDeepEquals(typeof(A))]
              public class NotPartial : DeepEqualsContextBase { }
              [GenerateDeepEquals(typeof(A))]
              public partial struct NotAClass { }
              """, 
            load: false);

        run.GeneratorDiagnosticIds.Should().Contain("DEQ001");
        run.GeneratorDiagnosticIds.Should().Contain("DEQ002");
    }

    private static void Set(object target, string member, object? value)
    {
        var type = target.GetType();
        var field = type.GetField(member);
        if (field is not null)
        {
            field.SetValue(target, value);
            return;
        }

        type.GetProperty(member)!.SetValue(target, value);
    }

    private static object Chain(GeneratorRun run, int length)
    {
        var head = run.New("Node");
        Set(head, "Value", 0);
        var current = head;
        for (var i = 1; i < length; i++)
        {
            var next = run.New("Node");
            Set(next, "Value", i);
            Set(current, "Next", next);
            current = next;
        }

        return head;
    }
}
